<?php

// This file is automatically generated from messages.po.  Do not edit it!

$TRANSLATED_STRINGS = array(

'Last Login'
=> 'Dernier connexion',

'Latest Registered'
=> '',

'Network Directory'
=> 'Directoire de réseaux',

'Community Blog'
=> 'Blogue de communauté',

'Network directory'
=> 'Directoire de réseaux',

'Return to home network'
=> 'Acceuil',

'Create a network'
=> 'Créer un réseau',

'Home'
=> 'Acceuil',

'Me'
=> 'Moi',

'People'
=> 'Peuple',

'Groups'
=> 'Groupes',

'Search'
=> 'Rechercher',

'Tags:'
=> '',

'Invalid email address.  Please try again.'
=> '',

'There are no accounts in our system with the e-mail address <font color='
.'"blue">%s</font>.\n'
.'\n'
.'If you have spelled the address incorrectly or entered the wrong address, '
.'please try again.'
=> '',

'Recently Created'
=> 'Date de création',

'Recently Modified'
=> 'Date de modification',

'Largest Group'
=> 'Taille',

'Recent Media'
=> '',

'Sorry! you are not authorized to view content of this page'
=> '',

'Newest Groups'
=> '',

'Members'
=> 'Membres',

'Recover Password'
=> '',

'A link has been e-mailed to you to let you change your password.  Thanks!'
=> '',

'Forgotten your PeopleAggregator account information?'
=> '',

'Just enter the e-mail address you signed up with, and we\'ll mail you a link '
.'to change your password.'
=> '',

'E-mail address:'
=> '',

'Get new password'
=> '',

'Sort By'
=> '',

'No groups created yet. Be the first to <a href="%s">create one</a>!'
=> '',

'Most Popular Tags'
=> '',

'No tags added yet'
=> '',

'Recent Posts'
=> '',

'No content in personal blog.  <a href="%s">Click here to make a post</a>!'
=> '',

'Contents'
=> '',

'Create post'
=> '',

'Manage posts'
=> '',

'View my public page'
=> '',

'Showing results for tag %s.'
=> '',

'Invite'
=> '',

'Group Setting'
=> '',

'Moderate'
=> '',

'Join this group'
=> '',

'No content found.'
=> '',

'Click <a href="%s">here</a> to create one.'
=> '',

'Last login'
=> '',

'Latest registered'
=> '',

'Advertisement'
=> '',

'Gallery'
=> '',

'Images'
=> '',

'Video'
=> '',

'Audio'
=> '',

'No images have been published yet.'
=> '',

'No videos have been published yet.'
=> '',

'No audio has been published yet.'
=> '',

'Search Networks'
=> '',

'Take A Tour'
=> '',

'Network Statistics'
=> '',

'No image'
=> '',

'Network Default Links'
=> '',

'No links under this category'
=> '',

'No links have been added.'
=> '',

'PeopleAggregator Networks'
=> '',

'Already a member?'
=> '',

'Login now'
=> '',

'or'
=> '',

'Register'
=> 'Enregistrer',

'About us'
=> '',

'Features'
=> '',

'FAQ'
=> '',

'Roadmap'
=> '',

'Report Bugs'
=> '',

'Feedback'
=> '',

'Developer Wiki'
=> '',

'&copy; 2007 Broadband Mechanics, Inc.'
=> '',

'view all'
=> '',

'All Posts'
=> '',

'posted by %s at %s'
=> '',

'permalink'
=> '',

'comments'
=> '',

'Blog'
=> '',

'Event'
=> '',

'Review'
=> '',

'Image'
=> '',

'Group'
=> '',

'title'
=> '',

'%s - My Links - %s'
=> '',

'page_name'
=> '',

'%s - Edit your profile - %s'
=> '',

'Groups - %s'
=> '',

'Create Group'
=> '',

'Edit Group'
=> '',

'Could not retrieve file from URL: %s'
=> '',

'Previous'
=> '',

'Next'
=> '',

'Please login to access this page'
=> '',

'Network name'
=> '',

'Network address'
=> '',

'Network tagline'
=> '',

'Group name'
=> '',

'Group description'
=> '',

'Group tag'
=> '',

'Select age'
=> '',

'Under 10 years'
=> '',

'11-20 years'
=> '',

'21-30 years'
=> '',

'31-40 years'
=> '',

'Over 50 years'
=> '',

'Select horizontal position'
=> '',

'left'
=> '',

'center'
=> '',

'right'
=> '',

'Select vertical position'
=> '',

'top'
=> '',

'no name'
=> '',

'no email'
=> '',

'Your file is too large for the web server.  The largest file you can upload '
.'here is %.1fM.  If this is too small, please ask the administrator to '
.'increase the <code>upload_max_filesize</code> directive in <code>php.ini</'
.'code>.'
=> '',

'The uploaded file was only partially uploaded.'
=> '',

'No file was uploaded'
=> '',

'File %s not uploaded correctly.'
=> '',

'File too large; %s file uploads are limited to %s.  If this is too small, '
.'please ask the administrator to increase the limit.'
=> '',

'Invalid image file.'
=> '',

'Invalid media file.'
=> '',

'Invalid document type - supported formats are: %s'
=> '',

'File error: File already exists'
=> '',

'Security error: File %s is not an uploaded file:'
=> '',

'JOIN Network'
=> '',

'Unjoin Network'
=> '',

'Configure'
=> '',

'My Page'
=> '',

'My Widgets'
=> '',

'My Messages'
=> '',

'My Gallery'
=> '',

'My Events'
=> '',

'Edit My Account'
=> '',

'Themes'
=> '',

'Find people'
=> '',

'My friends'
=> '',

'People who call me friend'
=> '',

'Friends gallery'
=> '',

'Find groups'
=> '',

'Create'
=> '',

'Group Home'
=> '',

'Forum'
=> '',

'Group gallery'
=> '',

'Group Events'
=> '',

'Join'
=> '',

'Unjoin'
=> '',

'Delete'
=> '',

'Are you sure you want to delete this group'
=> '',

'Email Notification'
=> '',

'Bulletins'
=> '',

'Set Feature Network'
=> '',

'Manage Emblem'
=> '',

'Personalized Video'
=> '',

'Configure Splash Page'
=> '',

'Top Bar Enable/Disable'
=> '',

'Create User'
=> '',

'User Defaults'
=> '',

'Relationships'
=> '',

'Manage Users'
=> '',

'Manage Contents'
=> '',

'Manage Links'
=> '',

'General'
=> '',

'Customize UI'
=> '',

'Home Page'
=> '',

'User Default Page'
=> '',

'Group Directory Page'
=> '',

'Network Directory Page'
=> '',

'Send a message'
=> '',

'Change '
=> '',

'Are you sure you want to delete this Relationship'
=> '',

'Write Testimonial'
=> '',

'Write Comment'
=> '',

'Add as '
=> '',

'Create Post'
=> '',

'Messages '
=> '',

'Widgets'
=> '',

'Edit my account'
=> '',

'&copy;'
=> '',

'shortcuts'
=> '',

'logoff'
=> '',

'%s Networks'
=> '',

'register'
=> '',

'Location'
=> '',

'Begins'
=> '',

'Ends'
=> '',

'Right-click to download'
=> '',

'Download'
=> '',

'posted by %s on %s'
=> '',

'Invite people - %s'
=> '',

'Personal Events'
=> '',

'My events'
=> '',

'%s - My Widgets - %s'
=> '',

'Events'
=> '',

'Homepage'
=> '',

'My Groups'
=> '',

'My Recent Comments'
=> '',

'About:'
=> '',

'My %s'
=> '',

'%s - My Page - %s'
=> '',

'Manage Ads'
=> '',

'Manage Textpads'
=> '',

'Connected. Please, select contacts you want to import.'
=> '',

'We haven\'t found any contacts on your Windows Live account.'
=> '',

'Authentication failed!'
=> '',

'Username and/or password field can\'t be empty!'
=> '',

'Your Windows Live ID'
=> '',

'(your Windows Live email address)'
=> '',

'Enter your password'
=> '',

'Role can\'t be deleted.'
=> '',

'Successfully deleted.'
=> '',

'Select roles you want to associate with this user and press left/right arrow.'
=> '',

'Please enter a valid URL!'
=> '',

'Please, select one of the following Professional profiles: '
=> '',

'Please, select the XFN relations you want to import: '
=> '',

'Sorry, we couldn\'t any identity informations '
=> '',

'at: '
=> '',

'in your HTML text.'
=> '',

'We haven\'t found any contacts on your Plaxo account.'
=> '',

'Select authentication method'
=> '',

'Enter your Plaxo ID'
=> '',

'(email or AIM screen name)'
=> '',

'Networks are disabled.'
=> '',

'Content'
=> '',

'%s - Media Gallery - %s'
=> '',

'Configure Email'
=> '',

'View All Members'
=> '',

'View All Group Members'
=> '',

'%s - Themes - %s'
=> '',

'Edit Events'
=> '',

'Please confirm network deletion by selecting deletion checkbox.'
=> '',

'Network Statistics - %s'
=> '',

'General Network Settings'
=> '',

'Administration panel'
=> '',

'Featured Network'
=> '',

'Network of the Moment'
=> '',

'Relations'
=> '',

'User Information'
=> '',

'Blog contents'
=> '',

'Photo'
=> '',

'Added as a friend by'
=> '',

'Messages'
=> '',

'Flickr'
=> '',

'Delicious Links'
=> '',

'My Links'
=> '',

'My Networks'
=> '',

'About User'
=> '',

'External Feeds'
=> '',

'Largest Network'
=> '',

'No network created yet.'
=> '',

'Blog Settings'
=> '',

'You have 3 blog options:'
=> '',

'You can contribute to the community blog'
=> '',

'You also can have a personal blog. A personal blog shows up on your page '
.'with posts routed to the community blog by default. You can opt for those to '
.'only be on your personal blog.'
=> '',

'If you already have a blog, you can display your External Blog here.'
=> '',

'Add a personal blog'
=> '',

'Display my external blog here'
=> '',

'Save'
=> '',

'Configure external blog'
=> '',

'Mp3 Player'
=> '',

'Multiple networks are disabled - please configure your system for network '
.'operation.'
=> '',

'The current featured network is: <a href="%s">%s</a>'
=> '',

'Select a featured network:'
=> '',

'Select a network'
=> '',

'Just enter the e-mail address or login name you signed up with, and we\'ll '
.'mail you a link to change your password.'
=> '',

'Login Name'
=> '',

'There are no accounts in our system with the e-mail address <font color='
.'"blue">%s</font>.\n'
.'      \n'
.'      If you have spelled the address incorrectly or entered the wrong '
.'address, please try again.'
=> '',

'No comments posted yet.'
=> '',

'Recent Comments'
=> '',

'Actions for '
=> '',

'Configure this Network'
=> '',

'no data'
=> '',

'Age'
=> '',

'Gender'
=> '',

'Add as'
=> '',

'Advanced Search'
=> '',

'Simple Search'
=> '',

'Recent Users'
=> '',

'Alphabetical'
=> '',

' with picture in profile'
=> '',

'Select rows'
=> '',

'First name'
=> '',

'Last name'
=> '',

'Find Users'
=> '',

'Male'
=> '',

'Female'
=> '',

'Any'
=> '',

'City'
=> '',

'State'
=> '',

'Company Name'
=> '',

'Interests'
=> '',

'Industry'
=> '',

'No contents in blog.  <a href="%s">Click here to make a post</a>!'
=> '',

'Author of this content is no longer a member of this group'
=> '',

'Moderate Group Members'
=> '',

'Moderate Membership'
=> '',

'Moderate Content'
=> '',

'There are no pending moderation requests'
=> '',

'Moderation'
=> '',

'Remove selected members from the group'
=> '',

'There are no members in this group'
=> '',

'No celebrities added yet.'
=> '',

'Recent Celebrities'
=> '',

'%s\'s Group Blog'
=> '',

'Group Settings'
=> '',

'Manage content'
=> '',

'Click <a href="%s">here</a> to add content.'
=> '',

'User image.'
=> '',

'More Detail'
=> '',

'Sex'
=> '',

'Date of birth'
=> '',

'ZIP code'
=> '',

'Country'
=> '',

'Delicious'
=> '',

'User Tags (Interests)'
=> '',

'No details entered yet.'
=> '',

'Professional'
=> '',

'Headline'
=> '',

'Company'
=> '',

'Title'
=> '',

'Website'
=> '',

'Career skill'
=> '',

'Download CV'
=> '',

'Prior Company'
=> '',

'Degree'
=> '',

'Personal'
=> '',

'Ethnicity'
=> '',

'Religion'
=> '',

'Political view'
=> '',

'Passion'
=> '',

'Activities'
=> '',

'Books'
=> '',

'Movies'
=> '',

'Music'
=> '',

'Cuisines'
=> '',

'TV shows'
=> '',

'About: %s'
=> '',

'You have not created any folders.'
=> '',

'Largest Groups'
=> '',

'Question of the Day'
=> '',

'No links have been added. Click <a href="%s">here</a> to add links.'
=> '',

'No links have been added'
=> '',

'Your Profile'
=> '',

'Please select the data import format and type<br />'
=> '',

'then click the \'import\' button.'
=> '',

'Your Profile as hCard/XFN'
=> '',

'Select the data you want to import:'
=> '',

'Your profile'
=> '',

'Your profile data are successfuly updated.'
=> '',

' can\'t be imported'
=> '',

'No data selected.'
=> '',

'Relations data: '
=> '',

'Size'
=> '',

'Date Created'
=> '',

'Group Directory'
=> '',

'Create a Group'
=> '',

'Search Groups'
=> '',

'Search for'
=> '',

'Member'
=> '',

'Created'
=> '',

'Moderated By'
=> '',

'No groups found.'
=> '',

'No networks in this category'
=> '',

'Manage Ad Center'
=> '',

'Edit Ad'
=> '',

'Create An Ad'
=> '',

'Page'
=> '',

'Orientation'
=> '',

'Display count'
=> '',

'Hit count'
=> '',

'Enable/Disable'
=> '',

'Edit'
=> '',

'Enable'
=> '',

'Disable'
=> '',

'Are you sure you want to delete this Ad'
=> '',

'In this page you can manage ads on your network'
=> '',

'Create New Ad'
=> '',

'Enter Title'
=> '',

'Title should not be greater than 30 characters'
=> '',

'Select An Image'
=> '',

'Preferred size'
=> '',

'for side modules and'
=> '',

'for center modules'
=> '',

'Previously Selected Image'
=> '',

'Enter URL'
=> '',

'Or Enter JavaScript(.js code)/ Html code'
=> '',

'Enter Description'
=> '',

'Select Page'
=> '',

'Select a page'
=> '',

'Select Horizontal position'
=> '',

'Edit Textpad'
=> '',

'Create Textpad'
=> '',

'Are you sure you want to delete this Textpad'
=> '',

'Available Textpads'
=> '',

'New Textpad'
=> '',

'Nothing has been tagged yet'
=> '',

'Browse Tags'
=> '',

'Click here to watch the video'
=> '',

'You cannot add an Event to the calendar of group %s, as you are not a member.'
=> '',

'Couldn\'t create event:'
=> '',

'Couldn\'t create EventAssociation:'
=> '',

'There was a problem updating the event:'
=> '',

'Event %d doesn\'t exist'
=> '',

'Couldn\'t update the event:'
=> '',

'There was a problem deleting the event:'
=> '',

'The event has been deleted.'
=> '',

'Couldn\'t delete the event:'
=> '',

'No users given'
=> '',

'There was a problem associating the event:'
=> '',

'%s is not a user'
=> '',

'Add people:'
=> '',

'You cannot add an Event to the caledar of group %s, as you are not a member.'
=> '',

'Add group:'
=> '',

'You may not remove the association to this event.'
=> '',

'You cannot remove yourself from this event, as you created it.  Please use '
.'\'Delete Event\' instead.'
=> '',

'Edit Event'
=> '',

'Create Event'
=> '',

'Event title'
=> '',

'Start date'
=> '',

'Start time'
=> '',

'End date'
=> '',

'End time'
=> '',

'Event venue'
=> '',

'Event description'
=> '',

'Current Event Banner'
=> '',

'Upload Event Banner'
=> '',

'Are you sure you want to delete this Event?'
=> '',

'Display as:'
=> '',

'List'
=> '',

'Calendar'
=> '',

'This event appears on'
=> '',

'Calendar for'
=> '',

'(This event will always appear in the creator\'s calendar.)'
=> '',

'Remove'
=> '',

'Add to further calendars'
=> '',

'Add people\'s login names here, seperated by commas.'
=> '',

'Groups you are a member of'
=> '',

'Add'
=> '',

'Event Banner'
=> '',

'Starts'
=> '',

'Venue'
=> '',

'Description'
=> '',

'Create new Event'
=> '',

's made yet.'
=> '',

'Invite friends and colleagues to join %s:'
=> '',

'Click to import your contacts from:'
=> '',

'Email:'
=> '',

'(separate addresses with commas)'
=> '',

'(separated by comma)'
=> '',

'Write your invitation Message:'
=> '',

'Send Invitation'
=> '',

'In this page you can manage groups on your network'
=> '',

'View all Members'
=> '',

'View all '
=> '',

'View all people who call '
=> '',

'me a friend'
=> '',

'Browse %d Groups'
=> '',

'No groups in this category'
=> '',

'Click <a href="%s">here</a> to enter your Flickr username or e-mail '
.'address to see your pictures!'
=> '',

'Loading'
=> '',

'No network joined yet.'
=> '',

'Search Content'
=> '',

'Search Terms'
=> '',

'all these words'
=> '',

'this exact phrase'
=> '',

'any of these words'
=> '',

'none of these words'
=> '',

'Date Range'
=> '',

'start date'
=> '',

'Select'
=> '',

'end date'
=> '',

'Showcased Members'
=> '',

'member'
=> '',

'No groups created yet. Be the first to <a href="%s" style="display:inline;'
.'">create one</a>!'
=> '',

'Back to search results'
=> '',

'Compose message'
=> '',

'Reply'
=> '',

'Forward'
=> '',

'Move to:'
=> '',

'- Select Folder -'
=> '',

'(no folders available)'
=> '',

'Date:'
=> '',

'From:'
=> '',

'To:'
=> '',

'Subject:'
=> '',

'There are no messages in this folder.'
=> '',

'No messages matched your search'
=> '',

'Create new folder'
=> '',

'Sent To'
=> '',

'Subject'
=> '',

'Date'
=> '',

'Sender'
=> '',

'Mailbox'
=> '',

'Conversations'
=> '',

'Search ...'
=> '',

'Inbox'
=> '',

'Sent'
=> '',

'Conversations View'
=> '',

'Go'
=> '',

'Network Activity Feed'
=> '',

'Welcome to %s!'
=> '',

'With your %s account you will be able to:'
=> '',

'Edit, share and store all your digital stuff in one place.'
=> '',

'Manage all your friends, groups and content.'
=> '',

'Unite your online life by connecting all your presences together.'
=> '',

'Provide the following information to join and start connecting all your '
.'digital worlds!'
=> '',

'Login name'
=> '',

'Login name may contain letters, numbers and underscores (_).'
=> '',

'Password'
=> '',

'Password can be 5-15 characters long, and is case sensitive.'
=> '',

'Confirm password'
=> '',

'Email'
=> '',

'Your photo'
=> '',

'To use a different image, click Browse or enter a URL below.'
=> '',

'Upload a photo'
=> '',

'Or enter a photo URL'
=> '',

'Preview image'
=> '',

'I have read and agree to the %s <a href=\'%s/terms.php\' target=\'_blank\'>Terms '
.'and Conditions</a>'
=> '',

'Manage users registered on your network'
=> '',

'Search Registered Users'
=> '',

'Registered'
=> '',

'User Name'
=> '',

'Action'
=> '',

'Approve'
=> '',

'Are you sure you want to delete this user?'
=> '',

'pending'
=> '',

'Assign Role'
=> '',

'Selected'
=> '',

'Are you sure?'
=> '',

'(un)check all'
=> '',

'No users'
=> '',

'No networks found'
=> '',

'Requests'
=> '',

'Approve or deny requests to join this group'
=> '',

'You haven\'t <a href="%s">created</a> or <a href="%s">joined</a> any '
.'groups yet.'
=> '',

'User has not joined any groups yet.'
=> '',

'Please, select your administration task'
=> '',

'Network Address'
=> '',

'Network address will be part of the URL of your network, e.g. <code>http://'
.'<b>abc</b>.%s/</code>. It should be less than 10 characters.'
=> '',

'Check Availability'
=> '',

'Network Title/Heading'
=> '',

'Title appears on network pages.  For best results, keep below 60 characters '
.'(max 100 characters).'
=> '',

'Network Sub Title'
=> '',

'The sub-title will be displayed below the Network Title.'
=> '',

'Network Category'
=> '',

'This category is used to organise the Network Directory.'
=> '',

'Network Description'
=> '',

'A short paragraph or two describing your network.'
=> '',

'Community Blog Title'
=> '',

'The Network group title will be displayed on the homepage.'
=> '',

'Network Icon'
=> '',

'The icon will appear in the network listing.'
=> '',

'Current Icon'
=> '',

'Ideal size 70 x 60 pixels'
=> '',

'Check if content moderation is required.'
=> '',

'Check if People page should only show users with a profile photo.'
=> '',

'Check if top menu bar is not required.'
=> '',

'Check if reciprocated relationships are required.'
=> '',

'Check if email address validation is required.'
=> '',

'Check if CAPTCHA is required during registration.'
=> '',

'Reciprocated relationships are required.'
=> '',

'Reciprocated relationships are not required.'
=> '',

'Email address validation is required.'
=> '',

'Email address validation is not required.'
=> '',

'CAPTCHA is required during registration.'
=> '',

'CAPTCHA is not required during registration.'
=> '',

'Friend'
=> '',

'%s supports several ID systems.'
=> '',

'%s login.'
=> '',

'OpenID'
=> '',

'Flickr ID'
=> '',

'Vista CardSpace'
=> '',

'Remember me on this computer'
=> '',

'Forgot your password?'
=> '',

'Nothing has been tagged yet.'
=> '',

'Invitation Status'
=> '',

'Accepted invitations'
=> '',

'No Accepted Invitations'
=> '',

'Pending invitations'
=> '',

'No pending Invitations'
=> '',

'Terms and Conditions - %s'
=> '',

'Status of selected user(s) updated successfully'
=> '',

'An error has occured on deleting users.'
=> '',

'%s - Private Messages - %s'
=> '',

'Successfully updated'
=> '',

'Newest People'
=> '',

'People - %s'
=> '',

'Friends'
=> '',

'%s\'s Gallery'
=> '',

'%s\'s Networks'
=> '',

'%s\'s Links'
=> '',

'%s\'s Groups'
=> '',

'%s\'s Comments'
=> '',

'%s\'s Blog'
=> '',

'%s %s - %s'
=> '',

'Network spawning disabled.'
=> '',

'Create Network - %s'
=> '',

'User Public Page'
=> '',

'Group Page'
=> '',

'Cannot create networks: this installation is not configured for network '
.'operation.'
=> '',

'Cannot create networks: %s is not writable'
=> '',

'Cannot create networks: Network spawning has been disabled on this '
.'installation.'
=> '',

'Files with extension \'%s\' may not be uploaded'
=> '',

'Unable to determine image type'
=> '',

'File MIME type is %s, expected %s'
=> '',

'Latest posts from %s'
=> '',

'Newest posts from everyone on %s'
=> '',

'%s: %s blog'
=> '',

'Failed to retrieve %s: %s'
=> '',

'Settings'
=> '',

'Network settings'
=> '',

'Ad center'
=> '',

'Manage ad center'
=> '',

'Textpads'
=> '',

'Meta network'
=> '',

'Set featured network'
=> '',

'Manage emblems'
=> '',

'Manage splash'
=> '',

'Showcased networks'
=> '',

'Network of Moment'
=> '',

'Video Tours'
=> '',

'Server Announcement'
=> '',

'Register Today'
=> '',

'Take a Tour Video'
=> '',

'MIS Reports'
=> '',

'Usage'
=> '',

'Counts'
=> '',

'Marketing reports'
=> '',

'Manage Ranking points'
=> '',

'Theme selector'
=> '',

'Module selector'
=> '',

'Background image'
=> '',

'Header image'
=> '',

'Customize theme'
=> '',

'User defaults'
=> '',

'Default settings'
=> '',

'Relationship settings'
=> '',

'Users Settings'
=> '',

'Create users'
=> '',

'Manage users'
=> '',

'Moderate users'
=> '',

'Moderate contents'
=> '',

'Manage contents'
=> '',

'Manage forums'
=> '',

'Manage comments'
=> '',

'Manage links'
=> '',

'Network links'
=> '',

'Manage Profanity'
=> '',

'Profane Word List'
=> '',

'Manage Signup Access'
=> '',

'Manage Domain Names'
=> '',

'Manage Events'
=> '',

'Network Events'
=> '',

'Manage Questions'
=> '',

'Manage Groups'
=> '',

'Manage Category'
=> '',

'Notifications'
=> '',

'Email notifications'
=> '',

'Roles'
=> '',

'Manage Roles'
=> '',

'Manage Tasks Relationship'
=> '',

'Celebrity'
=> '',

'Manage Celebrity'
=> '',

'Create Celebrity'
=> '',

'Poll'
=> '',

'Select Poll'
=> '',

'Create Poll'
=> '',

'Static Pages'
=> '',

'Manage Footer Links'
=> '',

'Manage Static Pages'
=> '',

'Delete as '
=> '',

'This section is disabled. Click the checkbox above to show it in your '
.'sidebar widget.'
=> '',

'Design your sidebar widget'
=> '',

'Rename this widget'
=> '',

'Rename'
=> '',

'Or'
=> '',

'Delete this widget'
=> '',

'Preview'
=> '',

'Sorry! you are not authorized to view the content of this page.'
=> '',

'Network URL cannot be left empty for showcased network '
=> '',

' For showcased network '
=> '',

'No caption given to network of moment'
=> '',

'Please provide URL for network of moment'
=> '',

'No video URL provided for video tours'
=> '',

'No description provided for network of moment'
=> '',

' For network of moment, '
=> '',

'Show Splash Page'
=> '',

'If this checkbox is checked then Splash Page will be the first page to be '
.'shown to the anonymous users otherwise Homepage will be the first page'
=> '',

'Current Image'
=> '',

'No image selected.'
=> '',

'Upload Image'
=> '',

'Uploaded image will be displayed at 185 pixels by 110 pixels.'
=> '',

'Save Announcement'
=> '',

'Uploaded image will be displayed at 193 pixels by 67 pixels.'
=> '',

'Showcased Network '
=> '',

'Showcased Network URL'
=> '',

'Paste the complete URL of the network here'
=> '',

'Showcased Network Image'
=> '',

'Caption'
=> '',

'Uploaded images will be displayed at 145 pixels by 145 pixels.'
=> '',

'Set Showcased Networks'
=> '',

'Video URL'
=> '',

'Video Tours Image'
=> '',

'Save Video Tour'
=> '',

'Network URL'
=> '',

'Network of the Moment Image'
=> '',

'Uploaded image will be displayed at 193 pixels by 67 pixels'
=> '',

'Save Network of the Moment'
=> '',

'In this page you can moderate users registered on your network'
=> '',

'Picture'
=> '',

'Name'
=> '',

'No User.'
=> '',

'Enable Modules'
=> '',

'Latest video of %s'
=> '',

'No Video uploaded yet.'
=> '',

'Full view'
=> '',

'Tags'
=> '',

'Apply Changes'
=> '',

'Return to group gallery'
=> '',

'Access'
=> '',

'in which your'
=> '',

'file will appear...'
=> '',

'Create New Album'
=> '',

'Return to media gallery'
=> '',

'No Forum Activity.'
=> '',

'Your page created sucessfull. Page data'
=> '',

'Click here for preview'
=> '',

'This module should be used for testing a new PA feature - generating page '
.'"in fly" or'
=> '',

'Dynamic page generation. This module also demonstrate handling actions '
.'inside a module'
=> '',

'instead by a script placed in the WEB root path. And, another module has '
.'been customized'
=> '',

'(AddGroupModule) to demonstrate that. Click here to see that example'
=> '',

'NOTE: Many of the existing modules could be used without any changes, but '
.'all modules which'
=> '',

'has been initialized from the WEB-root script should be adapted and '
.'initialization and action'
=> '',

'handling code should be moved inside a module. For more details, please take '
.'a look on the following source'
=> '',

'Page ID'
=> '',

'If you want to create a new page, enter here an unique Page ID number.'
=> '',

'For dynamic pages, this ID number should start from 200.'
=> '',

'Page Title'
=> '',

'Enter Page name'
=> '',

'Page Type'
=> '',

'Public Page'
=> '',

'Private Page'
=> '',

'Select Page type'
=> '',

'Required user or administration permissions for access to this page'
=> '',

'Enter required administration permissions. This permissions available'
=> '',

'Page Theme'
=> '',

'Enter Page theme (Beta)'
=> '',

'Page Outer Template'
=> '',

'Enter Page Outer Template (container_three_column.tpl, container_two_column.'
.'tpl ...)'
=> '',

'Header Template'
=> '',

'Enter Page Header Template (header.tpl, header_group.tpl ...)'
=> '',

'Page boot (pre-execute) PHP code'
=> '',

'NOTE: Code in the box above is only for example. If your page does not '
.'require boot code, delete it!'
=> '',

'Left modules'
=> '',

'Enter Left modules separated by commas'
=> '',

'Middle modules'
=> '',

'Enter Middle modules separated by commas'
=> '',

'Right modules'
=> '',

'Enter Right modules separated by commas'
=> '',

'Page JavaScript files'
=> '',

'Enter page Javascript file names separated by commas'
=> '',

'Page CSS files'
=> '',

'Enter page CSS file names separated by commas'
=> '',

'Page navigation links PHP code'
=> '',

'Enter code required for generating page navigation links. Here should be '
.'moved code from function'
=> '',

'declared in'
=> '',

'class (web/includes/classes/Navigation.php)'
=> '',

'inside'
=> '',

'statement'
=> '',

'Please see an example below. In this example we will use code written for '
.'generating navigation links on'
=> '',

'page'
=> '',

'So, this PHP code block should be copied and pasted in a text field above. '
.'If old'
=> '',

'page will not be used anymore, this code block should be removed from '
.'Navigation class'
=> '',

'See'
=> '',

'line'
=> '',

'NOTE: Code in the box above is only for example. You must delete it or enter '
.'your menu- navigation code here!'
=> '',

'Page body attributes'
=> '',

'Enter page body CSS attribute. For example'
=> '',

'Save generated page'
=> '',

'Select if you want to save generated Page'
=> '',

'Submit'
=> '',

'Upload'
=> '',

'Are you sure you want to delete this image'
=> '',

'No Photos.'
=> '',

'Tag Search'
=> '',

'Theme Selector'
=> '',

'Module Selector'
=> '',

'Desktop image'
=> '',

'Customize Theme'
=> '',

'Use these settings to customize the look of your '
=> '',

'Upload desktop image'
=> '',

'Image will appear on your public page'
=> '',

'Set image appearance'
=> '',

'Images 1016 pixels wide by 191 pixels tall will give the best results'
=> '',

'Use desktop image?'
=> '',

'Select '
=> '',

'Restore Default Image'
=> '',

'Check / Uncheck all modules'
=> '',

'In this page you can manage category on your network'
=> '',

'Select Type'
=> '',

'Parent'
=> '',

'Options'
=> '',

'Are you sure you want to delete this category?'
=> '',

'Create New Category'
=> '',

'Parent Category (Optional)'
=> '',

'Enter Tilte'
=> '',

'You can upload an audio file'
=> '',

'Maximum size'
=> '',

'Select a file to upload, or enter a URL below'
=> '',

'Audio URL'
=> '',

'Audio title'
=> '',

'Tags (separate with commas)'
=> '',

'Select who can listen this Audio'
=> '',

'Add More'
=> '',

'Or finish below'
=> '',

'Send to album'
=> '',

'Or create new album'
=> '',

'Upload audio'
=> '',

'You can upload a video file'
=> '',

'Select a file to upload'
=> '',

'Video title'
=> '',

'Upload video'
=> '',

'Back'
=> '',

'You can upload a gif, jpg, jpeg, png, xpm or bmp file'
=> '',

'Do not upload photos containing cartoons, celebrities, nudity, artwork or '
.'copyrighted images'
=> '',

'Image title'
=> '',

'Upload image'
=> '',

'Select who can see this image'
=> '',

'Image URL'
=> '',

'Are you sure you want to delete this comment'
=> '',

'No comment yet.'
=> '',

'Login to comment'
=> '',

'Comments on %s'
=> '',

'Please enter your email address or login name.'
=> '',

'Please enter either email or Login name'
=> '',

'There are no accounts in our system with the e-mail address %s.\n'
.'              If you have spelled the address incorrectly or entered the '
.'wrong address, please try again.'
=> '',

'Image will appear on your Networks Pages'
=> '',

'Stretch to fit'
=> '',

'Crop'
=> '',

'Tile'
=> '',

'Leave it alone'
=> '',

'Images 1016 pixels wide by 191 pixels tall will have the best results'
=> '',

'Here to set the Desktop image is display turn on or off.'
=> '',

'Apply desktop image'
=> '',

'Restore Default'
=> '',

'Configure Group Homepage'
=> '',

'Available Modules'
=> '',

'Show in Left or Right'
=> '',

'Stacking Order'
=> '',

'Left'
=> '',

'Right'
=> '',

'Previously Selected photo'
=> '',

'Image description'
=> '',

'Previously Selected Video'
=> '',

'Video description'
=> '',

'Manage Domain List'
=> '',

'Please press enter after each entry'
=> '',

'In this page you can manage Ads on a celebrity page.'
=> '',

'Place Holder'
=> '',

'Target url'
=> '',

'Add new celebrity ad'
=> '',

'Select ad place holder'
=> '',

'Upload Picture'
=> '',

'Ad target url'
=> '',

'Group Name'
=> '',

'Group Type'
=> '',

'Select Group Type'
=> '',

'Select Super Group Features'
=> '',

'Group Category'
=> '',

'separated tags with commas'
=> '',

'Group Photo'
=> '',

'Choose File'
=> '',

'Current Photo'
=> '',

'Group Description'
=> '',

'Registration Type'
=> '',

'Open'
=> '',

'Moderated'
=> '',

'Invite Only'
=> '',

'Edit Static Page'
=> '',

'Create Static Page'
=> '',

'URL'
=> '',

'Page Text'
=> '',

'Are you sure you want to delete this page?'
=> '',

'In this page you can manage static pages.'
=> '',

'Create New Static Page'
=> '',

'Enter Caption'
=> '',

'Caption should be less than 30 characters.'
=> '',

'Enter Page Text'
=> '',

'Thumbnail'
=> '',

'Title/Description/Date/Tags'
=> '',

'Album/Playlist'
=> '',

'No Videos'
=> '',

'No Video'
=> '',

'You can upload a gif, jpg, jpeg, png, xpm, bmp, file.'
=> '',

'Do not upload photos containing cartoons, celebrities, nudity, artwork of '
.'copyrighted images.'
=> '',

'For better result image dimension  should be 36x191'
=> '',

'Enter the destination URL of image'
=> '',

'No Fan listed yet.'
=> '',

'Become Fan'
=> '',

'Remove Fan'
=> '',

'View All'
=> '',

'Fans'
=> '',

'Fan has been added successfully'
=> '',

'Removed from fan list successfully'
=> '',

'caption'
=> '',

'Group doesn\'t exist'
=> '',

'Manage TakeATour'
=> '',

'In this page you can manage celebrities on your network'
=> '',

'Search Celebrities'
=> '',

'Second Picture'
=> '',

'Author'
=> '',

'Links'
=> '',

'Delete selected'
=> '',

'create your post'
=> '',

'select where you want it to go'
=> '',

'You can route this post to one or many destinations with the selectors '
.'below. You can even publish it to blogs outside of the PeopleAggregator '
.'network by configuring an'
=> '',

'account in your'
=> '',

'settings'
=> '',

'Please note that routing does not post to private groups'
=> '',

'Routing'
=> '',

'Send to selected group blogs'
=> '',

'Send to selected external blogs'
=> '',

'Select albums in your media gallery to send to'
=> '',

'Select none of my galleries'
=> '',

'Select all of my galleries'
=> '',

'No Albums'
=> '',

'Or, create a new album in your media gallery'
=> '',

'publish post'
=> '',

'The publish post button will send you creation to all the destination you '
.'have selected above. You can always edit this post or send it other places '
.'later by selecting Manage Posts, found on the Blog module on'
=> '',

'Your Page.'
=> '',

'Cancel'
=> '',

'Create Blog'
=> '',

'Separate tags with commas'
=> '',

'Send'
=> '',

'Message composed will be discarded. Do you want to continue?'
=> '',

'To'
=> '',

'select friend'
=> '',

'Message'
=> '',

'Check Mail'
=> '',

'Compose'
=> '',

'Message sent successfully to %s'
=> '',

'Message sending failed for %s  as user(s) doesn\'t exist'
=> '',

'Polls'
=> '',

'No previous poll to display'
=> '',

'No votes are posted for this poll'
=> '',

'Use this tool to send announcements to all registered network members'
=> '',

'Message/post'
=> '',

'Destination'
=> '',

'Deliver message to all registered members by internal mail'
=> '',

'Email message to all network members'
=> '',

'Post message to network home page community blog'
=> '',

'Send to me only'
=> '',

'No Group added yet.'
=> '',

'Manage Network Content'
=> '',

'Search Posts'
=> '',

'Browse Months'
=> '',

'In this page you can'
=> '',

'celebrity on your network'
=> '',

'celebrity'
=> '',

'Enter the Description'
=> '',

'Enter the Official site'
=> '',

'Upload celebrity photo'
=> '',

'Previously Selected another photo'
=> '',

'Upload celebrity another photo'
=> '',

'Edit '
=> '',

'Create a '
=> '',

'Forum Topic'
=> '',

'Manage content on your network.'
=> '',

'Search posts'
=> '',

'Browse months'
=> '',

'When'
=> '',

'Type'
=> '',

'Comments'
=> '',

'Abuses'
=> '',

'Are you sure you want to delete this content?'
=> '',

'No Content.'
=> '',

'Personal and professional info'
=> '',

'show everything'
=> '',

'show what your friends see'
=> '',

'show only public info'
=> '',

'Sidebar preview of your hCard/XFN profile'
=> '',

'ID Hub (WORK IN PROGRESS)'
=> '',

'Manage'
=> '',

'You have 3 blog options'
=> '',

'You also can have a personal blog. A personal blog shows up on your page '
.'with posts routed to the community blog by default. You can opt for those to '
.'only be on your personal blog'
=> '',

'If you already have a blog, you can display your External Blog on My Page'
=> '',

'Basic Info'
=> '',

'General Info'
=> '',

'Personal Info'
=> '',

'Professional Info'
=> '',

'Blogs/RSS'
=> '',

'External Accounts'
=> '',

'ID Hub'
=> '',

'Export'
=> '',

'Import'
=> '',

'Delete Account'
=> '',

'Sorry: you are unable to save data'
=> '',

'Reason: '
=> '',

'Select for All'
=> '',

'Upload CV'
=> '',

'Valid file types are .doc and .pdf'
=> '',

'This will replace your current CV'
=> '',

'Career Skills'
=> '',

'Prior Title'
=> '',

'College Name'
=> '',

'Summary'
=> '',

'Your full Professional biography here. Please note there is a 2,500 '
.'character limit.'
=> '',

'Languages'
=> '',

'Honors &amp; Awards'
=> '',

'Please modify the hCard/XFN preview below to suit your taste.'
=> '',

'Once you have selected what you want to display, click \'create hCard\', then '
.'copy the generated HTML to your blog or wherever you want to use it.'
=> '',

'Sorry: you are unable to save data.'
=> '',

' Reason: '
=> '',

'Political View'
=> '',

'TV Shows'
=> '',

'Fields marked with * can not be empty, First name can not be empty.'
=> '',

'Fields marked with * can not be empty, Email field is mandatory.'
=> '',

'Zipcode must be in numeric characters.'
=> '',

'Slogen must be less then 20 characters .'
=> '',

' Sub-Slogen must be then 30 characters .'
=> '',

' Confirm Password can\'t leave blank .'
=> '',

'Passwords do not match.'
=> '',

'The password must be less than 15 characters.'
=> '',

'The password must be greater than 5 characters.'
=> '',

'Basic info'
=> '',

'Confirm Password'
=> '',

'First Name'
=> '',

'Last Name'
=> '',

'Upload Photo'
=> '',

'I want to receive  notifications when'
=> '',

'via my registered email'
=> '',

'via my account inbox'
=> '',

'Notify \'messages waiting\''
=> '',

'through my registered mail'
=> '',

'\'messages waiting\' notifications in my mail box, when new messages arrive'
=> '',

'The Date of Birth is invalid.'
=> '',

'Url is invalid'
=> '',

'Slogan'
=> '',

'Slogan will appear on your Public Page.'
=> '',

'Shout Out'
=> '',

'Shout out will appear on your Public Page.'
=> '',

'Date of Birth'
=> '',

'State/Province'
=> '',

'Other state'
=> '',

'Zip/Postal Code'
=> '',

'Outputthis username'
=> '',

'Outputthis password'
=> '',

'Seperate tags with commas.'
=> '',

'Add another Blog'
=> '',

'Permission to view your Blog'
=> '',

'Blog Title'
=> '',

'Blog URL'
=> '',

'Blog Feed URL'
=> '',

'If you delete your account, all your content posted and your membership in '
.'other networks will be deleted. Your complete information will be deleted '
.'from the network.'
=> '',

'To delete your account you have to enter your password.'
=> '',

'Delete My Account'
=> '',

'There are'
=> '',

'No group Found.'
=> '',

'Write Testimonial for '
=> '',

'Testimonial'
=> '',

'Reviews'
=> '',

'No Content Published.'
=> '',

'On this page you can manage all posts you have created.'
=> '',

'No Content Published'
=> '',

'This is the echo test module.'
=> '',

'>Update:'
=> '',

'Edit Link'
=> '',

'Create A Link'
=> '',

'Are you sure you want to delete this link?'
=> '',

'In this page you can manage footer links.'
=> '',

'Create New Footer Link'
=> '',

'Check this, if you want to open link in a different window'
=> '',

'Manage ads'
=> '',

'Add ads'
=> '',

'Manage Headlines'
=> '',

'Manage headlines'
=> '',

'Manage Top Songs'
=> '',

'Manage Songs'
=> '',

'Manage Top Albums'
=> '',

'Manage Album'
=> '',

'Admin configuration module'
=> '',

'Specify how close you are in your relationship with'
=> '',

'Check if'
=> '',

'is'
=> '',

'in family'
=> '',

'Create New List'
=> '',

'List Caption'
=> '',

'Current CSV File'
=> '',

'Contacts File (.csv file)'
=> '',

'Mailing Lists'
=> '',

'Sr No.'
=> '',

'Actions'
=> '',

'Send Message To List'
=> '',

'Select List(s)'
=> '',

'Current no mailing list have been added.'
=> '',

'Click'
=> '',

'here'
=> '',

'to add.'
=> '',

'Playlist Caption'
=> '',

'Enter url of playlist(.xspf) file'
=> '',

'Upload playlist(.xspf) file'
=> '',

'Playlists'
=> '',

'No playlist added yet.'
=> '',

'Ecommerce Widget Caption'
=> '',

'Widget Script'
=> '',

'Widget Caption'
=> '',

'Are you sure you want to delete this video'
=> '',

'Latest Headlines'
=> '',

'No headline is added yet'
=> '',

'Top songs'
=> '',

'No song is added yet'
=> '',

'Top albums'
=> '',

'No album is added yet'
=> '',

'Manage Profanity List'
=> '',

'Background Image'
=> '',

'that others will see.'
=> '',

'Edit question'
=> '',

'Create new question'
=> '',

'select'
=> '',

'Question'
=> '',

'Are you sure you want to delete this?'
=> '',

'In this page you can manage questions for your network\'s users'
=> '',

'Set Active Question'
=> '',

'\'s Answers'
=> '',

'No answer is posted till now'
=> '',

'Submit your answer'
=> '',

'Answers'
=> '',

'Submit Answers'
=> '',

'Display as'
=> '',

'No Testimonial Found'
=> '',

'testimonials'
=> '',

'New Testimonials'
=> '',

'Album'
=> '',

'Select Album'
=> '',

'No Audio'
=> '',

'Announcements'
=> '',

'Post reply for '
=> '',

'Post Reply'
=> '',

'Start a new topic in '
=> '',

'Post New Topic'
=> '',

'No active forum topics found'
=> '',

'Message forum'
=> '',

'Please specify title for your comments.'
=> '',

'Please enter your comments.'
=> '',

'Error occured in saving thread'
=> '',

'You are not a member of this group.'
=> '',

'Leave This Group'
=> '',

'Request to join this group'
=> '',

'Join This Group'
=> '',

'Celebrity Stats'
=> '',

'There are '
=> '',

' members '
=> '',

'Deny'
=> '',

' members in group '
=> '',

' friends for '
=> '',

'member since:'
=> '',

'No relation exists'
=> '',

'No image uploaded yet.'
=> '',

'Select a group to invite into'
=> '',

'Enter Your friend\'s login name(in People Aggregator) or email address'
=> '',

'Write here personalized message for invitees. It will be appended to email'
=> '',

'Write your invitation Message'
=> '',

'Invite Into Groups'
=> '',

'Please select a group'
=> '',

'Invitation could not be sent to following login names- %s'
=> '',

'Invitation could not be sent to following email addresses- %s'
=> '',

'Invitation from %s %s to join %s'
=> '',

'Sorry: you are unable to invite a friend.  Reason: %s'
=> '',

'Loading ...'
=> '',

'In this page you can view stats about system usage'
=> '',

'Registered Users'
=> '',

'Number of blog post'
=> '',

'Number of Images'
=> '',

'Profile Views'
=> '',

'Maximum'
=> '',

'Minimum'
=> '',

'Average'
=> '',

'Profile Visited by User'
=> '',

'Relations Statistics'
=> '',

'Number of Users by Email Domain:'
=> '',

'Domain Name'
=> '',

'Number of Users'
=> '',

'In this page you can view Email Addresses of all users'
=> '',

'All Users'
=> '',

'Most Active Users'
=> '',

'Dormant Users'
=> '',

'User'
=> '',

'Email Addresses'
=> '',

'Total Points'
=> '',

'Vote'
=> '',

'Manage your link lists'
=> '',

'Create new'
=> '',

'Edit selected list'
=> '',

'Delete selected list'
=> '',

'Create a list'
=> '',

'New List Name'
=> '',

'Links under the selected list will be shown here'
=> '',

'Create link'
=> '',

'Link caption'
=> '',

'In this page you can manage different admin roles'
=> '',

'Sr.No.'
=> '',

'No roles have been created yet.'
=> '',

'Add New Role'
=> '',

'No Groups found.'
=> '',

'to create.'
=> '',

'In this page you can manage headlines on a celebrity page.'
=> '',

'Associated Url'
=> '',

'No Headlines added yet'
=> '',

'Add new celebrity Headlines'
=> '',

'Enter the Headline'
=> '',

'In this page you can manage Top Album on a celebrity page.'
=> '',

'Add new celebrity Album'
=> '',

'Album Description'
=> '',

'Album url'
=> '',

'In this page you can manage Top songs on a celebrity page.'
=> '',

'Add new Song'
=> '',

'No Song added yet'
=> '',

'Add new celebrity Song'
=> '',

'Song Description'
=> '',

'Song url'
=> '',

'Select An email type'
=> '',

'Select an email type'
=> '',

'Available configurable variables'
=> '',

'Personal Activity Feed'
=> '',

'Activity Feed'
=> '',

'Group Activity Feed'
=> '',

'Join now'
=> '',

'In this page you can assign roles to tasks'
=> '',

'No roles have been created yet'
=> '',

'On this page you can manage all posts which of the Group.'
=> '',

'On this page you can manage all the forums of the Group.'
=> '',

'Create Forum'
=> '',

'Welcome'
=> '',

'Enter your new password'
=> '',

'Re-enter the new password'
=> '',

'Manage forums on your network.'
=> '',

'No Forums.'
=> '',

'Poll Topic'
=> '',

'Number Of Options'
=> '',

'No poll is created yet.'
=> '',

'Moderate content on your network.'
=> '',

'No Content For Moderation.'
=> '',

'No Link Categories'
=> '',

'Link Name'
=> '',

'Link'
=> '',

'Terms and conditions for using'
=> '',

'No Comments Found'
=> '',

'Configure Network'
=> '',

'Configure Basic Information'
=> '',

'Configure Email Notifications'
=> '',

'Configure User defaults'
=> '',

'Send Announcements'
=> '',

'Configure Relationships'
=> '',

'New User Account Defaults'
=> '',

'Network friends'
=> '',

'I appear as a friend in all new accounts'
=> '',

'These users appear as friends in all new accounts.'
=> '',

'(enter screen names of registered network users, separated by commas)'
=> '',

'Desktop Image'
=> '',

'Current default desktop image'
=> '',

'(Images 1016 pixels wide by 191 pixels tall will have the best results)'
=> '',

'Upload default desktop image'
=> '',

'Set desktop image turn on/off'
=> '',

'Turn on'
=> '',

'Turn off'
=> '',

'Media Gallery Images'
=> '',

'Select an image album(s) from your gallery to include in new user default '
.'galleries. (An album in your gallery may contain one or more images.)'
=> '',

'Upload to gallery now'
=> '',

'For multiple selections hold down the &lt;Ctrl&gt;key PC or the &lt;'
.'Command&gt; key(Mac) while clicking the desired selections.'
=> '',

'Media Gallery Audio'
=> '',

'Select an audio album(s) from your gallery to include in new user default '
.'galleries. (An album in your gallery may contain one or more audio clips.)'
=> '',

'Media Gallery Video'
=> '',

'Default Blog'
=> '',

'Select a post to include in new user default.'
=> '',

'Manage link lists'
=> '',

'Select category'
=> '',

'Search Engines'
=> '',

'Ect...'
=> '',

'New List'
=> '',

'Edit List'
=> '',

'Delete List'
=> '',

'Add Link'
=> '',

'Delete Link'
=> '',

'Save Settings'
=> '',

'Email Notifications'
=> '',

'Notify network operator (me) when'
=> '',

'Registered members receive notifications when'
=> '',

'via their registered email'
=> '',

'via their account inbox'
=> '',

'Blink Messages Waiting:'
=> '',

'messages  waiting blinks in network member\'s toolbar when new messages arrive'
=> '',

'Save changes'
=> '',

'In this page you can manage users registered on your network'
=> '',

'Manage comments.'
=> '',

'No Comments'
=> '',

'Looks like your authentication with Flickr has timed out. Let\'s try again.'
=> '',

'We haven\'t seen you before, have we?'
=> '',

'Would you like to register this persona with the PeopleAggregator, so that '
.'you can login in the future?'
=> '',

'Click here to log in via Flickr.'
=> '',

'start here!'
=> '',

'Please login to Flickr via the new brower window that should have come up. '
.'If it has not, you can'
=> '',

'click here to open it.'
=> '',

'Once you have logged in to Flickr, please reload this page by'
=> '',

'clicking here to finish the registration process.'
=> '',

'You also returned'
=> '',

'as your nick.'
=> '',

'as your email.'
=> '',

'It seems you are coming from an OpenID auth server, but there is something '
.'wrong with your session. Please'
=> '',

'try again'
=> '',

'Welcome to PeopleAggregator'
=> '',

'This is a private network'
=> '',

'You need to be member of this network to do anything. You can send a request '
.'to join this network by clicking \'Request to join\'.'
=> '',

'Provide a login name, email address and basic information for a new network '
.'member.'
=> '',

'Upon hitting the create button, the new member will be emailed a greeting '
.'including an auto-generated password.'
=> '',

'Fields marked with an asterisk (*) are mandatory.'
=> '',

'Email address'
=> '',

'Photo/avatar'
=> '',

'Auto-generate new password for network member'
=> '',

'Manual password'
=> '',

'modify greeting if desired and click the create user button below tocomplete '
.'process'
=> '',

'Hi,'
=> '',

'I\'ve created my own place on PeopleAggregator and I\'d like you to'
=> '',

'connect to me so we can stay in touch.'
=> '',

'You can view my blog, my reviews, my ratings, my photos, my lists -'
=> '',

'and all sorts of things that matter to me.'
=> '',

'You can create a personal page and blog of your own, which will be'
=> '',

'linked to mine.'
=> '',

'That way you\'ll always know when I post something new!'
=> '',

'topics in this Group'
=> '',

'Create Topic'
=> '',

'Topics'
=> '',

'Replies'
=> '',

'Write Comment for '
=> '',

'Moderate Users'
=> '',

'Replace these fields in your PeopleAggregator profile'
=> '',

'Please be careful: the fields you select to import in this section will '
.'overwrite the info you had in those fields in your PeopleAggregator profile.'
=> '',

'Create new fields in your PeopleAggregator profile'
=> '',

'The fields you select below will be added to your PeopleAggregator profile.'
=> '',

'Recent Forum Activity'
=> '',

'Create Dynamic Page'
=> '',

'Networks'
=> '',

'Use these settings to customize the look of your "Me" page and the look of '
.'your public blog page<br>that others will see.'
=> '',

'Current Desktop Image'
=> '',

'Images 1016 pixels wide by 191 pixels tall will give the best results.'
=> '',

'Select "yes" to turn on or "no" to turn off your custom desktop image.'
=> '',

'Comment can not be empty'
=> '',

'Comment saved successfully'
=> '',

'Login required'
=> '',

'No header'
=> '',

'Blogs'
=> '',

'Change Group Settings'
=> '',

'Change Super Group Settings'
=> '',

'File upload error: '
=> '',

'Member Deleted'
=> '',

'Add Blog Post'
=> '',

'Default Image Album'
=> '',

'Default Audio Album'
=> '',

'Default Video Album'
=> '',

'Manage Network Bulletins'
=> '',

'Network Operator Controls'
=> '',

'Create A New Forum Topic'
=> '',

'Please specify a title for the forum topic'
=> '',

'Error occured in saving data'
=> '',

'Manage Content'
=> '',

'Couldn\'t disconnect the Service.'
=> '',

'Manage Post'
=> '',

'Echo Test'
=> '',

'Please specify widget caption.'
=> '',

'Please specify widget script.'
=> '',

'Please select at least one mailing list.'
=> '',

'Please specify the subject for the message.'
=> '',

'Please specify the message to be send.'
=> '',

'Statistics for '
=> '',

'mailing list(s)'
=> '',

'Successfull'
=> '',

'Failed'
=> '',

'Please specify caption for the mailing list.'
=> '',

'Please upload a valid CSV file.'
=> '',

'Invalid caption given in CSV file. Valid captions are'
=> '',

'Invalid CSV file. Captions provided are not valid'
=> '',

'Please provide the CSV file.'
=> '',

'Please specify playlist caption.'
=> '',

'Please specify playlist url or upload a new playlist.'
=> '',

'Specified playlist file doesn not exists.'
=> '',

'Invalid playlist file.'
=> '',

'Super Group Settings'
=> '',

'Select Theme'
=> '',

'Upload Desktop Image'
=> '',

'Set Desktop image Turn on/off'
=> '',

'Current Background Image'
=> '',

'Upload Background Image'
=> '',

'Image as header background will appear on your Networks Pages'
=> '',

'Apply background image'
=> '',

'Site Ranking'
=> '',

' as a friend'
=> '',

'who'
=> '',

'Latest Photo of %s'
=> '',

'Links Control Panel'
=> '',

' is not a valid folder name.'
=> '',

'Folder creation failed. You already have a folder named '
=> '',

'1 message has been deleted successfully'
=> '',

' messages have been deleted successfully'
=> '',

'1 message has been moved to folder '
=> '',

' successfully'
=> '',

' messages have been moved to folder '
=> '',

'Selected message(s) are already in '
=> '',

' folder'
=> '',

'Please select message(s) to move'
=> '',

'Folder creation failed). '
=> '',

'Celebrity Headlines'
=> '',

'Statistics'
=> '',

'Assign Roles to Tasks'
=> '',

'Manage Groups Contents'
=> '',

'Change Password'
=> '',

'Please enter your new password'
=> '',

'Please confirm your new password'
=> '',

'Passwords do not match. Please re-enter'
=> '',

'The password must be less than 15 characters'
=> '',

'The password must be greater than 4 characters'
=> '',

'Manage Forums'
=> '',

'Manage Network Links'
=> '',

'Manage Comments'
=> '',

'Anonymous'
=> '',

'Could not create the FileStore directory'
=> '',

'Please check the effective permissions.'
=> '',

'Please enter the details you would like to use below.'
=> '',

'Username'
=> '',

'Register Persona'
=> '',

'You can\'t enable this ID, as another user'
=> '',

'has already done so.'
=> '',

'Sorry but the invitation ID you are using is no longer valid.'
=> '',

'Send request for joining network'
=> '',

'Request Message'
=> '',

'Message sent successfully to '
=> '',

'Please, select contacts you want to import.'
=> '',

'Apply to User pages'
=> '',

'Apply to this Network'
=> '',

'Apply to '
=> '',

' group'
=> '',

'Tasks/Permissions'
=> '',

'Select any %s file to upload'
=> '',

'You have to login before uploading a %s'
=> '',

'Edit/Assign Role for user: '
=> '',

'Select roles you want to associate with this user and press left/right '
.'arrow, <br />'
=> '',

'We haven\'t found any contacts on your MSLive account.'
=> '',

'Answer can not be left blank'
=> '',

'Sorry, your Answer cannot be posted as it looks like spam. Try removing any '
.'links to possibly suspect sites, and re-submitting.'
=> '',

'Your Answer has been posted successfully'
=> '',

'Sorry, your answer cannot be posted as it was classified as spam by Akismet, '
.'or contained links to blacklisted sites. Please check the links in your '
.'post, and that your name and e-mail address are correct.'
=> '',

'click to include'
=> '',

'Are you sure you wish to delete this widget?'
=> '',

'About Me'
=> '',

'About'
=> '',

'My Activity Feeds'
=> '',

'Activity Feeds'
=> '',

'Please select a type.'
=> '',

'TypedEntity associated successfully.'
=> '',

'Please upload a valid Game Image in %s'
=> '',

'Please supply a name.'
=> '',

'Entity Type'
=> '',

'Password should be of %s characters or more.'
=> '',

'Password should be less than %s charcaters.'
=> '',

'Store as Defaults'
=> '',

'Caution - software developers only'
=> '',

'Load / restore Email Message settings from local disk'
=> '',

'Select XML configuration file.'
=> '',

'Select action'
=> '',

'Load Email Message settings'
=> '',

'Revert All Messages'
=> '',

'Warning: you will lose all message changes made at this site.'
=> '',

'Select page'
=> '',

'Select page you want to customize.'
=> '',

'Get module info'
=> '',

'Add this module to: '
=> '',

'No'
=> '',

'Yes'
=> '',

'Page type'
=> '',

'Enter Page type (user, group, network). For multiple types use "|" to '
.'separate types.'
=> '',

'Is page configurable'
=> '',

'If a page is configurable - these settings will be available in Customize UI '
.'pages.'
=> '',

'Enter required administration permissions. Currently, these permissions are '
.'available'
=> '',

'Enter here code that should be executed on page boot before any module '
.'initialization function called. Use this only if you have a good reason for '
.'that and when you can\'t place that code inside a module - initializeModule() '
.'function. For example, if some modules need and share same data and you want '
.'to avoid executing same code multiple times. In that case, place here '
.'required code to evaluate those data and forward results to each module via '
.'$module_shared_data variable. For example'
=> '',

'NOTE: If your page does not require additional boot code, leave this '
.'untouched.'
=> '',

'Edit/Create Dynamic Page'
=> '',

'Middle'
=> '',

'Image will appear on your Personal Pages'
=> '',

'Image will appear on your Groups Pages'
=> '',

'Select page layout'
=> '',

'Select page layout template.'
=> '',

'Add a side module'
=> '',

'Select a side module to add it to your page, chose module placement column, '
.'then click "Save settings". '
=> '',

'Add a middle module'
=> '',

'Select a middle module to add it to your page, chose module placement '
.'column, then click "Save settings". '
=> '',

'Use these settings to customize the look of your Network pages'
=> '',

'Return to %s gallery'
=> '',

'Remove Picture'
=> '',

'Profile updated successfully.'
=> '',

'Import Contacts'
=> '',

'You are not allowed to delete your account here. You can delete your account '
.'from meta organization only.'
=> '',

'To delete your account you have to check this box.'
=> '',

'Password and confirm password should match.'
=> '',

'Address'
=> '',

'Address 2'
=> '',

'Phone'
=> '',

'Mobile Phone'
=> '',

'Restore default settings'
=> '',

'Work Phone'
=> '',

'User: '
=> '',

'Update Relationship Request'
=> '',

'ADD as a Friend'
=> '',

'Your request for adding '
=> '',

' as a relation has already been sent'
=> '',

'Edit Relationship'
=> '',

'Unknown event association'
=> '',

'Latest Forum Posts'
=> '',

'Forum Name'
=> '',

'Thread Title'
=> '',

'Last Post'
=> '',

'No posts'
=> '',

'Posts'
=> '',

'Status'
=> '',

'You will be able to answer this post after admin approve your membership '
.'request'
=> '',

'Banned User'
=> '',

'Administrator message'
=> '',

'label'
=> '',

'Edit post'
=> '',

'Edit thread'
=> '',

'Post title'
=> '',

'Thread title'
=> '',

'Post content'
=> '',

'Thread content'
=> '',

'Forum Last post'
=> '',

'Threads'
=> '',

'Category:'
=> '',

'Posted by'
=> '',

'no posts'
=> '',

'Pages: '
=> '',

'Thread'
=> '',

'You will be able to answer this topic after admin approve your membership '
.'request'
=> '',

'Are you sure you want to delete this topic?'
=> '',

'Thread Last post'
=> '',

'Viewed'
=> '',

'Forum:'
=> '',

'Are you sure you want to delete this forum?'
=> '',

'Created by'
=> '',

'Forums'
=> '',

'Forum Board for this network has not yet been created.'
=> '',

'Forum Board for this group have not yet been created.'
=> '',

'The personal forum board for this user have not yet been created.'
=> '',

'Post does not exists!'
=> '',

'Thread does not exists!'
=> '',

'New Thread'
=> '',

'You don\'t have permissions to create a new thread!'
=> '',

'Forum does not exists!'
=> '',

'Edit Forum'
=> '',

'New Forum'
=> '',

'Forum title'
=> '',

'Short description'
=> '',

'You don\'t have permissions to create a new forum!'
=> '',

'Category does not exists!'
=> '',

'Edit Category'
=> '',

'New Category'
=> '',

'Category title'
=> '',

'You don\'t have permissions to create a new category!'
=> '',

'network forum board'
=> '',

'group forum board'
=> '',

'personal forum board'
=> '',

'Forum Board description goes here'
=> '',

'Forum Board sucessfully saved'
=> '',

'You don\'t have permissions to create this Forum Board!'
=> '',

'Forum Settings'
=> '',

'Forum name'
=> '',

'Forum description'
=> '',

'Allow anonymous post'
=> '',

'Allow users to create Categories'
=> '',

'Allow users to create Forums'
=> '',

'Membership approval required'
=> '',

'Threads per page'
=> '',

'Posts per page'
=> '',

'Avatar size'
=> '',

'Edit mode'
=> '',

'Forum theme'
=> '',

'Banned users message'
=> '',

'Join requested message'
=> '',

'Join approved message'
=> '',

'You don\'t have permissions to edit Forum Board settings!'
=> '',

'You don\'t have required permissions for this task!'
=> '',

'Thread sucessfully removed'
=> '',

'Forum sucessfully deleted'
=> '',

'Category sucessfully deleted'
=> '',

'Post sucessfully deleted'
=> '',

'Thread not found!'
=> '',

'sticky'
=> '',

'locked'
=> '',

'Thread status sucessfully changed'
=> '',

'Anonymous user can\'t be banned'
=> '',

'You can\'t ban itself.'
=> '',

'Can\'t ban user - user not found!'
=> '',

'User status sucessfully changed.'
=> '',

'User is'
=> '',

'not'
=> '',

'banned now.'
=> '',

'Please, enter your name or email address'
=> '',

'Please, enter correct verification code'
=> '',

'Please, enter reply title'
=> '',

'Please, enter reply message text'
=> '',

'Reply post sucessfully saved'
=> '',

'Please, enter thread title'
=> '',

'Please, enter thread text'
=> '',

'Thread sucessfully created'
=> '',

'Please, enter forum title'
=> '',

'Please, enter forum description text'
=> '',

'Forum sucessfully created'
=> '',

'Forum data sucessfully updated'
=> '',

'Please, enter category title'
=> '',

'Please, enter category description text'
=> '',

'Category sucessfully created'
=> '',

'Category data sucessfully updated'
=> '',

'Please, enter numeric value into the "threads_per_page" field'
=> '',

'Please, enter numeric value into the "posts_per_page" field'
=> '',

'Settings data sucessfully updated'
=> '',

'Title field can\'t be empty'
=> '',

'Content field can\'t be empty'
=> '',

'Post sucessfully saved'
=> '',

'Thread sucessfully saved'
=> '',

'Reply to'
=> '',

'post'
=> '',

'thread'
=> '',

'Reply title'
=> '',

'Reply content'
=> '',

'User '
=> '',

'wrote'
=> '',

'Enter the verification code'
=> '',

'Code'
=> '',

'Your name or email'
=> '',

'Click here to create it'
=> '',

'Forums List'
=> '',

'type: '
=> '',

'board'
=> '',

'Forum Statistics'
=> '',

'Categories'
=> '',

'Founded'
=> '',

'You have updated your relation to "%s" successfully.'
=> '',

'You are already a member of "%s"'
=> '',

'Your request to join "%s" has been submitted to the owner of the group.'
=> '',

'You have joined "%s" successfully.'
=> '',

'You need to be logged in to join a group.'
=> '',

'You can\'t leave your own group.'
=> '',

'You are not member of "%s".'
=> '',

'You have left "%s" successfully.'
=> '',

'Group sucessfully deleted.'
=> '',

'Sorry you are not authorised to moderate this group'
=> '',

'Content Approved'
=> '',

'Content Denied'
=> '',

'Please select a content for approval'
=> '',

'Please select a content for denial'
=> '',

'User Approved'
=> '',

'User Denied'
=> '',

'Please select a user for approval'
=> '',

'Please select a user for denial'
=> '',

'Moderate %s Members'
=> '',

'Remove selected members from the %s'
=> '',

'Declare as Moderator'
=> '',

'Declare as Member'
=> '',

'Edit/Assign Role'
=> '',

'There are no members in this %s'
=> '',

'Member(s) Deleted'
=> '',

'Please select a member'
=> '',

'User status sucessfuly changed.'
=> '',

'Can\'t change status for this user.'
=> '',

'On this page you can manage all posts of the %s.'
=> '',

'Manage %s Contents'
=> '',

'Largest'
=> '',

'Group Statistics'
=> '',

'Category'
=> '',

'Owner'
=> '',

'Group Gallery'
=> '',

'Choose a program or service below to import your contacts:'
=> '',

'Your Plaxo ID'
=> '',

'(Enter your email or AIM screen name here)'
=> '',

'We will not store your password. It will only be temporarily used to access '
.'your Plaxo address book.'
=> '',

'Your WindowsLive ID'
=> '',

'(Enter your WindowsLive ID here)'
=> '',

'Your password'
=> '',

'We will not store your password. It will only be temporarily used to access '
.'your Windows Live address book.'
=> '',

'Select CSV file'
=> '',

'(Select CSV file you want to load)'
=> '',

' Login Name'
=> '',

'Following user names are not valid %s'
=> '',

'Following email addresses are not valid: %s'
=> '',

' Invalid Email addresses'
=> '',

'Sorry: you are unable to invite a friend. Reason: %s'
=> '',

'An Invitation has been sent to - %s'
=> '',

'Largest %s'
=> '',

'Leader Board'
=> '',

'No.'
=> '',

'Last Activity Date'
=> '',

'Ranking points'
=> '',

'Ranking stars'
=> '',

'unknown'
=> '',

'There\'s no ranked users.'
=> '',

'Sorry - you are not logged in or you have been logged out due to inactivity.'
.'<br />Please, log in again.<br />'
=> '',

'Login'
=> '',

'You can login directly if you have an account,<br />or you can <b><a href="/'
.'register.php">sign up right now</a></b> to create a new account.'
=> '',

'User name: '
=> '',

'Password: '
=> '',

'Id'
=> '',

'Points'
=> '',

'Edit activity types or add a new type below'
=> '',

'New'
=> '',

'\'Title\' and/or \'Type\' filed should not be empty.'
=> '',

'\'Points\' filed should be numeric and not empty.'
=> '',

'Media file has been deleted from album or gallery.'
=> '',

'Return to %s'
=> '',

'Return to %s\'s gallery'
=> '',

'%s\'s Page'
=> '',

'No such content or media file has been deleted from the gallery.'
=> '',

'%s Members'
=> '',

'find People'
=> '',

'Member Search'
=> '',

'Folder creation failed. '
=> '',

'Search Results'
=> '',

'You can\'t access other user\'s messages.'
=> '',

'Please create a folder to move message(s)'
=> '',

'User settable'
=> '',

'Update All Current Users'
=> '',

'Restore Defaults'
=> '',

'Load / restore User Account Defaults from local disk'
=> '',

'Load User Account Defaults'
=> '',

'Save Relationship'
=> '',

'Default Network Language'
=> '',

'Select the Network default language'
=> '',

'Check if you want to enable the languages menu bar.'
=> '',

'Load / restore General Network Settings from local disk'
=> '',

'Load General Settings'
=> '',

'Upload / Download network default settings for this network'
=> '',

'Select XML configuration file for upload.'
=> '',

'Download default settings file'
=> '',

'Upload new default settings file'
=> '',

'Manage Roles & Tasks'
=> '',

'Newest %s'
=> '',

'Attach Media'
=> '',

'Add Image or Video'
=> '',

'edit your post'
=> '',

'Post to %s (On this networks home page)'
=> '',

'You can route this post to one or many destinations with the selectors below.'
=> '',

'Post to community Blog (On this networks home page)'
=> '',

'My Comments'
=> '',

'Street address 1'
=> '',

'Street address 2'
=> '',

'ZIP Code'
=> '',

'Phone #'
=> '',

'Preview Image'
=> '',

'Clear Image'
=> '',

'To use a different image, click Clear Image and select a new image.'
=> '',

'My '
=> '',

'Your request to join this network could not be sent due to following reason: '
.'%s. You can go back to the home network by clicking Return to home network'
=> '',

'Your request to join this network has been successfully sent to the '
.'moderator of this network. The Moderator will check this request and approve '
.'or deny the request. You can go back to mother network by clicking the '
.'button Return to home network'
=> '',

'Return to home network successfully.'
=> '',

'Load / restore Roles Settings from local disk'
=> '',

'Load Roles Settings'
=> '',

'Invalid configuration file format. Configuration file should be a valid XML '
.'file. '
=> '',

'Roles settings successfully loaded from '
=> '',

' file.'
=> '',

'Please, select a valid XML configuration file.'
=> '',

'Role data sucessfully updated.'
=> '',

'New Role sucessfully created.'
=> '',

'Role sucessfully deleted.'
=> '',

'This Role can\'t be deleted.'
=> '',

'Select Task(s) you want to assign to this Role and press left/right arrow.'
=> '',

'Default Roles settings sucessfully restored.'
=> '',

'There is no Roles data in default XML settings file.'
=> '',

'all of these words'
=> '',

'Start Date'
=> '',

'End Date'
=> '',

'Select Any One Topic'
=> '',

'Poll has been deleted successfully.'
=> '',

'Poll has been saved successfully.'
=> '',

'Poll has been created successfully.'
=> '',

'Date range selected is invalid. Please, select a valid date range.'
=> '',

'Please enter either data or date to search'
=> '',

'Return to private page'
=> '',

'No items match your search criteria.'
=> '',

'You will be redirected in '
=> '',

' seconds, or you can click here to redirect now'
=> '',

'An Error Has Occurred'
=> '',

'Error details'
=> '',

'Information'
=> '',

'Please confirm action'
=> '',

'Warning!'
=> '',

'Testimonials'
=> '',

'Comments for '
=> '',

'Create new %s'
=> '',

'There are %s entries in this directory.'
=> '',

'Master Directory'
=> '',

'%s directory'
=> '',

'There is no TypedEntity associated with this Group yet. Would you like to '
.'create one?'
=> '',

'--- Please select ---'
=> '',

'Create it'
=> '',

'Update relation'
=> '',

'-- Please select --'
=> '',

'Update'
=> '',

'Typed Group Settings'
=> '',

'Sorry, you can\'t perform this action.'
=> '',

'Request to join this group as'
=> '',

'Join This Group as'
=> '',

'You are a %s'
=> '',

'Edit %s profile'
=> '',

'%s profile'
=> '',

'Unkonwn type selected'
=> '',

'LinkedIn Contacts: '
=> '',

'No contacts'
=> '',

'MS Live Contacts: '
=> '',

'Contacts'
=> '',

'Outlook Contacts: '
=> '',

'Plaxo Contacts: '
=> '',

' contact(s) sucessfully imported'
=> '',

'Invalid file type. Please select a valid LinkedIn CSV file. '
=> '',

'Please, select a valid LinkedIn CSV file.'
=> '',

'Invalid file type. Please select a valid Outlook CSV file. '
=> '',

'Please, select a valid Outlook CSV file.'
=> '',

'Invite message can\'t be empty.'
=> '',

'Please, select one or more contacts.'
=> '',

' contact(s) sucessfully deleted.'
=> '',

'Other'
=> '',

'No details.'
=> '',

'There are %d members in %s.'
=> '',

'There are %d friends.'
=> '',

'There are %d members in this %s.'
=> '',

'There are %d members.'
=> '',

'There are %d friends for %s.'
=> '',

'No relation exists.'
=> '',

'View All %s Members'
=> '',

'Business'
=> '',

'Church'
=> '',

'School'
=> '',

'Fan'
=> '',

'Supporter'
=> '',

'Customer'
=> '',

'Employee'
=> '',

'Postal Code'
=> '',

'Phone Number'
=> '',

'PeopleAggregator setup'
=> '',

'Already configured'
=> '',

'It looks like this PeopleAggregator is already set up.'
=> '',

'Click here to log in'
=> '',

'If something went wrong and you want to reconfigure PeopleAggregator, delete '
.'the'
=> '',

'file and refresh this page'
=> '',

'Almost done!'
=> '',

'Congratulations - you have nearly finished installing PeopleAggregator!'
=> '',

'The final step is to move the'
=> '',

'file from'
=> '',

'up into the'
=> '',

'directory'
=> '',

'On Linux, the following command will do so'
=> '',

'Once that is done, please refresh this page'
=> '',

'Alternatively, if something went wrong and you want to reconfigure '
.'PeopleAggregator, delete'
=> '',

'the'
=> '',

'Email Messages settings data successfully loaded from '
=> '',

'Email message settings successfully restored.'
=> '',

'You need to be member of this group to view the contents'
=> '',

'There was a problem:<br>No message(s) selected. Please select at least one '
.'message and try again.'
=> '',

'There was a problem:'
=> '',

'No folder selected. Please select a folder and try again.'
=> '',

'No message(s) selected. Please select at least one message and try again.'
=> '',

' updated successfully'
=> '',

'File '
=> '',

' loaded successfully.'
=> '',

'Click "Save" button to save new settings.'
=> '',

'Default settings sucessfully restored.'
=> '',

'User default Notifications Settings successfully updated.'
=> '',

'Setting correct default Notifications for Videoplay installations'
=> '',

'%s Events'
=> '',

'Data mapping error. Invalid data format.'
=> '',

'-no email address-'
=> '',

'Current %s'
=> '',

'Current Logo'
=> '',

'Upload %s'
=> '',

'File is not uploaded correctly.'
=> '',

'XML parsing error!'
=> '',

'Data not found or XML parsing error!'
=> '',

'Can\'t get data from URL. Please, check the given URL.'
=> '',

'Can\'t open file \''
=> '',

'File'
=> '',

'doesn\'t exist.'
=> '',

'No data! Check is file empty.'
=> '',

'Directory'
=> '',

'My Forum'
=> '',

'Find %s'
=> '',

'%s who call me friend'
=> '',

'%s Home'
=> '',

'%s Forum'
=> '',

'%s Gallery'
=> '',

'First'
=> '',

'Last'
=> '',

'Hi '
=> '',

'Activate your '
=> '',

' account by clicking the following link:'
=> '',

'User ID or Password field can\'t be blank.'
=> '',

'Invalid or missing SOAP XML file'
=> '',

'Invalid response received from'
=> '',

'Invalid XML response received from'
=> '',

'BinarySecurityToken not found in XML response received from'
=> '',

'Can\'t estabilish WEB connection.'
=> '',

'Unknown communication error has been occured.'
=> '',

'Communication error - no response received.'
=> '',

'AdrBook: Invalid response received from'
=> '',

'Plaxo data parser error.'
=> '',

'Invalid Plaxo Header received.'
=> '',

'Unable to get list of the Plaxo folders.'
=> '',

'Unable to read the Plaxo folders.'
=> '',

'Sorry - you are not logged in or you have been logged out due to inactivity. '
.'Please, log in again.'
=> '',

'Myself'
=> '',

'Everyone'
=> '',

'Friends Only'
=> '',

'In Family'
=> '',

'41-50 years'
=> '',

'Group deleted successfully'
=> '',

' deleted successfully'
=> '',

'Question is set for all users'
=> '',

'Please select a question to activate.'
=> '',

'Question has been successfully saved'
=> '',

'Fields marked with * must not be left empty'
=> '',

'Question has been deleted successfully'
=> '',

' is already enabled at specified orientation'
=> '',

'Please select atleast one user.'
=> '',

' uploaded successfully.'
=> '',

'Following relations could not be added as default relation '
=> '',

'Default settings for the network has been saved'
=> '',

'Click "Save" button to store new settings.'
=> '',

'Request to join'
=> '',

'Date range selected is invalid, so it has been ignored in searching'
=> '',

'Your comment contains some illegal characters. Please try again.'
=> '',

'Comment can not be left blank'
=> '',

'Sorry, your comment cannot be posted as it looks like spam. Try removing any '
.'links to possibly suspect sites, and re-submitting.'
=> '',

'Your comment has been posted successfully'
=> '',

'Sorry, your comment cannot be posted as it was classified as spam by '
.'Akismet, or contained links to blacklisted sites.  Please check the links in '
.'your post, and that your name and e-mail address are correct.'
=> '',

'Sorry, your comment cannot be posted as it was classified as spam by '
.'Akismet, or contained links to blacklisted sites. Please check the links in '
.'your post, and that your name and e-mail address are correct.'
=> '',

'basecamp test disabled'
=> '',

'please enter your basecamp login details above.'
=> '',

'scraping contacts page to get companies'
=> '',

'getting list of people from company '
=> '',

' who are working on this project'
=> '',

'testing ImageResize module with engine'
=> '',

'make sure to hit ctrl-F5 after clicking, to clear the cache'
=> '',

'flushing cache'
=> '',

'done'
=> '',

'expanding and cropping 135x75 to fit inside 300x300'
=> '',

'reduce only'
=> '',

'fitting 135x75 inside 300x300'
=> '',

'reduce only, smaller'
=> '',

'Report abuse'
=> '',

'Comment'
=> '',

'Submit Abuse'
=> '',

'Overall Rating'
=> '',

'Your Rating'
=> '',

'Please'
=> '',

'log in'
=> '',

'to rate this audio'
=> '',

'to rate this post'
=> '',

'Are you sure you want  to post the comment?'
=> '',

'Leave a Comment'
=> '',

'Submit Comment'
=> '',

'Are you sure you want to post the comment?'
=> '',

'Unknown error.'
=> '',

'Detailed information has been written into the error log.'
=> '',

'to rate this image'
=> '',

'to rate this video'
=> '',

'Showing profile fields in sidebar widget.'
=> '',

'peopleaggregator: widgetization testbench'
=> '',

'Select a module'
=> '',

'Module'
=> '',

'Request'
=> '',

'Response'
=> '',

'Rendered response'
=> '',

'An unknown error occurred - no response available.'
=> '',

'Note: do not enable widgetization on public facing webservers as it allows '
.'operations to be performed as arbitrary users! Access must be restricted to '
.'trusted front-end systems.'
=> '',

'This file may not be called directly.'
=> '',

'No admininstrator password configured'
=> '',

'To use the updater, add a line like this to'
=> '',

'Log in'
=> '',

'All the files have been updated. Now you need to'
=> '',

'click here to update the database'
=> '',

'and the update will be complete'
=> '',

'Error occurred running database update:'
=> '',

'PeopleAggregator system update'
=> '',

'Please login to comment'
=> '',

'Your Recommendation: '
=> '',

'Error processing request'
=> '',

'Error parsing URL'
=> '',

'User Private Page'
=> '',

'People Page'
=> '',

'Blog Post Permalink Page'
=> '',

'Forums Page'
=> '',

'Search Page'
=> '',

'Date Established'
=> '',

'Honors / Awards'
=> '',

'Religion / Faith'
=> '',

'Congregational member'
=> '',

'Church member'
=> '',

'Church goer'
=> '',

'owner'
=> '',

'admin'
=> '',

'banned'
=> '',

'limited'
=> '',

' E-mail address is not valid'
=> '',

'The domain of your E-mail address is not in the list of  allowed domains'
=> '',

'Are you sure you want to delete this Ad?'
=> '',

'Ad Center'
=> '',

'%s - %s'
=> '',

'Caption has already been taken, please enter a different caption'
=> '',

'Ad Title can not have empty.'
=> '',

'Ad Target page is not specified.'
=> '',

'middle'
=> '',

'(%d %ss)'
=> '',

'Forum Board for this group has not yet been created.'
=> '',

'The personal forum board for this user has not yet been created.'
=> '',

'Post does not exist!'
=> '',

'Thread does not exist!'
=> '',

'You do not have permission to manage Ads.'
=> '',

'Add as %s'
=> '',

);

?>