<?php

// This file is automatically generated from messages.po.  Do not edit it!

$TRANSLATED_STRINGS = array(

'Create Group'
=> '',

'Edit Group'
=> '',

'Message sent successfully to '
=> '',

'Last Login'
=> 'Dernier connexion',

'Latest Registered'
=> '',

'Select any %s file to upload'
=> '',

'You have to login before uploading a %s'
=> '',

'Blog Feed sucessfully deleted.'
=> '',

'Role can\'t be deleted.'
=> '',

'Successfully deleted.'
=> '',

'Not found'
=> '',

'Please enter a valid URL!'
=> '',

'Please, select one of the following Professional profiles: '
=> '',

'Please, select the XFN relations you want to import: '
=> '',

'Sorry, we couldn\'t any identity informations '
=> '',

'at: '
=> '',

'in your HTML text.'
=> '',

'Please, select contacts you want to import.'
=> '',

'We haven\'t found any contacts on your Plaxo account.'
=> '',

'Username and/or password field can\'t be empty!'
=> '',

'Apply to User pages'
=> '',

'Apply to this Network'
=> '',

'Apply to '
=> '',

' group'
=> '',

'Tasks/Permissions'
=> '',

'Edit/Assign Role for user: '
=> '',

'Select roles you want to associate with this user and press left/right '
.'arrow, <br />'
=> '',

'We haven\'t found any contacts on your MSLive account.'
=> '',

'Recently Created'
=> 'Date de création',

'Recently Modified'
=> 'Date de modification',

'Largest Group'
=> 'Taille',

'Answer can not be left blank'
=> '',

'Sorry, your Answer cannot be posted as it looks like spam. Try removing any '
.'links to possibly suspect sites, and re-submitting.'
=> '',

'Your Answer has been posted successfully'
=> '',

'Sorry, your answer cannot be posted as it was classified as spam by Akismet, '
.'or contained links to blacklisted sites. Please check the links in your '
.'post, and that your name and e-mail address are correct.'
=> '',

'This section is disabled. Click the checkbox above to show it in your '
.'sidebar widget.'
=> '',

'click to include'
=> '',

'Design your sidebar widget'
=> '',

'Rename this widget'
=> '',

'Rename'
=> '',

'Or'
=> '',

'Delete this widget'
=> '',

'Are you sure you wish to delete this widget?'
=> '',

'Preview'
=> '',

'%s - My Widgets - %s'
=> '',

'About Me'
=> '',

'About'
=> '',

'User image.'
=> '',

'More Detail'
=> '',

'Sex'
=> '',

'Date of birth'
=> '',

'State'
=> '',

'City'
=> '',

'ZIP code'
=> '',

'Country'
=> '',

'Blog'
=> '',

'Flickr'
=> '',

'Delicious'
=> '',

'User Tags (Interests)'
=> '',

'No details entered yet.'
=> '',

'Professional'
=> '',

'Headline'
=> '',

'Industry'
=> '',

'Company'
=> '',

'Title'
=> '',

'Website'
=> '',

'Career skill'
=> '',

'Prior Company'
=> '',

'Degree'
=> '',

'Languages'
=> '',

'Awards'
=> '',

'Summary'
=> '',

'Download CV'
=> '',

'Download'
=> '',

'Personal'
=> '',

'Ethnicity'
=> '',

'Religion'
=> '',

'Political view'
=> '',

'Passion'
=> '',

'Activities'
=> '',

'Books'
=> '',

'Movies'
=> '',

'Music'
=> '',

'Cuisines'
=> '',

'TV shows'
=> '',

'Actions'
=> '',

'Activity Feed'
=> '',

'My Activity Feeds'
=> '',

'Activity Feeds'
=> '',

'Change Group Settings'
=> '',

'File upload error: '
=> '',

'Please supply a name.'
=> '',

'Group Name'
=> '',

'Group Category'
=> '',

'Tags'
=> '',

'separated tags with commas'
=> '',

'Group Photo'
=> '',

'Choose File'
=> '',

'Current Photo'
=> '',

'Group Description'
=> '',

'Registration Type'
=> '',

'Open'
=> '',

'Moderated'
=> '',

'Invite Only'
=> '',

'Submit'
=> '',

'Entity Type'
=> '',

'Compose'
=> '',

'Message sent successfully to %s'
=> '',

'Message sending failed for %s  as user(s) doesn\'t exist'
=> '',

'Send'
=> '',

'Message composed will be discarded. Do you want to continue?'
=> '',

'To'
=> '',

'select friend'
=> '',

'Note: to address a message to a user who is not your friend, please visit '
.'their public page and click \'send message\'.'
=> '',

'Subject'
=> '',

'Message'
=> '',

'Cancel'
=> '',

'You have not created any folders.'
=> '',

'Write Comment for '
=> '',

'\'s Answers'
=> '',

'No answer is posted till now'
=> '',

'Submit your answer'
=> '',

'Answers'
=> '',

'Submit Answers'
=> '',

'Album'
=> '',

'Select Album'
=> '',

'Upload'
=> '',

'Groups'
=> 'Groupes',

'Thumbnail'
=> '',

'Title/Description/Date/Tags'
=> '',

'Album/Playlist'
=> '',

'No Audio'
=> '',

'Blog Settings'
=> '',

'You have 3 blog options:'
=> '',

'You can contribute to the community blog'
=> '',

'You also can have a personal blog. A personal blog shows up on your page '
.'with posts routed to the community blog by default. You can opt for those to '
.'only be on your personal blog.'
=> '',

'If you already have a blog, you can display your External Blog here.'
=> '',

'Add a personal blog'
=> '',

'Display my external blog here'
=> '',

'Save'
=> '',

'View my public page'
=> '',

'Configure external blog'
=> '',

'Welcome'
=> '',

'Enter your new password'
=> '',

'Re-enter the new password'
=> '',

'Change Password'
=> '',

'Please enter your new password'
=> '',

'Please confirm your new password'
=> '',

'Passwords do not match. Please re-enter'
=> '',

'Password should be of %s characters or more.'
=> '',

'Password should be less than %s charcaters.'
=> '',

'Manage comments.'
=> '',

'When'
=> '',

'Parent'
=> '',

'Abuses'
=> '',

'Author'
=> '',

'Delete'
=> '',

'No Comments'
=> '',

'Manage Comments'
=> '',

'Anonymous'
=> '',

'ConfigManager'
=> '',

'Section does not exists!'
=> '',

'Configuration data sucessfully stored.'
=> '',

'Select edit mode and section name'
=> '',

'Mode'
=> '',

'Section'
=> '',

'People Aggregator Defender setup'
=> '',

'Rule'
=> '',

'Status'
=> '',

'description'
=> '',

'PADefender configuration data sucessfully stored.'
=> '',

'Configure Email'
=> '',

'Select An email type'
=> '',

'Select an email type'
=> '',

'Description'
=> '',

'Email Template'
=> '',

'Configurable variables related to the selected message'
=> '',

'Recipient/Requester configurable variables available in each message'
=> '',

'Network configurable variables available in each message'
=> '',

'Group configurable variables available in each message of Group type'
=> '',

'Restore Default'
=> '',

'Store as Defaults'
=> '',

'Caution - software developers only'
=> '',

'Load / restore Email Message settings from local disk'
=> '',

'Select XML configuration file.'
=> '',

'Select action'
=> '',

'Load Email Message settings'
=> '',

'Revert All Messages'
=> '',

'Warning: you will lose all message changes made at this site.'
=> '',

'Select page'
=> '',

'Select page you want to customize.'
=> '',

'Get module info'
=> '',

'Add this module to: '
=> '',

'Page ID'
=> '',

'If you want to create a new page, enter here an unique Page ID number.'
=> '',

'For dynamic pages, this ID number should start from 200.'
=> '',

'Page Title'
=> '',

'Enter Page name'
=> '',

'Login required'
=> '',

'No'
=> '',

'Yes'
=> '',

'Select Page type'
=> '',

'Page type'
=> '',

'Enter Page type (user, group, network). For multiple types use "|" to '
.'separate types.'
=> '',

'Is page configurable'
=> '',

'If a page is configurable - these settings will be available in Customize UI '
.'pages.'
=> '',

'Required user or administration permissions for access to this page'
=> '',

'Enter required administration permissions. Currently, these permissions are '
.'available'
=> '',

'Page Theme'
=> '',

'Enter Page theme (Beta)'
=> '',

'Page Outer Template'
=> '',

'Enter Page Outer Template (container_three_column.tpl, container_two_column.'
.'tpl ...)'
=> '',

'Header Template'
=> '',

'Enter Page Header Template (header.tpl, header_group.tpl ...)'
=> '',

'Page boot (pre-execute) PHP code'
=> '',

'Enter here code that should be executed on page boot before any module '
.'initialization function called. Use this only if you have a good reason for '
.'that and when you can\'t place that code inside a module - initializeModule() '
.'function. For example, if some modules need and share same data and you want '
.'to avoid executing same code multiple times. In that case, place here '
.'required code to evaluate those data and forward results to each module via '
.'$module_shared_data variable. For example'
=> '',

'NOTE: If your page does not require additional boot code, leave this '
.'untouched.'
=> '',

'Left modules'
=> '',

'Enter Left modules separated by commas'
=> '',

'Middle modules'
=> '',

'Enter Middle modules separated by commas'
=> '',

'Right modules'
=> '',

'Enter Right modules separated by commas'
=> '',

'Page JavaScript files'
=> '',

'Enter page Javascript file names separated by commas'
=> '',

'Page CSS files'
=> '',

'Enter page CSS file names separated by commas'
=> '',

'Page navigation links PHP code'
=> '',

'Enter code required for generating page navigation links. Here should be '
.'moved code from function'
=> '',

'declared in'
=> '',

'class (web/includes/classes/Navigation.php)'
=> '',

'inside'
=> '',

'statement'
=> '',

'Please see an example below. In this example we will use code written for '
.'generating navigation links on'
=> '',

'page'
=> '',

'So, this PHP code block should be copied and pasted in a text field above. '
.'If old'
=> '',

'page will not be used anymore, this code block should be removed from '
.'Navigation class'
=> '',

'See'
=> '',

'line'
=> '',

'NOTE: Code in the box above is only for example. You must delete it or enter '
.'your menu- navigation code here!'
=> '',

'Page body attributes'
=> '',

'Enter page body CSS attribute. For example'
=> '',

'Save generated page'
=> '',

'Select if you want to save generated Page'
=> '',

'Edit/Create Dynamic Page'
=> '',

'Your page created sucessfull. Page data'
=> '',

'Click here for preview'
=> '',

'Write Testimonial'
=> '',

'Testimonial'
=> '',

'Write Testimonial for '
=> '',

'Left'
=> '',

'Right'
=> '',

'Middle'
=> '',

'Background Image'
=> '',

'Current Background Image'
=> '',

'Upload Background Image'
=> '',

'Image as header background will appear on your Networks Pages'
=> '',

'Apply background image'
=> '',

'Theme Selector'
=> '',

'Module Selector'
=> '',

'Desktop image'
=> '',

'Customize Theme'
=> '',

'Desktop Image'
=> '',

'Current Desktop Image'
=> '',

'Upload Desktop Image'
=> '',

'Image will appear on your Personal Pages'
=> '',

'Image will appear on your Groups Pages'
=> '',

'Image will appear on your Networks Pages'
=> '',

'Set image appearance'
=> '',

'Stretch to fit'
=> '',

'Crop'
=> '',

'Tile'
=> '',

'Leave it alone'
=> '',

'Images 1016 pixels wide by 191 pixels tall will have the best results'
=> '',

'Set Desktop image Turn on/off'
=> '',

'Turn on'
=> '',

'Turn off'
=> '',

'Here to set the Desktop image is display turn on or off.'
=> '',

'Apply desktop image'
=> '',

'Select page layout'
=> '',

'Select page layout template.'
=> '',

'Add a side module'
=> '',

'Select a side module to add it to your page, chose module placement column, '
.'then click "Save settings". '
=> '',

'Add a middle module'
=> '',

'Select a middle module to add it to your page, chose module placement '
.'column, then click "Save settings". '
=> '',

'Available Modules'
=> '',

'Enable'
=> '',

'Show in Left or Right'
=> '',

'Stacking Order'
=> '',

'Use these settings to customize the look of your Network pages'
=> '',

'that others will see.'
=> '',

'Select Theme'
=> '',

'Apply Changes'
=> '',

'This is the echo test module.'
=> '',

'>Update:'
=> '',

'Echo Test'
=> '',

'Family Name'
=> '',

'Family Photo'
=> '',

'About this Family'
=> '',

'Create Family'
=> '',

'Change Family Settings'
=> '',

'Please supply a name for the Family.'
=> '',

'Family has been updated successfully.'
=> '',

'Family has been created successfully.'
=> '',

'Edit'
=> '',

'Full view'
=> '',

'Return to %s gallery'
=> '',

'Select'
=> '',

'Access'
=> '',

'in which your'
=> '',

'file will appear...'
=> '',

'Create New Album'
=> '',

'Return to media gallery'
=> '',

'Basic info'
=> '',

'Login Name'
=> '',

'Password'
=> '',

'Confirm Password'
=> '',

'First Name'
=> '',

'Last Name'
=> '',

'Email'
=> '',

'Upload Photo'
=> '',

'Current Image'
=> '',

'Remove Picture'
=> '',

'You have 3 blog options'
=> '',

'You also can have a personal blog. A personal blog shows up on your page '
.'with posts routed to the community blog by default. You can opt for those to '
.'only be on your personal blog'
=> '',

'If you already have a blog, you can display your External Blog on My Page'
=> '',

'Profile updated successfully.'
=> '',

'Blogs/RSS'
=> '',

'Add another Blog'
=> '',

'Remove'
=> '',

'Permission to view your Blog'
=> '',

'Blog Title'
=> '',

'Blog URL'
=> '',

'Blog Feed URL'
=> '',

'Basic Info'
=> '',

'General Info'
=> '',

'Personal Info'
=> '',

'Professional Info'
=> '',

'Notifications'
=> '',

'Import Contacts'
=> '',

'Export'
=> '',

'Delete Account'
=> '',

'You are not allowed to delete your account here. You can delete your account '
.'from meta organization only.'
=> '',

'If you delete your account, all your content posted and your membership in '
.'other networks will be deleted. Your complete information will be deleted '
.'from the network.'
=> '',

'To delete your account you have to check this box.'
=> '',

'Delete My Account'
=> '',

'EditProfileModule::handleSaveProfile() - Unknown save handler!'
=> '',

'Fields marked with * can not be empty, First name can not be empty.'
=> '',

'Fields marked with * can not be empty, Email field is mandatory.'
=> '',

'Password and confirm password should match.'
=> '',

'Personal and professional info'
=> '',

'show everything'
=> '',

'show what your friends see'
=> '',

'show only public info'
=> '',

'Sidebar preview of your hCard/XFN profile'
=> '',

'Please modify the hCard/XFN preview below to suit your taste.'
=> '',

'Once you have selected what you want to display, click \'create hCard\', then '
.'copy the generated HTML to your blog or wherever you want to use it.'
=> '',

'The Date of Birth is invalid.'
=> '',

'Url is invalid'
=> '',

'Sorry: you are unable to save data.'
=> '',

'Reason: '
=> '',

'Family'
=> '',

'Create new %s'
=> '',

'Select for All'
=> '',

'Slogan'
=> '',

'Slogan will appear on your Public Page.'
=> '',

'Shout Out'
=> '',

'Shout out will appear on your Public Page.'
=> '',

'Gender'
=> '',

'Date of Birth'
=> '',

'Address'
=> '',

'Address 2'
=> '',

'Other state'
=> '',

'State/Province'
=> '',

'Zip/Postal Code'
=> '',

'Phone'
=> '',

'Mobile Phone'
=> '',

'Seperate tags with commas.'
=> '',

'I want to receive  notifications when'
=> '',

'via my registered email'
=> '',

'via my account inbox'
=> '',

'Notify \'messages waiting\''
=> '',

'through my registered mail'
=> '',

'\'messages waiting\' notifications in my mail box, when new messages arrive'
=> '',

'Restore default settings'
=> '',

' Reason: '
=> '',

'Political View'
=> '',

'TV Shows'
=> '',

'Sorry: you are unable to save data'
=> '',

'Upload CV'
=> '',

'Valid file types are .doc and .pdf'
=> '',

'This will replace your current CV'
=> '',

'Work Phone'
=> '',

'Career Skills'
=> '',

'Prior Title'
=> '',

'College Name'
=> '',

'Your full Professional biography here. Please note there is a 2,500 '
.'character limit.'
=> '',

'Honors &amp; Awards'
=> '',

'Specify how close you are in your relationship with'
=> '',

'User: '
=> '',

'Check if'
=> '',

'is'
=> '',

'in family'
=> '',

'Update Relationship Request'
=> '',

'ADD as a Friend'
=> '',

'Your request for adding '
=> '',

' as a relation has already been sent'
=> '',

'Edit Relationship'
=> '',

'Your relationship request approved.'
=> '',

'Relationship estabilished.'
=> '',

'You cannot add an Event to the calendar of group %s, as you are not a member.'
=> '',

'Couldn\'t create event:'
=> '',

'Couldn\'t create EventAssociation:'
=> '',

'There was a problem updating the event:'
=> '',

'Event %d doesn\'t exist'
=> '',

'Couldn\'t update the event:'
=> '',

'There was a problem deleting the event:'
=> '',

'The event has been deleted.'
=> '',

'Couldn\'t delete the event:'
=> '',

'No users given'
=> '',

'There was a problem associating the event:'
=> '',

'%s is not a user'
=> '',

'Add people:'
=> '',

'You cannot add an Event to the caledar of group %s, as you are not a member.'
=> '',

'Add group:'
=> '',

'You may not remove the association to this event.'
=> '',

'You cannot remove yourself from this event, as you created it.  Please use '
.'\'Delete Event\' instead.'
=> '',

'Event'
=> '',

'Event Banner'
=> '',

'Starts'
=> '',

'Ends'
=> '',

'Venue'
=> '',

'Are you sure you want to delete this Event?'
=> '',

'Create new Event'
=> '',

'Edit Event'
=> '',

'Create Event'
=> '',

'Event title'
=> '',

'Start date'
=> '',

'Start time'
=> '',

'End date'
=> '',

'End time'
=> '',

'Event venue'
=> '',

'Event description'
=> '',

'Current Event Banner'
=> '',

'Upload Event Banner'
=> '',

'This event appears on'
=> '',

'Calendar for'
=> '',

'(This event will always appear in the creator\'s calendar.)'
=> '',

'Add to further calendars'
=> '',

'Add people\'s login names here, seperated by commas.'
=> '',

'Groups you are a member of'
=> '',

'Add'
=> '',

'Unknown event association'
=> '',

'Display as'
=> '',

'List'
=> '',

'Calendar'
=> '',

'Personal Events'
=> '',

'External Feeds'
=> '',

'There are %d members in %s.'
=> '',

'There are %d friends.'
=> '',

'There are '
=> '',

' members '
=> '',

'Approve'
=> '',

'Deny'
=> '',

'There are %d members in this %s.'
=> '',

'There are %d members.'
=> '',

'There are %d friends for %s.'
=> '',

'member since:'
=> '',

'waiting approval'
=> '',

'No relation exists.'
=> '',

'FaceBookFeed'
=> '',

'Friend'
=> '',

'Last login'
=> '',

'Latest registered'
=> '',

'Sort By'
=> '',

'(%d friends)'
=> '',

'(%d %ss)'
=> '',

'sort by'
=> '',

'Family Directory'
=> '',

'Name'
=> '',

'Family Members'
=> '',

'Login name'
=> '',

'Login name may contain letters, numbers and underscores (_).'
=> '',

'First name'
=> '',

'Last name'
=> '',

'Day'
=> '',

'Month'
=> '',

'Year'
=> '',

'Street address 1'
=> '',

'Street address 2'
=> '',

'ZIP Code'
=> '',

'Phone #'
=> '',

'Password can be 5-15 characters long, and is case sensitive.'
=> '',

'Confirm password'
=> '',

'use own email account'
=> '',

'use a parent\'s email account'
=> '',

'Upload a photo'
=> '',

'Or enter a photo URL'
=> '',

'Preview Image'
=> '',

'Clear Image'
=> '',

'Your photo'
=> '',

'To use a different image, click Clear Image and select a new image.'
=> '',

'I have read and agree to the %s <a href=\'%s/terms.php\' target=\'_blank\'>Terms '
.'and Conditions</a>'
=> '',

'Family Members Moderation'
=> '',

'Edit/Assign Role'
=> '',

'Joined Family'
=> '',

'There are no members in this %s'
=> '',

'Remove Selected'
=> '',

'Add a Child'
=> '',

'Member(s) Deleted'
=> '',

'Please select a member'
=> '',

'You have left "%s" successfully.'
=> '',

'Child\'s account was successfully created'
=> '',

'Member'
=> '',

'Family Profile'
=> '',

'Sorry, you can\'t perform this action.'
=> '',

'Request to join this family as'
=> '',

'Join This family as'
=> '',

'You are a %s'
=> '',

'Edit %s profile'
=> '',

'%s profile'
=> '',

'Please select a type.'
=> '',

'TypedEntity associated successfully.'
=> '',

'Please upload a valid Game Image in %s'
=> '',

'You have updated your relation to "%s" successfully.'
=> '',

'You are already a member of "%s"'
=> '',

'Your request to join "%s" has been submitted to the owner of the group.'
=> '',

'You have joined "%s" successfully.'
=> '',

'You need to be logged in to join a group.'
=> '',

'You can\'t leave your own group.'
=> '',

'You are not member of "%s".'
=> '',

'Group sucessfully deleted.'
=> '',

'Leave this Family'
=> '',

'Update relation'
=> '',

'-- Please select --'
=> '',

'Update'
=> '',

'Join now'
=> '',

'Family Settings'
=> '',

'Forgotten your PeopleAggregator account information?'
=> '',

'Just enter the e-mail address or login name you signed up with, and we\'ll '
.'mail you a link to change your password.'
=> '',

'E-mail address:'
=> '',

'Get new password'
=> '',

'Please enter your email address or login name.'
=> '',

'Please enter either email or Login name'
=> '',

'Invalid email address.  Please try again.'
=> '',

'A link has been e-mailed to you to let you change your password.  Thanks!'
=> '',

'There are no accounts in our system with the e-mail address %s.\n'
.'              If you have spelled the address incorrectly or entered the '
.'wrong address, please try again.'
=> '',

'Recover Password'
=> '',

'Latest Forum Posts'
=> '',

'Date'
=> '',

'Forum Name'
=> '',

'Thread Title'
=> '',

'User'
=> '',

'Last Post'
=> '',

'Replies'
=> '',

'No posts'
=> '',

'Posts'
=> '',

'You will be able to answer this post after admin approve your membership '
.'request'
=> '',

'Banned User'
=> '',

'Administrator message'
=> '',

'label'
=> '',

'Edit post'
=> '',

'Edit thread'
=> '',

'Post title'
=> '',

'Thread title'
=> '',

'Post content'
=> '',

'Thread content'
=> '',

'Forum'
=> '',

'Forum Last post'
=> '',

'Threads'
=> '',

'Category:'
=> '',

'Are you sure you want to delete this category?'
=> '',

'Posted by'
=> '',

'no posts'
=> '',

'Pages: '
=> '',

'Thread'
=> '',

'You will be able to answer this topic after admin approve your membership '
.'request'
=> '',

'Are you sure you want to delete this topic?'
=> '',

'Thread Last post'
=> '',

'Viewed'
=> '',

'Forum:'
=> '',

'Are you sure you want to delete this forum?'
=> '',

'Created by'
=> '',

'Forums'
=> '',

'Forum Board for this network has not yet been created.'
=> '',

'Forum Board for this group has not yet been created.'
=> '',

'The personal forum board for this user has not yet been created.'
=> '',

'Post does not exist!'
=> '',

'Thread does not exist!'
=> '',

'You don\'t have permissions to post on this Forum!'
=> '',

'New Thread'
=> '',

'You don\'t have permissions to create a new thread!'
=> '',

'Forum does not exists!'
=> '',

'Edit Forum'
=> '',

'New Forum'
=> '',

'Forum title'
=> '',

'Short description'
=> '',

'You don\'t have permissions to create a new forum!'
=> '',

'Category does not exists!'
=> '',

'Edit Category'
=> '',

'New Category'
=> '',

'Category title'
=> '',

'You don\'t have permissions to create a new category!'
=> '',

'network forum board'
=> '',

'group forum board'
=> '',

'personal forum board'
=> '',

'Forum Board description goes here'
=> '',

'Forum Board sucessfully saved'
=> '',

'You don\'t have permissions to create this Forum Board!'
=> '',

'Forum Settings'
=> '',

'Forum name'
=> '',

'Forum description'
=> '',

'Allow anonymous post'
=> '',

'Allow users to create Categories'
=> '',

'Allow users to create Forums'
=> '',

'Membership approval required'
=> '',

'Threads per page'
=> '',

'Posts per page'
=> '',

'Avatar size'
=> '',

'Edit mode'
=> '',

'Forum theme'
=> '',

'Banned users message'
=> '',

'Join requested message'
=> '',

'Join approved message'
=> '',

'You don\'t have permissions to edit Forum Board settings!'
=> '',

'You don\'t have required permissions for this task!'
=> '',

'Post does not exists!'
=> '',

'Thread does not exists!'
=> '',

'Thread sucessfully removed'
=> '',

'Forum sucessfully deleted'
=> '',

'Category sucessfully deleted'
=> '',

'Post sucessfully deleted'
=> '',

'Thread not found!'
=> '',

'sticky'
=> '',

'locked'
=> '',

'Thread status sucessfully changed'
=> '',

'Anonymous user can\'t be banned'
=> '',

'You can\'t ban itself.'
=> '',

'Can\'t ban user - user not found!'
=> '',

'User status sucessfully changed.'
=> '',

'User is'
=> '',

'not'
=> '',

'banned now.'
=> '',

'Please, enter your name or email address'
=> '',

'Please, enter correct verification code'
=> '',

'Please, enter reply title'
=> '',

'Please, enter reply message text'
=> '',

'Reply post sucessfully saved'
=> '',

'Please, enter thread title'
=> '',

'Please, enter thread text'
=> '',

'Thread sucessfully created'
=> '',

'Please, enter forum title'
=> '',

'Please, enter forum description text'
=> '',

'Forum sucessfully created'
=> '',

'Forum data sucessfully updated'
=> '',

'Please, enter category title'
=> '',

'Please, enter category description text'
=> '',

'Category sucessfully created'
=> '',

'Category data sucessfully updated'
=> '',

'Please, enter numeric value into the "threads_per_page" field'
=> '',

'Please, enter numeric value into the "posts_per_page" field'
=> '',

'Settings data sucessfully updated'
=> '',

'Title field can\'t be empty'
=> '',

'Content field can\'t be empty'
=> '',

'Post sucessfully saved'
=> '',

'Thread sucessfully saved'
=> '',

'Reply to'
=> '',

'post'
=> '',

'thread'
=> '',

'Reply title'
=> '',

'Reply content'
=> '',

'User '
=> '',

'wrote'
=> '',

'Enter the verification code'
=> '',

'Code'
=> '',

'Your name or email'
=> '',

'Click here to create it'
=> '',

'Forums List'
=> '',

'type: '
=> '',

'board'
=> '',

'Forum Statistics'
=> '',

'Type'
=> '',

'Members'
=> 'Membres',

'Categories'
=> '',

'Topics'
=> '',

'Founded'
=> '',

'Request to join this group'
=> '',

'Join This Group'
=> '',

'Leave This Group'
=> '',

'Group Settings'
=> '',

'Invite Into Groups'
=> '',

'Please select a group'
=> '',

'Invitation could not be sent to following login names- %s'
=> '',

'Invitation could not be sent to following email addresses- %s'
=> '',

'Invitation from %s %s to join %s'
=> '',

'Sorry: you are unable to invite a friend.  Reason: %s'
=> '',

'Select a group to invite into'
=> '',

'Enter Your friend\'s login name(in People Aggregator) or email address'
=> '',

'(separated by comma)'
=> '',

'Write here personalized message for invitees. It will be appended to email'
=> '',

'Write your invitation Message'
=> '',

'Send Invitation'
=> '',

'Moderate Group Members'
=> '',

'Moderate Membership'
=> '',

'Moderate Content'
=> '',

'Content'
=> '',

'There are no pending moderation requests'
=> '',

'Content Approved'
=> '',

'Content Denied'
=> '',

'Please select a content for approval'
=> '',

'Please select a content for denial'
=> '',

'Requests'
=> '',

'Approve or deny requests to join this group'
=> '',

'User Approved'
=> '',

'User Denied'
=> '',

'Please select a user for approval'
=> '',

'Please select a user for denial'
=> '',

'Moderate %s Members'
=> '',

'Moderation'
=> '',

'Remove selected members from the %s'
=> '',

'Declare as Moderator'
=> '',

'Declare as Member'
=> '',

'User status sucessfuly changed.'
=> '',

'Can\'t change status for this user.'
=> '',

'%d members'
=> 'Membres',

'No Groups found.'
=> '',

'Click <a href="%s">here</a> to create one.'
=> '',

'caption'
=> '',

'Group doesn\'t exist'
=> '',

'Browse %d Groups'
=> '',

'No groups in this category'
=> '',

'On this page you can manage all posts of the %s.'
=> '',

'Create post'
=> '',

'title'
=> '',

'No Content Published'
=> '',

'On this page you can manage all the forums of the Group.'
=> '',

'Create Forum'
=> '',

'Manage %s Contents'
=> '',

'Alphabetical'
=> '',

'Largest'
=> '',

'Date Created'
=> '',

'Group Directory'
=> '',

'There are %d groups'
=> '',

'Create a Group'
=> '',

'Search Groups'
=> '',

'Search for'
=> '',

'%d Members'
=> 'Membres',

'Created'
=> '',

'Moderated By'
=> '',

'No groups found.'
=> '',

'Group Statistics'
=> '',

'Category'
=> '',

'Owner'
=> '',

'No Photos.'
=> '',

'Gallery'
=> '',

'Recent Media'
=> '',

'Group Gallery'
=> '',

'My Gallery'
=> '',

'Images'
=> '',

'Video'
=> '',

'Audio'
=> '',

'No images have been published yet.'
=> '',

'No videos have been published yet.'
=> '',

'No audio has been published yet.'
=> '',

'Are you sure you want to delete this image'
=> '',

'Added as a friend by'
=> '',

'Invite friends and colleagues to join %s:'
=> '',

'Choose a program or service below to import your contacts:'
=> '',

'Your Plaxo ID'
=> '',

'(Enter your email or AIM screen name here)'
=> '',

'Enter your password'
=> '',

'We will not store your password. It will only be temporarily used to access '
.'your Plaxo address book.'
=> '',

'Your WindowsLive ID'
=> '',

'(Enter your WindowsLive ID here)'
=> '',

'Your password'
=> '',

'We will not store your password. It will only be temporarily used to access '
.'your Windows Live address book.'
=> '',

'Select CSV file'
=> '',

'(Select CSV file you want to load)'
=> '',

'Email:'
=> '',

'(separate addresses with commas)'
=> '',

' Login Name'
=> '',

'Write your invitation Message:'
=> '',

'Invite'
=> '',

'Following user names are not valid %s'
=> '',

'Following email addresses are not valid: %s'
=> '',

' Invalid Email addresses'
=> '',

'Sorry: you are unable to invite a friend. Reason: %s'
=> '',

'An Invitation has been sent to - %s'
=> '',

'Invitation Status'
=> '',

'Accepted invitations'
=> '',

'No Accepted Invitations'
=> '',

'Pending invitations'
=> '',

'No pending Invitations'
=> '',

'Largest %s'
=> '',

'Leader Board'
=> '',

'No.'
=> '',

'User Name'
=> '',

'Last Activity Date'
=> '',

'Ranking points'
=> '',

'Ranking stars'
=> '',

'unknown'
=> '',

'There\'s no ranked users.'
=> '',

'Manage your link lists'
=> '',

'Create new'
=> '',

'Edit selected list'
=> '',

'Delete selected list'
=> '',

'Create a list'
=> '',

'New List Name'
=> '',

'Links'
=> '',

'Links under the selected list will be shown here'
=> '',

'Create link'
=> '',

'Link caption'
=> '',

'URL'
=> '',

'Links Control Panel'
=> '',

'Sorry - you are not logged in or you have been logged out due to inactivity.'
.'<br />Please, log in again.<br />'
=> '',

'Login'
=> '',

'%s login.'
=> '',

'You can login directly if you have an account,<br />or you can <b><a href="/'
.'register.php">sign up right now</a></b> to create a new account.'
=> '',

'User name: '
=> '',

'Password: '
=> '',

'Remember me on this computer'
=> '',

'Forgot your password?'
=> '',

'Edit Ad'
=> '',

'Create An Ad'
=> '',

'Image'
=> '',

'Page'
=> '',

'Orientation'
=> '',

'Display count'
=> '',

'Hit count'
=> '',

'Enable/Disable'
=> '',

'Disable'
=> '',

'Are you sure you want to delete this Ad?'
=> '',

'In this page you can manage ads on your network'
=> '',

'Manage Ads'
=> '',

'Create New Ad'
=> '',

'Enter Title'
=> '',

'Title should not be greater than 30 characters'
=> '',

'Select An Image'
=> '',

'Preferred size'
=> '',

'for side modules and'
=> '',

'for center modules'
=> '',

'Previously Selected Image'
=> '',

'Enter URL'
=> '',

'Or Enter JavaScript(.js code)/ Html code'
=> '',

'Enter Description'
=> '',

'Select Page'
=> '',

'Select a page'
=> '',

'Select Horizontal position'
=> '',

'Select vertical position'
=> '',

'Manage Ad Center'
=> '',

'You do not have permission to manage Ads.'
=> '',

'Select horizontal position'
=> '',

'left'
=> '',

'center'
=> '',

'right'
=> '',

'top'
=> '',

'Edit Textpad'
=> '',

'Create Textpad'
=> '',

'Are you sure you want to delete this Textpad'
=> '',

'Available Textpads'
=> '',

'New Textpad'
=> '',

'In this page you can manage category on your network'
=> '',

'Manage Category'
=> '',

'Select Type'
=> '',

'Options'
=> '',

'Create New Category'
=> '',

'Parent Category (Optional)'
=> '',

'Enter Tilte'
=> '',

'You can upload a gif, jpg, jpeg, png, xpm, bmp, file.'
=> '',

'Maximum size'
=> '',

'Do not upload photos containing cartoons, celebrities, nudity, artwork of '
.'copyrighted images.'
=> '',

'For better result image dimension  should be 36x191'
=> '',

'Select a file to upload'
=> '',

'Enter the destination URL of image'
=> '',

'Image title'
=> '',

'Manage Domain List'
=> '',

'Please press enter after each entry'
=> '',

'Edit Link'
=> '',

'Create A Link'
=> '',

'Caption'
=> '',

'Are you sure you want to delete this link?'
=> '',

'In this page you can manage footer links.'
=> '',

'Manage Footer Links'
=> '',

'Create New Footer Link'
=> '',

'Enter Caption'
=> '',

'Caption should be less than 30 characters.'
=> '',

'Check this, if you want to open link in a different window'
=> '',

'In this page you can manage groups on your network'
=> '',

'Manage Groups'
=> '',

'Manage Profanity List'
=> '',

'Edit question'
=> '',

'Create new question'
=> '',

'select'
=> '',

'Question'
=> '',

'Are you sure you want to delete this?'
=> '',

'In this page you can manage questions for your network\'s users'
=> '',

'Manage Questions'
=> '',

'Set Active Question'
=> '',

'Id'
=> '',

'Points'
=> '',

'Edit activity types or add a new type below'
=> '',

'New'
=> '',

'Manage Ranking points'
=> '',

'\'Title\' and/or \'Type\' filed should not be empty.'
=> '',

'\'Points\' filed should be numeric and not empty.'
=> '',

'Edit Static Page'
=> '',

'Create Static Page'
=> '',

'Page Text'
=> '',

'Are you sure you want to delete this page?'
=> '',

'Manage Static Pages'
=> '',

'Create New Static Page'
=> '',

'Enter Page Text'
=> '',

'Manage TakeATour'
=> '',

'Video URL'
=> '',

'Video description'
=> '',

'Media file has been deleted from album or gallery.'
=> '',

'Author of this content is no longer a member of this group'
=> '',

'Return to %s'
=> '',

'Return to %s\'s gallery'
=> '',

'%s\'s Page'
=> '',

'My Page'
=> '',

'No such content or media file has been deleted from the gallery.'
=> '',

'On this page you can manage all posts you have created.'
=> '',

'All Posts'
=> '',

'Events'
=> '',

'Reviews'
=> '',

'People'
=> 'Peuple',

'Group'
=> '',

'No Content Published.'
=> '',

'Manage Post'
=> '',

'%s Members'
=> '',

'find People'
=> '',

'Member Search'
=> '',

'Folder creation failed. '
=> '',

' is not a valid folder name.'
=> '',

'Folder creation failed. You already have a folder named '
=> '',

'1 message has been deleted successfully'
=> '',

' messages have been deleted successfully'
=> '',

'1 message has been moved to folder '
=> '',

' successfully'
=> '',

' messages have been moved to folder '
=> '',

'Selected message(s) are already in '
=> '',

' folder'
=> '',

'Please select message(s) to move'
=> '',

'There are no messages in this folder.'
=> '',

'No messages matched your search'
=> '',

'Compose message'
=> '',

'Create new folder'
=> '',

'Move to:'
=> '',

'- Select Folder -'
=> '',

'(no folders available)'
=> '',

'Sent To'
=> '',

'To:'
=> '',

'Sender'
=> '',

'Search ...'
=> '',

'Inbox'
=> '',

'Sent'
=> '',

'Conversations View'
=> '',

'Go'
=> '',

'Mailbox'
=> '',

'Search Results'
=> '',

'You can\'t access other user\'s messages.'
=> '',

'Conversations'
=> '',

'Please create a folder to move message(s)'
=> '',

'Back to search results'
=> '',

'Reply'
=> '',

'Forward'
=> '',

'Previous'
=> '',

'Next'
=> '',

'Date:'
=> '',

'From:'
=> '',

'Subject:'
=> '',

'In this page you can view Email Addresses of all users'
=> '',

'All Users'
=> '',

'Most Active Users'
=> '',

'Dormant Users'
=> '',

'Email Addresses'
=> '',

'Total Points'
=> '',

'In this page you can view stats about system usage'
=> '',

'Registered Users'
=> '',

'Number of blog post'
=> '',

'Number of Images'
=> '',

'Profile Views'
=> '',

'Maximum'
=> '',

'Minimum'
=> '',

'Average'
=> '',

'Profile Visited by User'
=> '',

'Relations Statistics'
=> '',

'Number of Users by Email Domain:'
=> '',

'Domain Name'
=> '',

'Number of Users'
=> '',

'MIS Reports'
=> '',

'member'
=> '',

'You haven\'t <a href="%s">created</a> or <a href="%s">joined</a> any '
.'families yet.'
=> '',

'User has not joined any family yet.'
=> '',

'Families'
=> '',

'My Families'
=> '',

'My Groups'
=> '',

'You haven\'t <a href="%s">created</a> or <a href="%s">joined</a> any '
.'groups yet.'
=> '',

'User has not joined any groups yet.'
=> '',

'My Links'
=> '',

'No links under this category'
=> '',

'No links have been added. Click <a href="%s">here</a> to add links.'
=> '',

'No links have been added'
=> '',

'My Networks'
=> '',

'No network joined yet.'
=> '',

'Use this tool to send announcements to all registered network members'
=> '',

'Message/post'
=> '',

'Destination'
=> '',

'Deliver message to all registered members by internal mail'
=> '',

'Email message to all network members'
=> '',

'Post message to network home page community blog'
=> '',

'Send to me only'
=> '',

'Manage Network Bulletins'
=> '',

'Email Notifications'
=> '',

'Notify network operator (me) when'
=> '',

'Registered members receive notifications when'
=> '',

'via their registered email'
=> '',

'via their account inbox'
=> '',

'User settable'
=> '',

'Blink Messages Waiting:'
=> '',

'messages  waiting blinks in network member\'s toolbar when new messages arrive'
=> '',

'Update All Current Users'
=> '',

'Save changes'
=> '',

'Restore Defaults'
=> '',

'Load / restore User Account Defaults from local disk'
=> '',

'Load User Account Defaults'
=> '',

'Save Relationship'
=> '',

'Network Address'
=> '',

'Network address will be part of the URL of your network, e.g. <code>http://'
.'<b>abc</b>.%s/</code>. It should be less than 10 characters.'
=> '',

'Check Availability'
=> '',

'Network Title/Heading'
=> '',

'Title appears on network pages.  For best results, keep below 60 characters '
.'(max 100 characters).'
=> '',

'Network Sub Title'
=> '',

'The sub-title will be displayed below the Network Title.'
=> '',

'Network Category'
=> '',

'This category is used to organise the Network Directory.'
=> '',

'Network Description'
=> '',

'A short paragraph or two describing your network.'
=> '',

'Default Network Language'
=> '',

'Select the Network default language'
=> '',

'Community Blog Title'
=> '',

'The Network group title will be displayed on the homepage.'
=> '',

'Network Icon'
=> '',

'The icon will appear in the network listing.'
=> '',

'Current Icon'
=> '',

'Ideal size 70 x 60 pixels'
=> '',

'Check if content moderation is required.'
=> '',

'Check if People page should only show users with a profile photo.'
=> '',

'Check if you want to enable the languages menu bar.'
=> '',

'Check if top menu bar is not required.'
=> '',

'Check if reciprocated relationships are required.'
=> '',

'Check if email address validation is required.'
=> '',

'Check if CAPTCHA is required during registration.'
=> '',

'Reciprocated relationships are required.'
=> '',

'Reciprocated relationships are not required.'
=> '',

'Email address validation is required.'
=> '',

'Email address validation is not required.'
=> '',

'CAPTCHA is required during registration.'
=> '',

'CAPTCHA is not required during registration.'
=> '',

'Load / restore General Network Settings from local disk'
=> '',

'Load General Settings'
=> '',

'Upload / Download network default settings for this network'
=> '',

'Select XML configuration file for upload.'
=> '',

'Download default settings file'
=> '',

'Upload new default settings file'
=> '',

'New User Account Defaults'
=> '',

'Network friends'
=> '',

'I appear as a friend in all new accounts'
=> '',

'These users appear as friends in all new accounts.'
=> '',

'(enter screen names of registered network users, separated by commas)'
=> '',

'Current default desktop image'
=> '',

'(Images 1016 pixels wide by 191 pixels tall will have the best results)'
=> '',

'Upload default desktop image'
=> '',

'Set desktop image turn on/off'
=> '',

'Media Gallery Images'
=> '',

'Select an image album(s) from your gallery to include in new user default '
.'galleries. (An album in your gallery may contain one or more images.)'
=> '',

'Upload to gallery now'
=> '',

'For multiple selections hold down the &lt;Ctrl&gt;key PC or the &lt;'
.'Command&gt; key(Mac) while clicking the desired selections.'
=> '',

'Media Gallery Audio'
=> '',

'Select an audio album(s) from your gallery to include in new user default '
.'galleries. (An album in your gallery may contain one or more audio clips.)'
=> '',

'Media Gallery Video'
=> '',

'Default Blog'
=> '',

'Select a post to include in new user default.'
=> '',

'Save Settings'
=> '',

'Network Default Links'
=> '',

'No links have been added.'
=> '',

'Multiple networks are disabled - please configure your system for network '
.'operation.'
=> '',

'The current featured network is: <a href="%s">%s</a>'
=> '',

'Select a featured network:'
=> '',

'Select a network'
=> '',

'Featured Network'
=> '',

'Configure'
=> '',

'System Settings'
=> '',

'Configuration manager'
=> '',

'PA Defender'
=> '',

'Network Settings'
=> '',

'Network settings'
=> '',

'Ad Center'
=> '',

'Textpads'
=> '',

'Manage Textpads'
=> '',

'Meta network'
=> '',

'Set featured network'
=> '',

'Manage emblems'
=> '',

'Manage splash'
=> '',

'Info Boxes'
=> '',

'Network of Moment'
=> '',

'Showcase Modules'
=> '',

'Video Tours'
=> '',

'Server Announcement'
=> '',

'Survey'
=> '',

'Create Survey'
=> '',

'Select Survey'
=> '',

'Register Today'
=> '',

'Take a Tour Video'
=> '',

'Usage'
=> '',

'Counts'
=> '',

'Marketing reports'
=> '',

'Themes'
=> '',

'Theme selector'
=> '',

'Module selector'
=> '',

'Background image'
=> '',

'Header image'
=> '',

'Customize theme'
=> '',

'User defaults'
=> '',

'Default settings'
=> '',

'Relationship settings'
=> '',

'Users Settings'
=> '',

'Create users'
=> '',

'Manage users'
=> '',

'Moderate users'
=> '',

'Moderate contents'
=> '',

'Manage contents'
=> '',

'Manage comments'
=> '',

'Manage links'
=> '',

'Network links'
=> '',

'Manage Profanity'
=> '',

'Profane Word List'
=> '',

'Manage Signup Access'
=> '',

'Manage Domain Names'
=> '',

'Manage Events'
=> '',

'Network Events'
=> '',

'Bulletins'
=> '',

'Email notifications'
=> '',

'Roles'
=> '',

'Manage Roles & Tasks'
=> '',

'Manage Tasks Relationship'
=> '',

'Static Pages'
=> '',

'Manage Network Links'
=> '',

'No Link Categories'
=> '',

'Manage Links'
=> '',

'Link Name'
=> '',

'Link'
=> '',

'Manage Network Content'
=> '',

'Search Posts'
=> '',

'Browse Months'
=> '',

'Search'
=> 'Rechercher',

'Network Operator Controls'
=> '',

'In this page you can manage users registered on your network'
=> '',

'Search Registered Users'
=> '',

'Manage Users'
=> '',

'Moderate content on your network.'
=> '',

'No Content For Moderation.'
=> '',

'In this page you can moderate users registered on your network'
=> '',

'Picture'
=> '',

'Registered'
=> '',

'Action'
=> '',

'No User.'
=> '',

'Moderate Users'
=> '',

'Manage content on your network.'
=> '',

'Search posts'
=> '',

'Browse months'
=> '',

'Comments'
=> '',

'Are you sure you want to delete this content?'
=> '',

'No Content.'
=> '',

'Manage Content'
=> '',

'Manage users registered on your network'
=> '',

'Are you sure you want to delete this user?'
=> '',

'pending'
=> '',

'Assign Role'
=> '',

'Selected'
=> '',

'Are you sure?'
=> '',

'(un)check all'
=> '',

'No users'
=> '',

'No networks in this category'
=> '',

'Size'
=> '',

'Network Directory'
=> 'Directoire de réseaux',

'Search Networks'
=> '',

'No networks found'
=> '',

'Network Statistics'
=> '',

'Newest %s'
=> '',

'Networks'
=> '',

'Largest Network'
=> '',

'No network created yet.'
=> '',

'Provide a login name, email address and basic information for a new network '
.'member.'
=> '',

'Upon hitting the create button, the new member will be emailed a greeting '
.'including an auto-generated password.'
=> '',

'Fields marked with an asterisk (*) are mandatory.'
=> '',

'Email address'
=> '',

'Photo/avatar'
=> '',

'Auto-generate new password for network member'
=> '',

'Manual password'
=> '',

'modify greeting if desired and click the create user button below tocomplete '
.'process'
=> '',

'Hi,'
=> '',

'I\'ve created my own place on PeopleAggregator and I\'d like you to'
=> '',

'connect to me so we can stay in touch.'
=> '',

'You can view my blog, my reviews, my ratings, my photos, my lists -'
=> '',

'and all sorts of things that matter to me.'
=> '',

'You can create a personal page and blog of your own, which will be'
=> '',

'linked to mine.'
=> '',

'That way you\'ll always know when I post something new!'
=> '',

'Create User'
=> '',

'Location'
=> '',

'no data'
=> '',

'Age'
=> '',

'Add as'
=> '',

'Advanced Search'
=> '',

'Simple Search'
=> '',

'Recent Users'
=> '',

' with picture in profile'
=> '',

'Select rows'
=> '',

'Find Users'
=> '',

'Male'
=> '',

'Female'
=> '',

'Any'
=> '',

'Company Name'
=> '',

'Interests'
=> '',

'College'
=> '',

'Cusines'
=> '',

'Shout-out'
=> '',

'Click here to add your Shout-out.'
=> '',

'Please, select a family member that you wish to assign points'
=> '',

'Date: '
=> '',

'No entries.'
=> '',

'or click here to add a new'
=> '',

'Rating Points'
=> '',

'Place'
=> '',

'Related Media'
=> '',

'Click here to upload'
=> '',

'%s Points Directory'
=> '',

'%s Points'
=> '',

'Points for %s'
=> '',

'Search results for \'%s\' Category'
=> '',

'Add Points'
=> '',

'Edit Points'
=> '',

'You do not have permission for this action!'
=> '',

'Points Entity not found!'
=> '',

'Points sucessfully deleted.'
=> '',

'Points data sucessfully stored'
=> '',

'Survey Archive'
=> '',

'Answer'
=> '',

'See all recent Surveys'
=> '',

'Most Popular Tags'
=> '',

'Nothing has been tagged yet.'
=> '',

'Attach Media'
=> '',

'Add Image or Video'
=> '',

'Separate tags with commas'
=> '',

'edit your post'
=> '',

'create your post'
=> '',

'Routing'
=> '',

'Community Blog'
=> 'Blogue de communauté',

'Post to %s (On this networks home page)'
=> '',

'You can route this post to one or many destinations with the selectors below.'
=> '',

'Please note that routing does not post to private groups'
=> '',

'Post to community Blog (On this networks home page)'
=> '',

'Send to selected group blogs'
=> '',

'Send to selected external blogs'
=> '',

'Select albums in your media gallery to send to'
=> '',

'Select none of my galleries'
=> '',

'Select all of my galleries'
=> '',

'No Albums'
=> '',

'Or, create a new album in your media gallery'
=> '',

'The post you are composing will be lost if you continue, are you sure you '
.'want to leave  without saving?'
=> '',

'Add Blog Post'
=> '',

'Default Image Album'
=> '',

'Default Audio Album'
=> '',

'Default Video Album'
=> '',

'Blogs'
=> '',

'Question of the Day'
=> '',

'Site Ranking'
=> '',

'Recent Comments'
=> '',

'My Friend\'s Comments'
=> '',

'No title'
=> '',

'No comments posted yet.'
=> '',

'Recent Posts'
=> '',

'No contents in blog.  <a href="%s">Click here to make a post</a>!'
=> '',

'Browse Tags'
=> '',

'Nothing has been tagged yet'
=> '',

'Welcome to %s!'
=> '',

'With your %s account you will be able to:'
=> '',

'Edit, share and store all your digital stuff in one place.'
=> '',

'Manage all your friends, groups and content.'
=> '',

'Unite your online life by connecting all your presences together.'
=> '',

'Provide the following information to join and start connecting all your '
.'digital worlds!'
=> '',

'%s\'s friends'
=> '',

'My friends'
=> '',

'Friends'
=> '',

'No friends made yet.'
=> '',

'Send request to join this network'
=> '',

'Your request to join this network could not be sent due to following reason: '
.'%s. You can go back to the home network by clicking Return to home network'
=> '',

'Your request to join this network has been successfully sent to the '
.'moderator of this network. The Moderator will check this request and approve '
.'or deny the request. You can go back to mother network by clicking the '
.'button Return to home network'
=> '',

'Return to home network successfully.'
=> '',

'Request Message'
=> '',

'Welcome to PeopleAggregator'
=> '',

'This is a private network'
=> '',

'You need to be member of this network to do anything. You can send a request '
.'to join this network by clicking \'Request to join\'.'
=> '',

'Return to home network'
=> 'Acceuil',

'In this page you can manage different admin roles'
=> '',

'Sr.No.'
=> '',

'No roles have been created yet.'
=> '',

'Add New Role'
=> '',

'Load / restore Roles Settings from local disk'
=> '',

'Load Roles Settings'
=> '',

'Manage Roles'
=> '',

'Invalid configuration file format. Configuration file should be a valid XML '
.'file. '
=> '',

'Roles settings successfully loaded from '
=> '',

' file.'
=> '',

'Please, select a valid XML configuration file.'
=> '',

'Role data sucessfully updated.'
=> '',

'New Role sucessfully created.'
=> '',

'Role sucessfully deleted.'
=> '',

'This Role can\'t be deleted.'
=> '',

'Select Task(s) you want to assign to this Role and press left/right arrow.'
=> '',

'Default Roles settings sucessfully restored.'
=> '',

'There is no Roles data in default XML settings file.'
=> '',

'Tag Search'
=> '',

'Search Terms'
=> '',

'all of these words'
=> '',

'this exact phrase'
=> '',

'any of these words'
=> '',

'none of these words'
=> '',

'Date Range'
=> '',

'Start Date'
=> '',

'End Date'
=> '',

'Search Content'
=> '',

'Poll Topic'
=> '',

'Number Of Options'
=> '',

'Select Any One Topic'
=> '',

'No poll was created yet.'
=> '',

'Poll has been deleted successfully.'
=> '',

'Poll has been saved successfully.'
=> '',

'Poll has been created successfully.'
=> '',

'Announcements'
=> '',

'ShowCase'
=> '',

'Contents'
=> '',

'Date range selected is invalid. Please, select a valid date range.'
=> '',

'Please enter either data or date to search'
=> '',

'%s\'s Group Blog'
=> '',

'Manage posts'
=> '',

'Return to private page'
=> '',

'Showing results for tag %s.'
=> '',

'Moderate'
=> '',

'Manage content'
=> '',

'Join this group'
=> '',

'No items match your search criteria.'
=> '',

'Back'
=> '',

'Click <a href="%s">here</a> to add content.'
=> '',

'You will be redirected in '
=> '',

' seconds, or you can click here to redirect now'
=> '',

'An Error Has Occurred'
=> '',

'Error details'
=> '',

'Information'
=> '',

'Please confirm action'
=> '',

'Warning!'
=> '',

'No Testimonial Found'
=> '',

'Testimonials'
=> '',

'New Testimonials'
=> '',

'Click here to submit a Testimonial'
=> '',

'Testimonials for '
=> '',

'Comment rejected by spam filter'
=> '',

'Comment can\'t be empty.'
=> '',

'Show Splash Page'
=> '',

'If this checkbox is checked then Splash Page will be the first page to be '
.'shown to the anonymous users otherwise Homepage will be the first page'
=> '',

'Info for: '
=> '',

'Info URL'
=> '',

'Paste the complete URL of the network here'
=> '',

'Info Image'
=> '',

'No image selected.'
=> '',

'Upload Image'
=> '',

'Uploaded images will be displayed at 145 pixels by 145 pixels.'
=> '',

'Set Info Boxes'
=> '',

'Network URL'
=> '',

'Network of the Moment Image'
=> '',

'Uploaded image will be displayed at 193 pixels by 67 pixels'
=> '',

'Save Network of the Moment'
=> '',

'Uploaded image will be displayed at 193 pixels by 67 pixels.'
=> '',

'Uploaded image will be displayed at 185 pixels by 110 pixels.'
=> '',

'Save Announcement'
=> '',

'Featured User'
=> '',

'Featured Group ID'
=> '',

'Featured Video Link'
=> '',

'Featured Business ID'
=> '',

'Save Showcase Module'
=> '',

'Showcased Network '
=> '',

'Showcased Network URL'
=> '',

'Showcased Network Image'
=> '',

'Set Showcased Networks'
=> '',

'Showcase Module'
=> '',

'Video Tours Image'
=> '',

'Save Video Tour'
=> '',

'Click here to watch the video'
=> '',

'Take A Tour'
=> '',

'In this page you can assign roles to tasks'
=> '',

'No roles have been created yet'
=> '',

'Assign Roles to Tasks'
=> '',

'Terms and conditions for using'
=> '',

'There are %s entries in this directory.'
=> '',

'Master Directory'
=> '',

'%s directory'
=> '',

'There is no TypedEntity associated with this Group yet. Would you like to '
.'create one?'
=> '',

'--- Please select ---'
=> '',

'Create it'
=> '',

'Typed Group Settings'
=> '',

'Request to join this group as'
=> '',

'Join This Group as'
=> '',

'You can upload an audio file'
=> '',

'Audio title'
=> '',

'You can upload a gif, jpg, jpeg, png, xpm or bmp file'
=> '',

'Do not upload photos containing cartoons, celebrities, nudity, artwork or '
.'copyrighted images'
=> '',

'Upload image'
=> '',

'Select who can see this image'
=> '',

'Tags (separate with commas)'
=> '',

'Add More'
=> '',

'Or finish below'
=> '',

'Upload audio'
=> '',

'You can upload a video file'
=> '',

'Video title'
=> '',

'Upload video'
=> '',

'Select a file to upload, or enter a URL below'
=> '',

'Audio URL'
=> '',

'Select who can listen to this Audio'
=> '',

'Send to album'
=> '',

'Or create new album'
=> '',

'Image URL'
=> '',

'Unkonwn type selected'
=> '',

'LinkedIn Contacts: '
=> '',

'No contacts'
=> '',

'MS Live Contacts: '
=> '',

'Contacts'
=> '',

'Import'
=> '',

'Outlook Contacts: '
=> '',

'Plaxo Contacts: '
=> '',

' contact(s) sucessfully imported'
=> '',

'Invalid file type. Please select a valid LinkedIn CSV file. '
=> '',

'Please, select a valid LinkedIn CSV file.'
=> '',

'Invalid file type. Please select a valid Outlook CSV file. '
=> '',

'Please, select a valid Outlook CSV file.'
=> '',

'Invite message can\'t be empty.'
=> '',

'Please, select one or more contacts.'
=> '',

' contact(s) sucessfully deleted.'
=> '',

'General'
=> '',

'Other'
=> '',

'No details.'
=> '',

'Messages'
=> '',

'Photo'
=> '',

'No Videos'
=> '',

'No Video'
=> '',

'Are you sure you want to delete this video'
=> '',

'View all Members'
=> '',

'View all '
=> '',

'View All %s Members'
=> '',

'Polls'
=> '',

'No previous poll to display'
=> '',

'No votes are posted for this poll'
=> '',

'Edit Events'
=> '',

'My Events'
=> '',

'Email Messages settings data successfully loaded from '
=> '',

'Email message settings successfully restored.'
=> '',

'Network URL cannot be left empty for showcased network '
=> '',

' For showcased network '
=> '',

'No caption given to network of moment'
=> '',

'Please provide URL for network of moment'
=> '',

'No video URL provided for video tours'
=> '',

'No description provided for network of moment'
=> '',

' For network of moment, '
=> '',

'Configure Splash Page'
=> '',

'You need to be member of this group to view the contents'
=> '',

'Networks are disabled.'
=> '',

'Network spawning disabled.'
=> '',

'Create Network - %s'
=> '',

'There was a problem:<br>No message(s) selected. Please select at least one '
.'message and try again.'
=> '',

'There was a problem:'
=> '',

'No folder selected. Please select a folder and try again.'
=> '',

'No message(s) selected. Please select at least one message and try again.'
=> '',

'%s - %s'
=> '',

'page_name'
=> '',

' updated successfully'
=> '',

'%s - Edit your profile - %s'
=> '',

'Sorry! you are not authorized to view content of this page'
=> '',

'File '
=> '',

' loaded successfully.'
=> '',

'Click "Save" button to save new settings.'
=> '',

'Default settings sucessfully restored.'
=> '',

'User default Notifications Settings successfully updated.'
=> '',

'%s Events'
=> '',

'Data mapping error. Invalid data format.'
=> '',

'-no email address-'
=> '',

'Current %s'
=> '',

'Current Logo'
=> '',

'Upload %s'
=> '',

'Your file is too large for the web server.  The largest file you can upload '
.'here is %.1fM.  If this is too small, please ask the administrator to '
.'increase the <code>upload_max_filesize</code> directive in <code>php.ini</'
.'code>.'
=> '',

'The uploaded file was only partially uploaded.'
=> '',

'No file was uploaded'
=> '',

'File %s not uploaded correctly.'
=> '',

'File is not uploaded correctly.'
=> '',

'File too large; %s file uploads are limited to %s.  If this is too small, '
.'please ask the administrator to increase the limit.'
=> '',

'Invalid image file.'
=> '',

'Invalid media file.'
=> '',

'Invalid document type - supported formats are: %s'
=> '',

'File error: File already exists'
=> '',

'Security error: File %s is not an uploaded file:'
=> '',

'XML parsing error!'
=> '',

'Data not found or XML parsing error!'
=> '',

'Can\'t get data from URL. Please, check the given URL.'
=> '',

'Can\'t open file \''
=> '',

'File'
=> '',

'doesn\'t exist.'
=> '',

'No data! Check if file is empty.'
=> '',

'Network directory'
=> 'Directoire de réseaux',

'JOIN Network'
=> '',

'Unjoin Network'
=> '',

'Create a network'
=> 'Créer un réseau',

'Home'
=> 'Acceuil',

'Orgs'
=> '',

'Neighbors'
=> '',

'My Widgets'
=> '',

'My Messages'
=> '',

'My Friends'
=> '',

'My Forum'
=> '',

'My Points'
=> '',

'My Family'
=> '',

'Edit My Account'
=> '',

'Find %s'
=> '',

'Friends gallery'
=> '',

'Family Homepage'
=> '',

'Create'
=> '',

'%s Home'
=> '',

'%s Forum'
=> '',

'%s Gallery'
=> '',

'Join'
=> '',

'Unjoin'
=> '',

'Are you sure you want to delete this group'
=> '',

'Email Notification'
=> '',

'Set Feature Network'
=> '',

'Manage Emblem'
=> '',

'Personalized Video'
=> '',

'Top Bar Enable/Disable'
=> '',

'User Defaults'
=> '',

'Relationships'
=> '',

'Manage Contents'
=> '',

'Customize UI'
=> '',

'Home Page'
=> '',

'User Default Page'
=> '',

'Group Directory Page'
=> '',

'Network Directory Page'
=> '',

'Send a message'
=> '',

'Change Relation'
=> '',

'Delete as %s'
=> '',

'Are you sure you want to delete this Relationship?'
=> '',

'Add as %s'
=> '',

'%s function expects string as first argument.'
=> '',

'Malicious or unauthorized activities detected. If you think this is an '
.'error, '
=> '',

'First'
=> '',

'Last'
=> '',

'Could not retrieve file from URL: %s'
=> '',

'User ID or Password field can\'t be blank.'
=> '',

'Invalid or missing SOAP XML file'
=> '',

'Invalid response received from'
=> '',

'Invalid XML response received from'
=> '',

'BinarySecurityToken not found in XML response received from'
=> '',

'Can\'t estabilish WEB connection.'
=> '',

'Unknown communication error has occured.'
=> '',

'Communication error - no response received.'
=> '',

'AdrBook: Invalid response received from'
=> '',

'no name'
=> '',

'no email'
=> '',

'Plaxo data parser error.'
=> '',

'Invalid Plaxo Header received.'
=> '',

'Unable to get list of the Plaxo folders.'
=> '',

'Unable to read the Plaxo folders.'
=> '',

'Sorry - you are not logged in or you have been logged out due to inactivity. '
.'Please, log in again.'
=> '',

'Myself'
=> '',

'Everyone'
=> '',

'Friends Only'
=> '',

'In Family'
=> '',

'Network name'
=> '',

'Network address'
=> '',

'Network tagline'
=> '',

'Group name'
=> '',

'Group description'
=> '',

'Group tag'
=> '',

'Select age'
=> '',

'Under 10 years'
=> '',

'11-20 years'
=> '',

'21-30 years'
=> '',

'31-40 years'
=> '',

'41-50 years'
=> '',

'Over 50 years'
=> '',

'Create Post'
=> '',

'Messages '
=> '',

'Edit my account'
=> '',

'Tags:'
=> '',

'Installer will perform now a series of tests to determine the working '
.'environment of the server and the minimum conditions for a successful '
.'installation. Please do not interrupt this step of the installation process.'
=> '',

'Please wait...'
=> '',

'Please complete the following information to create an admin account.'
=> '',

'Admin username'
=> '',

'Admin password'
=> '',

'Admin email'
=> '',

'Invalid or empty user name.'
=> '',

'Your password must be at least %d characters long.'
=> '',

'Your password can not be longer than %d characters.'
=> '',

'Invalid or empty email field.'
=> '',

'Administrator account data sucessfully stored. Click \'Next\' please...'
=> '',

'Please complete the following information if you have already created a '
.'database for People Aggregator application.'
=> '',

'or you can provide bellow MySQL root username/password and People Aggregator '
.'will create a database for you.'
=> '',

'MySQL root username'
=> '',

'MySQL root password'
=> '',

'Please wait, trying to connect to the database.'
=> '',

'Creating the Database'
=> '',

'Congratulations!'
=> '',

'%s - My Links - %s'
=> '',

'Group deleted successfully'
=> '',

'%s groups deleted successfully'
=> '',

'Question is set for all users'
=> '',

'Please select a question to activate.'
=> '',

'Question has been successfully saved'
=> '',

'Fields marked with * must not be left empty'
=> '',

'Question has been deleted successfully'
=> '',

'Caption has already been taken, please enter a different caption'
=> '',

'Successfully updated'
=> '',

' is already enabled at specified orientation'
=> '',

'Please select atleast one user.'
=> '',

'Status of selected user(s) updated successfully'
=> '',

'An error has occured on deleting users.'
=> '',

' uploaded successfully.'
=> '',

'Please confirm network deletion by selecting deletion checkbox.'
=> '',

'Network Statistics - %s'
=> '',

'General Network Settings'
=> '',

'Administration panel'
=> '',

'Following relations could not be added as default relation '
=> '',

'Default settings for the network has been saved'
=> '',

'Click "Save" button to store new settings.'
=> '',

'Date range selected is invalid, so it has been ignored in searching'
=> '',

'Your comment contains some illegal characters. Please try again.'
=> '',

'Comment can not be left blank'
=> '',

'Sorry, your comment cannot be posted as it looks like spam. Try removing any '
.'links to possibly suspect sites, and re-submitting.'
=> '',

'Your comment has been posted successfully'
=> '',

'Sorry, your comment cannot be posted as it was classified as spam by '
.'Akismet, or contained links to blacklisted sites.  Please check the links in '
.'your post, and that your name and e-mail address are correct.'
=> '',

'Sorry, your comment cannot be posted as it was classified as spam by '
.'Akismet, or contained links to blacklisted sites. Please check the links in '
.'your post, and that your name and e-mail address are correct.'
=> '',

'Terms and Conditions - %s'
=> '',

'basecamp test disabled'
=> '',

'please enter your basecamp login details above.'
=> '',

'scraping contacts page to get companies'
=> '',

'getting list of people from company '
=> '',

' who are working on this project'
=> '',

'testing ImageResize module with engine'
=> '',

'make sure to hit ctrl-F5 after clicking, to clear the cache'
=> '',

'flushing cache'
=> '',

'done'
=> '',

'expanding and cropping 135x75 to fit inside 300x300'
=> '',

'reduce only'
=> '',

'fitting 135x75 inside 300x300'
=> '',

'reduce only, smaller'
=> '',

'Report abuse'
=> '',

'Comment'
=> '',

'Submit Abuse'
=> '',

'Right-click to download'
=> '',

'Overall Rating'
=> '',

'Your Rating'
=> '',

'Please'
=> '',

'log in'
=> '',

'to rate this audio'
=> '',

'to rate this post'
=> '',

'Are you sure you want  to post the comment?'
=> '',

'Leave a Comment'
=> '',

'Submit Comment'
=> '',

'Are you sure you want to post the comment?'
=> '',

'posted by %s on %s'
=> '',

'permalink'
=> '',

'comments'
=> '',

'Unknown error.'
=> '',

'Detailed information has been written into the error log.'
=> '',

'Begins'
=> '',

'Click here to go back to the Home page'
=> '',

'&copy; %s Broadband Mechanics, Inc.'
=> '',

'Already a member?'
=> '',

'Login now'
=> '',

'or'
=> '',

'Register'
=> 'Enregistrer',

'shortcuts'
=> '',

'logoff'
=> '',

'to rate this image'
=> '',

'Network is temporarily closed. We apologize for any inconvenience and thank '
.'you for your patience as we improve the system. Please try after some time. '
.'Currently, only site administrator can login.'
=> '',

'view all'
=> '',

'%s Networks'
=> '',

'to rate this video'
=> '',

'Showing profile fields in sidebar widget.'
=> '',

'peopleaggregator: widgetization testbench'
=> '',

'Select a module'
=> '',

'Module'
=> '',

'Request'
=> '',

'Response'
=> '',

'Rendered response'
=> '',

'An unknown error occurred - no response available.'
=> '',

'Note: do not enable widgetization on public facing webservers as it allows '
.'operations to be performed as arbitrary users! Access must be restricted to '
.'trusted front-end systems.'
=> '',

'This file may not be called directly.'
=> '',

'No admininstrator password configured'
=> '',

'To use the updater, add a line like this to'
=> '',

'Log in'
=> '',

'All the files have been updated. Now you need to'
=> '',

'click here to update the database'
=> '',

'and the update will be complete'
=> '',

'Error occurred running database update:'
=> '',

'PeopleAggregator system update'
=> '',

'%s - Media Gallery - %s'
=> '',

'View All Members'
=> '',

'View All Group Members'
=> '',

'Comment can not be empty'
=> '',

'Please login to comment'
=> '',

'Your Recommendation: '
=> '',

'Error processing request'
=> '',

'Error parsing URL'
=> '',

'Ad Title can not have empty.'
=> '',

'Ad Target page is not specified.'
=> '',

'attributes'
=> '',

'middle'
=> '',

'Date Established'
=> '',

'Postal Code'
=> '',

'Phone Number'
=> '',

'Honors / Awards'
=> '',

'Supporter'
=> '',

'Customer'
=> '',

'Employee'
=> '',

'Religion / Faith'
=> '',

'Congregational member'
=> '',

'Church member'
=> '',

'Church goer'
=> '',

'Date the Family was formed'
=> '',

'City of Origin'
=> '',

'Grand Parent'
=> '',

'Relative'
=> '',

'Child'
=> '',

'owner'
=> '',

'admin'
=> '',

'banned'
=> '',

'limited'
=> '',

'Group moderation'
=> '',

'My messages'
=> '',

'Cannot create networks: this installation is not configured for network '
.'operation.'
=> '',

'Cannot create networks: %s is not writable'
=> '',

'Cannot create networks: Network spawning has been disabled on this '
.'installation.'
=> '',

'Files with extension \'%s\' may not be uploaded'
=> '',

'Unable to determine image type'
=> '',

'File MIME type is %s, expected %s'
=> '',

'E-mail address is not valid.'
=> '',

'The domain of your E-mail address is not in the list of allowed domains.'
=> '',

'\n'
.'The password must be less than %d characters.'
=> '',

'\n'
.'The password must be longer than %d characters.'
=> '',

'Latest posts from %s'
=> '',

'Newest posts from everyone on %s'
=> '',

'%s: %s blog'
=> '',

'Failed to retrieve %s: %s'
=> '',

);

?>