<?php

// This file is automatically generated from messages.po.  Do not edit it!

$TRANSLATED_STRINGS = array(

'Create Group'
=> 'Gruppe erstellen',

'Edit Group'
=> 'Gruppe bearbeiten',

'Message sent successfully to '
=> 'Nachricht erfolgreich gesendet',

'Last Login'
=> 'Zuletzt eingeloggt',

'Latest Registered'
=> 'Neueste Registrierung',

'Select any %s file to upload'
=> 'Wähle ine %s Datein zum Hochladen',

'You have to login before uploading a %s'
=> 'Du musst eingeloggt sein um eine %s Datei hochzuladen',

'Blog Feed sucessfully deleted.'
=> '',

'Role can\'t be deleted.'
=> '',

'Successfully deleted.'
=> '',

'Not found'
=> '',

'Please enter a valid URL!'
=> '',

'Please, select one of the following Professional profiles: '
=> '',

'Please, select the XFN relations you want to import: '
=> '',

'Sorry, we couldn\'t any identity informations '
=> '',

'at: '
=> '',

'in your HTML text.'
=> '',

'Please, select contacts you want to import.'
=> '',

'We haven\'t found any contacts on your Plaxo account.'
=> '',

'Username and/or password field can\'t be empty!'
=> '',

'Apply to User pages'
=> '',

'Apply to this Network'
=> '',

'Apply to '
=> '',

' group'
=> '',

'Tasks/Permissions'
=> '',

'Edit/Assign Role for user: '
=> '',

'Select roles you want to associate with this user and press left/right '
.'arrow, <br />'
=> '',

'We haven\'t found any contacts on your MSLive account.'
=> '',

'Recently Created'
=> '',

'Recently Modified'
=> '',

'Largest Group'
=> '',

'Answer can not be left blank'
=> '',

'Sorry, your Answer cannot be posted as it looks like spam. Try removing any '
.'links to possibly suspect sites, and re-submitting.'
=> '',

'Your Answer has been posted successfully'
=> '',

'Sorry, your answer cannot be posted as it was classified as spam by Akismet, '
.'or contained links to blacklisted sites. Please check the links in your '
.'post, and that your name and e-mail address are correct.'
=> '',

'This section is disabled. Click the checkbox above to show it in your '
.'sidebar widget.'
=> '',

'click to include'
=> '',

'Design your sidebar widget'
=> '',

'Rename this widget'
=> '',

'Rename'
=> '',

'Or'
=> '',

'Delete this widget'
=> '',

'Are you sure you wish to delete this widget?'
=> '',

'Preview'
=> '',

'%s - My Widgets - %s'
=> '',

'About Me'
=> 'Über mich',

'About'
=> 'Über',

'User image.'
=> 'Nutzerbild',

'More Detail'
=> 'Details',

'Sex'
=> 'Geschlecht',

'Date of birth'
=> 'Geburtsdatum',

'State'
=> 'Bundesland',

'City'
=> 'Stadt',

'ZIP code'
=> 'PLZ',

'Country'
=> 'Land',

'Blog'
=> '',

'Flickr'
=> '',

'Delicious'
=> '',

'User Tags (Interests)'
=> '',

'No details entered yet.'
=> 'Noch keine Details eingegeben.',

'Professional'
=> '',

'Headline'
=> '',

'Industry'
=> 'Branche',

'Company'
=> '',

'Title'
=> 'Titel',

'Website'
=> '',

'Career skill'
=> '',

'Prior Company'
=> '',

'Degree'
=> '',

'Languages'
=> '',

'Awards'
=> '',

'Summary'
=> '',

'Download CV'
=> '',

'Download'
=> '',

'Personal'
=> '',

'Ethnicity'
=> '',

'Religion'
=> '',

'Political view'
=> '',

'Passion'
=> '',

'Activities'
=> '',

'Books'
=> 'Literatur',

'Movies'
=> 'Filme',

'Music'
=> 'Musik',

'Cuisines'
=> '',

'TV shows'
=> '',

'Actions'
=> 'Aktionen',

'Activity Feed'
=> 'Aktivität',

'My Activity Feeds'
=> 'Meine Aktivitäten',

'Activity Feeds'
=> 'Aktivitäten',

'Change Group Settings'
=> '',

'File upload error: '
=> '',

'Please supply a name.'
=> '',

'Group Name'
=> 'Gruppen Name',

'Group Category'
=> 'Gruppen Kategorie',

'Tags'
=> 'Stichwörter',

'separated tags with commas'
=> 'Stichwörter mit Komma trennen',

'Group Photo'
=> 'Gruppen Foto',

'Choose File'
=> 'Datei auswählen',

'Current Photo'
=> 'Derzeitiges Foto',

'Group Description'
=> 'Gruppen Beschreibung',

'Registration Type'
=> '',

'Open'
=> '',

'Moderated'
=> '',

'Invite Only'
=> '',

'Submit'
=> 'Abschicken',

'Entity Type'
=> '',

'Compose'
=> '',

'Message sent successfully to %s'
=> '',

'Message sending failed for %s  as user(s) doesn\'t exist'
=> '',

'Send'
=> 'Senden',

'Message composed will be discarded. Do you want to continue?'
=> 'Erstellte Nachricht wird verworfen, ist das ok?',

'To'
=> 'An',

'select friend'
=> 'Freund auswählen',

'Note: to address a message to a user who is not your friend, please visit '
.'their public page and click \'send message\'.'
=> '',

'Subject'
=> 'Betreff',

'Message'
=> 'Nachricht',

'Cancel'
=> 'Abbrechen',

'You have not created any folders.'
=> 'Sie haben noch keine Ordner erstellt.',

'Write Comment for '
=> '',

'\'s Answers'
=> '',

'No answer is posted till now'
=> '',

'Submit your answer'
=> '',

'Answers'
=> '',

'Submit Answers'
=> '',

'Album'
=> '',

'Select Album'
=> '',

'Upload'
=> '',

'Groups'
=> 'Gruppen',

'Thumbnail'
=> '',

'Title/Description/Date/Tags'
=> '',

'Album/Playlist'
=> '',

'No Audio'
=> '',

'Blog Settings'
=> '',

'You have 3 blog options:'
=> '',

'You can contribute to the community blog'
=> '',

'You also can have a personal blog. A personal blog shows up on your page '
.'with posts routed to the community blog by default. You can opt for those to '
.'only be on your personal blog.'
=> '',

'If you already have a blog, you can display your External Blog here.'
=> '',

'Add a personal blog'
=> '',

'Display my external blog here'
=> '',

'Save'
=> 'Sichern',

'View my public page'
=> 'Meine öffentliche Seite',

'Configure external blog'
=> '',

'Welcome'
=> '',

'Enter your new password'
=> '',

'Re-enter the new password'
=> '',

'Change Password'
=> '',

'Please enter your new password'
=> '',

'Please confirm your new password'
=> '',

'Passwords do not match. Please re-enter'
=> '',

'Password should be of %s characters or more.'
=> '',

'Password should be less than %s charcaters.'
=> '',

'Manage comments.'
=> '',

'When'
=> '',

'Parent'
=> '',

'Abuses'
=> '',

'Author'
=> 'Autor',

'Delete'
=> 'Löschen',

'No Comments'
=> '',

'Manage Comments'
=> '',

'Anonymous'
=> '',

'ConfigManager'
=> '',

'Section does not exists!'
=> '',

'Configuration data sucessfully stored.'
=> '',

'Select edit mode and section name'
=> '',

'Mode'
=> '',

'Section'
=> '',

'People Aggregator Defender setup'
=> '',

'Rule'
=> '',

'Status'
=> '',

'description'
=> '',

'PADefender configuration data sucessfully stored.'
=> '',

'Configure Email'
=> '',

'Select An email type'
=> '',

'Select an email type'
=> '',

'Description'
=> 'Beschreibung',

'Email Template'
=> '',

'Configurable variables related to the selected message'
=> '',

'Recipient/Requester configurable variables available in each message'
=> '',

'Network configurable variables available in each message'
=> '',

'Group configurable variables available in each message of Group type'
=> '',

'Restore Default'
=> '',

'Store as Defaults'
=> '',

'Caution - software developers only'
=> '',

'Load / restore Email Message settings from local disk'
=> '',

'Select XML configuration file.'
=> '',

'Select action'
=> '',

'Load Email Message settings'
=> '',

'Revert All Messages'
=> '',

'Warning: you will lose all message changes made at this site.'
=> '',

'Select page'
=> '',

'Select page you want to customize.'
=> '',

'Get module info'
=> '',

'Add this module to: '
=> '',

'Page ID'
=> '',

'If you want to create a new page, enter here an unique Page ID number.'
=> '',

'For dynamic pages, this ID number should start from 200.'
=> '',

'Page Title'
=> '',

'Enter Page name'
=> '',

'Login required'
=> '',

'No'
=> 'Ja',

'Yes'
=> 'Nein',

'Select Page type'
=> '',

'Page type'
=> '',

'Enter Page type (user, group, network). For multiple types use "|" to '
.'separate types.'
=> '',

'Is page configurable'
=> '',

'If a page is configurable - these settings will be available in Customize UI '
.'pages.'
=> '',

'Required user or administration permissions for access to this page'
=> '',

'Enter required administration permissions. Currently, these permissions are '
.'available'
=> '',

'Page Theme'
=> '',

'Enter Page theme (Beta)'
=> '',

'Page Outer Template'
=> '',

'Enter Page Outer Template (container_three_column.tpl, container_two_column.'
.'tpl ...)'
=> '',

'Header Template'
=> '',

'Enter Page Header Template (header.tpl, header_group.tpl ...)'
=> '',

'Page boot (pre-execute) PHP code'
=> '',

'Enter here code that should be executed on page boot before any module '
.'initialization function called. Use this only if you have a good reason for '
.'that and when you can\'t place that code inside a module - initializeModule() '
.'function. For example, if some modules need and share same data and you want '
.'to avoid executing same code multiple times. In that case, place here '
.'required code to evaluate those data and forward results to each module via '
.'$module_shared_data variable. For example'
=> '',

'NOTE: If your page does not require additional boot code, leave this '
.'untouched.'
=> '',

'Left modules'
=> '',

'Enter Left modules separated by commas'
=> '',

'Middle modules'
=> '',

'Enter Middle modules separated by commas'
=> '',

'Right modules'
=> '',

'Enter Right modules separated by commas'
=> '',

'Page JavaScript files'
=> '',

'Enter page Javascript file names separated by commas'
=> '',

'Page CSS files'
=> '',

'Enter page CSS file names separated by commas'
=> '',

'Page navigation links PHP code'
=> '',

'Enter code required for generating page navigation links. Here should be '
.'moved code from function'
=> '',

'declared in'
=> '',

'class (web/includes/classes/Navigation.php)'
=> '',

'inside'
=> '',

'statement'
=> '',

'Please see an example below. In this example we will use code written for '
.'generating navigation links on'
=> '',

'page'
=> '',

'So, this PHP code block should be copied and pasted in a text field above. '
.'If old'
=> '',

'page will not be used anymore, this code block should be removed from '
.'Navigation class'
=> '',

'See'
=> '',

'line'
=> '',

'NOTE: Code in the box above is only for example. You must delete it or enter '
.'your menu- navigation code here!'
=> '',

'Page body attributes'
=> '',

'Enter page body CSS attribute. For example'
=> '',

'Save generated page'
=> '',

'Select if you want to save generated Page'
=> '',

'Edit/Create Dynamic Page'
=> '',

'Your page created sucessfull. Page data'
=> '',

'Click here for preview'
=> '',

'Write Testimonial'
=> '',

'Testimonial'
=> '',

'Write Testimonial for '
=> '',

'Left'
=> '',

'Right'
=> '',

'Middle'
=> '',

'Background Image'
=> '',

'Current Background Image'
=> '',

'Upload Background Image'
=> '',

'Image as header background will appear on your Networks Pages'
=> '',

'Apply background image'
=> '',

'Theme Selector'
=> '',

'Module Selector'
=> '',

'Desktop image'
=> '',

'Customize Theme'
=> '',

'Desktop Image'
=> '',

'Current Desktop Image'
=> 'Derzeitiges Desktop Bild',

'Upload Desktop Image'
=> '',

'Image will appear on your Personal Pages'
=> '',

'Image will appear on your Groups Pages'
=> '',

'Image will appear on your Networks Pages'
=> '',

'Set image appearance'
=> 'Bild darstellungs-Optionen wählen',

'Stretch to fit'
=> '',

'Crop'
=> '',

'Tile'
=> '',

'Leave it alone'
=> '',

'Images 1016 pixels wide by 191 pixels tall will have the best results'
=> '',

'Set Desktop image Turn on/off'
=> '',

'Turn on'
=> '',

'Turn off'
=> '',

'Here to set the Desktop image is display turn on or off.'
=> '',

'Apply desktop image'
=> '',

'Select page layout'
=> '',

'Select page layout template.'
=> '',

'Add a side module'
=> '',

'Select a side module to add it to your page, chose module placement column, '
.'then click "Save settings". '
=> '',

'Add a middle module'
=> '',

'Select a middle module to add it to your page, chose module placement '
.'column, then click "Save settings". '
=> '',

'Available Modules'
=> '',

'Enable'
=> '',

'Show in Left or Right'
=> '',

'Stacking Order'
=> '',

'Use these settings to customize the look of your Network pages'
=> '',

'that others will see.'
=> '',

'Select Theme'
=> '',

'Apply Changes'
=> 'Änderungen anwenden',

'This is the echo test module.'
=> '',

'>Update:'
=> '',

'Echo Test'
=> '',

'Family Name'
=> '',

'Family Photo'
=> '',

'About this Family'
=> '',

'Create Family'
=> '',

'Change Family Settings'
=> '',

'Please supply a name for the Family.'
=> '',

'Family has been updated successfully.'
=> '',

'Family has been created successfully.'
=> '',

'Edit'
=> 'Bearbeiten',

'Full view'
=> 'Vollansicht',

'Return to %s gallery'
=> 'Zurück zur %s Gallerie',

'Select'
=> 'Auswählen',

'Access'
=> 'Zugang',

'in which your'
=> 'in welchem deine',

'file will appear...'
=> 'erscheinen wird',

'Create New Album'
=> 'Neues Album erstellen',

'Return to media gallery'
=> 'Zurück zur Gallerie',

'Basic info'
=> '',

'Login Name'
=> '',

'Password'
=> 'Passwort',

'Confirm Password'
=> 'Passwort bestätigen',

'First Name'
=> 'Vorname',

'Last Name'
=> 'Nachname',

'Email'
=> 'Email',

'Upload Photo'
=> '',

'Current Image'
=> 'Derzeitiges Bild',

'Remove Picture'
=> 'Bild entfernen',

'You have 3 blog options'
=> '',

'You also can have a personal blog. A personal blog shows up on your page '
.'with posts routed to the community blog by default. You can opt for those to '
.'only be on your personal blog'
=> '',

'If you already have a blog, you can display your External Blog on My Page'
=> '',

'Profile updated successfully.'
=> 'Profil erfolgreich aktualisiert.',

'Blogs/RSS'
=> '',

'Add another Blog'
=> '',

'Remove'
=> 'entfernen',

'Permission to view your Blog'
=> '',

'Blog Title'
=> '',

'Blog URL'
=> '',

'Blog Feed URL'
=> '',

'Basic Info'
=> '',

'General Info'
=> '',

'Personal Info'
=> '',

'Professional Info'
=> '',

'Notifications'
=> 'Benschrichtigungen',

'Import Contacts'
=> '',

'Export'
=> '',

'Delete Account'
=> 'Account löschen',

'You are not allowed to delete your account here. You can delete your account '
.'from meta organization only.'
=> '',

'If you delete your account, all your content posted and your membership in '
.'other networks will be deleted. Your complete information will be deleted '
.'from the network.'
=> '',

'To delete your account you have to check this box.'
=> 'Um dein Konto zu löschen musst du dieses Kästchen anklicken.',

'Delete My Account'
=> 'Mein Konto löschen',

'EditProfileModule::handleSaveProfile() - Unknown save handler!'
=> '',

'Fields marked with * can not be empty, First name can not be empty.'
=> '',

'Fields marked with * can not be empty, Email field is mandatory.'
=> '',

'Password and confirm password should match.'
=> '',

'Personal and professional info'
=> '',

'show everything'
=> '',

'show what your friends see'
=> '',

'show only public info'
=> '',

'Sidebar preview of your hCard/XFN profile'
=> '',

'Please modify the hCard/XFN preview below to suit your taste.'
=> '',

'Once you have selected what you want to display, click \'create hCard\', then '
.'copy the generated HTML to your blog or wherever you want to use it.'
=> '',

'The Date of Birth is invalid.'
=> '',

'Url is invalid'
=> '',

'Sorry: you are unable to save data.'
=> '',

'Reason: '
=> '',

'Family'
=> '',

'Create new %s'
=> '',

'Select for All'
=> '',

'Slogan'
=> '',

'Slogan will appear on your Public Page.'
=> '',

'Shout Out'
=> '',

'Shout out will appear on your Public Page.'
=> '',

'Gender'
=> 'Geschlecht',

'Date of Birth'
=> '',

'Address'
=> '',

'Address 2'
=> '',

'Other state'
=> 'Anderes Bundesland',

'State/Province'
=> 'Bundesland',

'Zip/Postal Code'
=> '',

'Phone'
=> '',

'Mobile Phone'
=> '',

'Seperate tags with commas.'
=> '',

'I want to receive  notifications when'
=> '',

'via my registered email'
=> 'über meine registrierte Email Adresse',

'via my account inbox'
=> 'über meine Konto InBox',

'Notify \'messages waiting\''
=> '',

'through my registered mail'
=> '',

'\'messages waiting\' notifications in my mail box, when new messages arrive'
=> '',

'Restore default settings'
=> '',

' Reason: '
=> '',

'Political View'
=> '',

'TV Shows'
=> '',

'Sorry: you are unable to save data'
=> '',

'Upload CV'
=> '',

'Valid file types are .doc and .pdf'
=> '',

'This will replace your current CV'
=> '',

'Work Phone'
=> '',

'Career Skills'
=> '',

'Prior Title'
=> '',

'College Name'
=> '',

'Your full Professional biography here. Please note there is a 2,500 '
.'character limit.'
=> '',

'Honors &amp; Awards'
=> '',

'Specify how close you are in your relationship with'
=> '',

'User: '
=> '',

'Check if'
=> '',

'is'
=> '',

'in family'
=> '',

'Update Relationship Request'
=> '',

'ADD as a Friend'
=> '',

'Your request for adding '
=> '',

' as a relation has already been sent'
=> '',

'Edit Relationship'
=> '',

'Your relationship request approved.'
=> '',

'Relationship estabilished.'
=> '',

'You cannot add an Event to the calendar of group %s, as you are not a member.'
=> 'Du kannst dieses Ereignis nicht der Gruppe %s hinzufügen, weil du kein '
.'Mitglieded bist.',

'Couldn\'t create event:'
=> 'Konnte das Ereignis nicht erzeugen:',

'Couldn\'t create EventAssociation:'
=> '',

'There was a problem updating the event:'
=> 'Es gab ein Problem bein Aktualisieren des ereignisses:',

'Event %d doesn\'t exist'
=> 'Ereignis %d existiert nicht.',

'Couldn\'t update the event:'
=> 'Konnte das Ereignis nicht aktualisieren',

'There was a problem deleting the event:'
=> 'Es gab ein Problem beim Löschen des Ereignisses.',

'The event has been deleted.'
=> 'Das Ereignis wurde gelöscht.',

'Couldn\'t delete the event:'
=> 'Konnte das ereignis nicht löschen:',

'No users given'
=> '',

'There was a problem associating the event:'
=> '',

'%s is not a user'
=> '%s ist kein Benutzer',

'Add people:'
=> 'Leute hinzufügen:',

'You cannot add an Event to the caledar of group %s, as you are not a member.'
=> '',

'Add group:'
=> 'Gruppe hinzufügen:',

'You may not remove the association to this event.'
=> '',

'You cannot remove yourself from this event, as you created it.  Please use '
.'\'Delete Event\' instead.'
=> '',

'Event'
=> 'Ereigniss',

'Event Banner'
=> 'Ereigniss Banner',

'Starts'
=> 'Beginnt',

'Ends'
=> 'Endet',

'Venue'
=> 'Ort',

'Are you sure you want to delete this Event?'
=> 'Bist du sicher, dass du dieses Ereigniss löschen willst',

'Create new Event'
=> 'Neues Ereigniss erstellen',

'Edit Event'
=> 'Ereigniss bearbeiten',

'Create Event'
=> 'Ereigniss erstellen',

'Event title'
=> 'Ereigniss Titel',

'Start date'
=> 'Start Datum',

'Start time'
=> 'Start Zeit',

'End date'
=> 'Ende Datum',

'End time'
=> 'Ende Zeit',

'Event venue'
=> 'Ort',

'Event description'
=> 'Beschribung',

'Current Event Banner'
=> '',

'Upload Event Banner'
=> 'Banner hochladen',

'This event appears on'
=> 'Dieses Ereigniss erscheint auf',

'Calendar for'
=> 'Kalender für',

'(This event will always appear in the creator\'s calendar.)'
=> '',

'Add to further calendars'
=> '',

'Add people\'s login names here, seperated by commas.'
=> '',

'Groups you are a member of'
=> '',

'Add'
=> 'Hinzufügen',

'Unknown event association'
=> 'Unbekannte ereignis Verknüpfung',

'Display as'
=> 'Anzeigen als',

'List'
=> 'Liste',

'Calendar'
=> 'Kaöender',

'Personal Events'
=> 'Persönliche Ereignisse',

'External Feeds'
=> '',

'There are %d members in %s.'
=> '',

'There are %d friends.'
=> '',

'There are '
=> '',

' members '
=> '',

'Approve'
=> '',

'Deny'
=> '',

'There are %d members in this %s.'
=> '',

'There are %d members.'
=> '',

'There are %d friends for %s.'
=> '',

'member since:'
=> '',

'waiting approval'
=> '',

'No relation exists.'
=> '',

'FaceBookFeed'
=> '',

'Friend'
=> 'Freund',

'Last login'
=> '',

'Latest registered'
=> '',

'Sort By'
=> '',

'(%d %ss)'
=> '(%d %se)',

'sort by'
=> '',

'Family Directory'
=> '',

'Name'
=> 'Name',

'Family Members'
=> '',

'Login name'
=> 'Login Name',

'Login name may contain letters, numbers and underscores (_).'
=> 'Der Login Name kann Buchstaben, Zahlen und Unterstriche (_) enthalten',

'First name'
=> 'Vorname',

'Last name'
=> 'Nachname',

'Day'
=> '',

'Month'
=> '',

'Year'
=> '',

'Street address 1'
=> 'Adresse 1',

'Street address 2'
=> 'Adresse 2',

'ZIP Code'
=> 'PLZ',

'Phone #'
=> 'Telefon Nummer',

'Password can be 5-15 characters long, and is case sensitive.'
=> 'Das PAsswort kann 5-15 Zeichen lang sein und die Gross-/Kleinschreibung ist '
.'wichtig',

'Confirm password'
=> 'Passwort bestätigen',

'use own email account'
=> '',

'use a parent\'s email account'
=> '',

'Upload a photo'
=> 'Ein Foto hochladen',

'Or enter a photo URL'
=> '',

'Preview Image'
=> 'Bildvorschau',

'Clear Image'
=> 'Bild löschen',

'Your photo'
=> 'Dein Foto',

'To use a different image, click Clear Image and select a new image.'
=> 'Um ein anderes Foto zu benutzen, klicke \'Bild löschen\' und wähle ein anderes',

'I have read and agree to the %s <a href=\'%s/terms.php\' target=\'_blank\'>Terms '
.'and Conditions</a>'
=> 'I habe die %s <a href=\'%s/terms.php\' target=\'_blank\'>AGBs</a> gelsen und '
.'akzeptiere sie.',

'Family Members Moderation'
=> '',

'Edit/Assign Role'
=> '',

'Joined Family'
=> '',

'There are no members in this %s'
=> '',

'Remove Selected'
=> '',

'Add a Child'
=> '',

'Member(s) Deleted'
=> '',

'Please select a member'
=> '',

'You have left "%s" successfully.'
=> '',

'Child\'s account was successfully created'
=> '',

'Member'
=> 'Mitglied',

'Family Profile'
=> '',

'Sorry, you can\'t perform this action.'
=> '',

'Request to join this family as'
=> '',

'Join This family as'
=> '',

'You are a %s'
=> '',

'Edit %s profile'
=> '',

'%s profile'
=> '',

'Please select a type.'
=> '',

'TypedEntity associated successfully.'
=> '',

'Please upload a valid Game Image in %s'
=> '',

'You have updated your relation to "%s" successfully.'
=> '',

'You are already a member of "%s"'
=> '',

'Your request to join "%s" has been submitted to the owner of the group.'
=> '',

'You have joined "%s" successfully.'
=> '',

'You need to be logged in to join a group.'
=> '',

'You can\'t leave your own group.'
=> '',

'You are not member of "%s".'
=> '',

'Group sucessfully deleted.'
=> '',

'Leave this Family'
=> '',

'Update relation'
=> '',

'-- Please select --'
=> '',

'Update'
=> '',

'Join now'
=> 'Jetzt Mitglied werden',

'Family Settings'
=> '',

'Forgotten your PeopleAggregator account information?'
=> '',

'Just enter the e-mail address or login name you signed up with, and we\'ll '
.'mail you a link to change your password.'
=> '',

'E-mail address:'
=> '',

'Get new password'
=> '',

'Please enter your email address or login name.'
=> '',

'Please enter either email or Login name'
=> '',

'Invalid email address.  Please try again.'
=> '',

'A link has been e-mailed to you to let you change your password.  Thanks!'
=> '',

'There are no accounts in our system with the e-mail address %s.\n'
.'              If you have spelled the address incorrectly or entered the '
.'wrong address, please try again.'
=> '',

'Recover Password'
=> '',

'Latest Forum Posts'
=> '',

'Date'
=> '',

'Forum Name'
=> '',

'Thread Title'
=> '',

'User'
=> '',

'Last Post'
=> '',

'Replies'
=> '',

'No posts'
=> '',

'Posts'
=> '',

'You will be able to answer this post after admin approve your membership '
.'request'
=> '',

'Banned User'
=> '',

'Administrator message'
=> '',

'label'
=> '',

'Edit post'
=> '',

'Edit thread'
=> '',

'Post title'
=> '',

'Thread title'
=> '',

'Post content'
=> '',

'Thread content'
=> '',

'Forum'
=> '',

'Forum Last post'
=> '',

'Threads'
=> '',

'Category:'
=> '',

'Are you sure you want to delete this category?'
=> '',

'Posted by'
=> '',

'no posts'
=> '',

'Pages: '
=> '',

'Thread'
=> '',

'You will be able to answer this topic after admin approve your membership '
.'request'
=> '',

'Are you sure you want to delete this topic?'
=> '',

'Thread Last post'
=> '',

'Viewed'
=> '',

'Forum:'
=> '',

'Are you sure you want to delete this forum?'
=> '',

'Created by'
=> 'Erstellt von',

'Forums'
=> 'Foren',

'Forum Board for this network has not yet been created.'
=> '',

'Forum Board for this group has not yet been created.'
=> '',

'The personal forum board for this user has not yet been created.'
=> '',

'Post does not exist!'
=> '',

'Thread does not exist!'
=> '',

'You don\'t have permissions to post on this Forum!'
=> '',

'New Thread'
=> '',

'You don\'t have permissions to create a new thread!'
=> '',

'Forum does not exists!'
=> '',

'Edit Forum'
=> '',

'New Forum'
=> '',

'Forum title'
=> '',

'Short description'
=> '',

'You don\'t have permissions to create a new forum!'
=> '',

'Category does not exists!'
=> '',

'Edit Category'
=> '',

'New Category'
=> '',

'Category title'
=> '',

'You don\'t have permissions to create a new category!'
=> '',

'network forum board'
=> '',

'group forum board'
=> '',

'personal forum board'
=> '',

'Forum Board description goes here'
=> '',

'Forum Board sucessfully saved'
=> '',

'You don\'t have permissions to create this Forum Board!'
=> '',

'Forum Settings'
=> '',

'Forum name'
=> '',

'Forum description'
=> '',

'Allow anonymous post'
=> '',

'Allow users to create Categories'
=> '',

'Allow users to create Forums'
=> '',

'Membership approval required'
=> '',

'Threads per page'
=> '',

'Posts per page'
=> '',

'Avatar size'
=> '',

'Edit mode'
=> '',

'Forum theme'
=> '',

'Banned users message'
=> '',

'Join requested message'
=> '',

'Join approved message'
=> '',

'You don\'t have permissions to edit Forum Board settings!'
=> '',

'You don\'t have required permissions for this task!'
=> '',

'Post does not exists!'
=> '',

'Thread does not exists!'
=> '',

'Thread sucessfully removed'
=> '',

'Forum sucessfully deleted'
=> '',

'Category sucessfully deleted'
=> '',

'Post sucessfully deleted'
=> '',

'Thread not found!'
=> '',

'sticky'
=> '',

'locked'
=> '',

'Thread status sucessfully changed'
=> '',

'Anonymous user can\'t be banned'
=> '',

'You can\'t ban itself.'
=> '',

'Can\'t ban user - user not found!'
=> '',

'User status sucessfully changed.'
=> '',

'User is'
=> '',

'not'
=> '',

'banned now.'
=> '',

'Please, enter your name or email address'
=> '',

'Please, enter correct verification code'
=> '',

'Please, enter reply title'
=> '',

'Please, enter reply message text'
=> '',

'Reply post sucessfully saved'
=> '',

'Please, enter thread title'
=> '',

'Please, enter thread text'
=> '',

'Thread sucessfully created'
=> '',

'Please, enter forum title'
=> '',

'Please, enter forum description text'
=> '',

'Forum sucessfully created'
=> '',

'Forum data sucessfully updated'
=> '',

'Please, enter category title'
=> '',

'Please, enter category description text'
=> '',

'Category sucessfully created'
=> '',

'Category data sucessfully updated'
=> '',

'Please, enter numeric value into the "threads_per_page" field'
=> '',

'Please, enter numeric value into the "posts_per_page" field'
=> '',

'Settings data sucessfully updated'
=> '',

'Title field can\'t be empty'
=> '',

'Content field can\'t be empty'
=> '',

'Post sucessfully saved'
=> '',

'Thread sucessfully saved'
=> '',

'Reply to'
=> '',

'post'
=> '',

'thread'
=> '',

'Reply title'
=> '',

'Reply content'
=> '',

'User '
=> '',

'wrote'
=> '',

'Enter the verification code'
=> '',

'Code'
=> '',

'Your name or email'
=> '',

'Click here to create it'
=> '',

'Forums List'
=> '',

'type: '
=> '',

'board'
=> '',

'Forum Statistics'
=> '',

'Type'
=> 'Art',

'Members'
=> 'Mitglieder',

'Categories'
=> '',

'Topics'
=> '',

'Founded'
=> 'Gegründet',

'Request to join this group'
=> '',

'Join This Group'
=> '',

'Leave This Group'
=> '',

'Group Settings'
=> 'Gruppeneinstellungen',

'Invite Into Groups'
=> '',

'Please select a group'
=> '',

'Invitation could not be sent to following login names- %s'
=> '',

'Invitation could not be sent to following email addresses- %s'
=> '',

'Invitation from %s %s to join %s'
=> '',

'Sorry: you are unable to invite a friend.  Reason: %s'
=> '',

'Select a group to invite into'
=> '',

'Enter Your friend\'s login name(in People Aggregator) or email address'
=> '',

'(separated by comma)'
=> '',

'Write here personalized message for invitees. It will be appended to email'
=> '',

'Write your invitation Message'
=> '',

'Send Invitation'
=> '',

'Moderate Group Members'
=> '',

'Moderate Membership'
=> '',

'Moderate Content'
=> '',

'Content'
=> 'Inhalt',

'There are no pending moderation requests'
=> '',

'Content Approved'
=> '',

'Content Denied'
=> '',

'Please select a content for approval'
=> '',

'Please select a content for denial'
=> '',

'Requests'
=> '',

'Approve or deny requests to join this group'
=> '',

'User Approved'
=> '',

'User Denied'
=> '',

'Please select a user for approval'
=> '',

'Please select a user for denial'
=> '',

'Moderate %s Members'
=> '',

'Moderation'
=> '',

'Remove selected members from the %s'
=> '',

'Declare as Moderator'
=> '',

'Declare as Member'
=> '',

'User status sucessfuly changed.'
=> '',

'Can\'t change status for this user.'
=> '',

'member'
=> '',

'No groups created yet. Be the first to <a href="%s" style="display:inline;'
.'">create one</a>!'
=> '',

'No Groups found.'
=> '',

'Click'
=> '',

'to create.'
=> '',

'caption'
=> 'Überschrift',

'Group doesn\'t exist'
=> '',

'Browse %d Groups'
=> '',

'No groups in this category'
=> '',

'On this page you can manage all posts of the %s.'
=> '',

'Create post'
=> 'Beitrag erstellen',

'title'
=> '',

'No Content Published'
=> '',

'On this page you can manage all the forums of the Group.'
=> '',

'Create Forum'
=> '',

'Manage %s Contents'
=> '',

'Alphabetical'
=> 'Alfabetisch',

'Largest'
=> '',

'Date Created'
=> '',

'Group Directory'
=> '',

'Create a Group'
=> '',

'Search Groups'
=> '',

'Search for'
=> '',

'Created'
=> '',

'Moderated By'
=> '',

'No groups found.'
=> '',

'Group Statistics'
=> '',

'Category'
=> 'Kategorie',

'Owner'
=> 'Eigentümer',

'No Photos.'
=> '',

'Gallery'
=> 'Gallerie',

'Recent Media'
=> 'Aktuelle Medien',

'Group Gallery'
=> 'Gruppen Gallerie',

'My Gallery'
=> 'Meine Gallerie',

'Images'
=> 'Bilder',

'Video'
=> 'Video',

'Audio'
=> 'Audio',

'No images have been published yet.'
=> 'Es sind noch keine Bilder veröffentlicht worden.',

'No videos have been published yet.'
=> 'Es sind noch keine Videos veröffentlicht worden.',

'No audio has been published yet.'
=> 'Es ist noch kein Audio veröffentlicht worden.',

'Are you sure you want to delete this image'
=> '',

'Added as a friend by'
=> '',

'Invite friends and colleagues to join %s:'
=> '',

'Choose a program or service below to import your contacts:'
=> '',

'Your Plaxo ID'
=> '',

'(Enter your email or AIM screen name here)'
=> '',

'Enter your password'
=> '',

'We will not store your password. It will only be temporarily used to access '
.'your Plaxo address book.'
=> '',

'Your WindowsLive ID'
=> '',

'(Enter your WindowsLive ID here)'
=> '',

'Your password'
=> '',

'We will not store your password. It will only be temporarily used to access '
.'your Windows Live address book.'
=> '',

'Select CSV file'
=> '',

'(Select CSV file you want to load)'
=> '',

'Email:'
=> '',

'(separate addresses with commas)'
=> '',

' Login Name'
=> '',

'Write your invitation Message:'
=> '',

'Invite'
=> 'Einladen',

'Following user names are not valid %s'
=> '',

'Following email addresses are not valid: %s'
=> '',

' Invalid Email addresses'
=> '',

'Sorry: you are unable to invite a friend. Reason: %s'
=> '',

'An Invitation has been sent to - %s'
=> '',

'Invitation Status'
=> '',

'Accepted invitations'
=> '',

'No Accepted Invitations'
=> '',

'Pending invitations'
=> '',

'No pending Invitations'
=> '',

'Largest %s'
=> '',

'Leader Board'
=> '',

'No.'
=> '',

'User Name'
=> '',

'Last Activity Date'
=> '',

'Ranking points'
=> '',

'Ranking stars'
=> '',

'unknown'
=> '',

'There\'s no ranked users.'
=> '',

'Manage your link lists'
=> '',

'Create new'
=> '',

'Edit selected list'
=> '',

'Delete selected list'
=> '',

'Create a list'
=> '',

'New List Name'
=> '',

'Links'
=> '',

'Links under the selected list will be shown here'
=> '',

'Create link'
=> '',

'Link caption'
=> '',

'URL'
=> '',

'Links Control Panel'
=> '',

'Sorry - you are not logged in or you have been logged out due to inactivity.'
.'<br />Please, log in again.<br />'
=> '',

'Login'
=> '',

'%s login.'
=> '',

'You can login directly if you have an account,<br />or you can <b><a href="/'
.'register.php">sign up right now</a></b> to create a new account.'
=> '',

'User name: '
=> '',

'Password: '
=> '',

'Remember me on this computer'
=> '',

'Forgot your password?'
=> '',

'Edit Ad'
=> '',

'Create An Ad'
=> '',

'Image'
=> '',

'Page'
=> '',

'Orientation'
=> '',

'Display count'
=> '',

'Hit count'
=> '',

'Enable/Disable'
=> '',

'Disable'
=> '',

'Are you sure you want to delete this Ad?'
=> '',

'In this page you can manage ads on your network'
=> '',

'Manage Ads'
=> '',

'Create New Ad'
=> '',

'Enter Title'
=> '',

'Title should not be greater than 30 characters'
=> '',

'Select An Image'
=> '',

'Preferred size'
=> '',

'for side modules and'
=> '',

'for center modules'
=> '',

'Previously Selected Image'
=> '',

'Enter URL'
=> '',

'Or Enter JavaScript(.js code)/ Html code'
=> '',

'Enter Description'
=> '',

'Select Page'
=> '',

'Select a page'
=> '',

'Select Horizontal position'
=> '',

'Select vertical position'
=> '',

'Manage Ad Center'
=> '',

'You do not have permission to manage Ads.'
=> '',

'Select horizontal position'
=> 'Wähöe horizontale Position',

'left'
=> 'links',

'center'
=> 'mitte',

'right'
=> 'rechts',

'top'
=> 'oben',

'Edit Textpad'
=> '',

'Create Textpad'
=> '',

'Are you sure you want to delete this Textpad'
=> '',

'Available Textpads'
=> '',

'New Textpad'
=> '',

'In this page you can manage category on your network'
=> '',

'Manage Category'
=> 'Kategorie verwalten',

'Select Type'
=> '',

'Options'
=> '',

'Create New Category'
=> '',

'Parent Category (Optional)'
=> '',

'Enter Tilte'
=> '',

'You can upload a gif, jpg, jpeg, png, xpm, bmp, file.'
=> '',

'Maximum size'
=> '',

'Do not upload photos containing cartoons, celebrities, nudity, artwork of '
.'copyrighted images.'
=> '',

'For better result image dimension  should be 36x191'
=> '',

'Select a file to upload'
=> '',

'Enter the destination URL of image'
=> '',

'Image title'
=> '',

'Manage Domain List'
=> '',

'Please press enter after each entry'
=> '',

'Edit Link'
=> '',

'Create A Link'
=> '',

'Caption'
=> '',

'Are you sure you want to delete this link?'
=> '',

'In this page you can manage footer links.'
=> '',

'Manage Footer Links'
=> 'Links der Fusszeile verwalten',

'Create New Footer Link'
=> '',

'Enter Caption'
=> '',

'Caption should be less than 30 characters.'
=> '',

'Check this, if you want to open link in a different window'
=> '',

'In this page you can manage groups on your network'
=> '',

'Manage Groups'
=> 'Gruppen verwalten',

'Manage Profanity List'
=> '',

'Edit question'
=> '',

'Create new question'
=> '',

'select'
=> '',

'Question'
=> '',

'Are you sure you want to delete this?'
=> '',

'In this page you can manage questions for your network\'s users'
=> '',

'Manage Questions'
=> '',

'Set Active Question'
=> '',

'Id'
=> '',

'Points'
=> '',

'Edit activity types or add a new type below'
=> '',

'New'
=> '',

'Manage Ranking points'
=> '',

'\'Title\' and/or \'Type\' filed should not be empty.'
=> '',

'\'Points\' filed should be numeric and not empty.'
=> '',

'Edit Static Page'
=> '',

'Create Static Page'
=> '',

'Page Text'
=> '',

'Are you sure you want to delete this page?'
=> '',

'Manage Static Pages'
=> '',

'Create New Static Page'
=> '',

'Enter Page Text'
=> '',

'Manage TakeATour'
=> '',

'Video URL'
=> '',

'Video description'
=> '',

'Media file has been deleted from album or gallery.'
=> 'Medien datei wurde aus dem Albun gelöscht.',

'Author of this content is no longer a member of this group'
=> '',

'Return to %s'
=> 'Zurück zu %s',

'Return to %s\'s gallery'
=> 'Zurück zu %ss Gallerie',

'%s\'s Page'
=> '%ss Seite',

'My Page'
=> 'Meine Seite',

'No such content or media file has been deleted from the gallery.'
=> '',

'On this page you can manage all posts you have created.'
=> '',

'All Posts'
=> 'Alle Beiträge',

'Events'
=> 'Ereignisse',

'Reviews'
=> '',

'People'
=> 'Mitglieder',

'Group'
=> '',

'No Content Published.'
=> '',

'Manage Post'
=> '',

'%s Members'
=> '%s Mitglieder',

'find People'
=> 'Leute finden',

'Member Search'
=> '',

'Folder creation failed. '
=> '',

' is not a valid folder name.'
=> '',

'Folder creation failed. You already have a folder named '
=> '',

'1 message has been deleted successfully'
=> '',

' messages have been deleted successfully'
=> '',

'1 message has been moved to folder '
=> '',

' successfully'
=> '',

' messages have been moved to folder '
=> '',

'Selected message(s) are already in '
=> '',

' folder'
=> '',

'Please select message(s) to move'
=> '',

'There are no messages in this folder.'
=> '',

'No messages matched your search'
=> '',

'Compose message'
=> '',

'Create new folder'
=> '',

'Move to:'
=> '',

'- Select Folder -'
=> '',

'(no folders available)'
=> '',

'Sent To'
=> '',

'To:'
=> '',

'Sender'
=> '',

'Search ...'
=> '',

'Inbox'
=> '',

'Sent'
=> '',

'Conversations View'
=> '',

'Go'
=> '',

'Mailbox'
=> '',

'Search Results'
=> '',

'You can\'t access other user\'s messages.'
=> '',

'Conversations'
=> '',

'Please create a folder to move message(s)'
=> '',

'Back to search results'
=> '',

'Reply'
=> '',

'Forward'
=> '',

'Previous'
=> '',

'Next'
=> '',

'Date:'
=> '',

'From:'
=> '',

'Subject:'
=> '',

'In this page you can view Email Addresses of all users'
=> '',

'All Users'
=> '',

'Most Active Users'
=> '',

'Dormant Users'
=> '',

'Email Addresses'
=> '',

'Total Points'
=> '',

'In this page you can view stats about system usage'
=> '',

'Registered Users'
=> '',

'Number of blog post'
=> '',

'Number of Images'
=> '',

'Profile Views'
=> '',

'Maximum'
=> '',

'Minimum'
=> '',

'Average'
=> '',

'Profile Visited by User'
=> '',

'Relations Statistics'
=> '',

'Number of Users by Email Domain:'
=> '',

'Domain Name'
=> '',

'Number of Users'
=> '',

'MIS Reports'
=> '',

'You haven\'t <a href="%s">created</a> or <a href="%s">joined</a> any '
.'families yet.'
=> '',

'User has not joined any family yet.'
=> '',

'Families'
=> '',

'My Families'
=> '',

'My Groups'
=> 'Meine Gruppen',

'You haven\'t <a href="%s">created</a> or <a href="%s">joined</a> any '
.'groups yet.'
=> '',

'User has not joined any groups yet.'
=> '',

'My Links'
=> 'Meine Links',

'No links under this category'
=> '',

'No links have been added. Click <a href="%s">here</a> to add links.'
=> '',

'No links have been added'
=> '',

'My Networks'
=> '',

'No network joined yet.'
=> '',

'Use this tool to send announcements to all registered network members'
=> '',

'Message/post'
=> '',

'Destination'
=> '',

'Deliver message to all registered members by internal mail'
=> '',

'Email message to all network members'
=> '',

'Post message to network home page community blog'
=> '',

'Send to me only'
=> '',

'Manage Network Bulletins'
=> '',

'Email Notifications'
=> '',

'Notify network operator (me) when'
=> '',

'Registered members receive notifications when'
=> '',

'via their registered email'
=> '',

'via their account inbox'
=> '',

'User settable'
=> '',

'Blink Messages Waiting:'
=> '',

'messages  waiting blinks in network member\'s toolbar when new messages arrive'
=> '',

'Update All Current Users'
=> '',

'Save changes'
=> '',

'Restore Defaults'
=> '',

'Load / restore User Account Defaults from local disk'
=> '',

'Load User Account Defaults'
=> '',

'Save Relationship'
=> '',

'Network Address'
=> '',

'Network address will be part of the URL of your network, e.g. <code>http://'
.'<b>abc</b>.%s/</code>. It should be less than 10 characters.'
=> '',

'Check Availability'
=> '',

'Network Title/Heading'
=> '',

'Title appears on network pages.  For best results, keep below 60 characters '
.'(max 100 characters).'
=> '',

'Network Sub Title'
=> '',

'The sub-title will be displayed below the Network Title.'
=> '',

'Network Category'
=> '',

'This category is used to organise the Network Directory.'
=> '',

'Network Description'
=> '',

'A short paragraph or two describing your network.'
=> '',

'Default Network Language'
=> '',

'Select the Network default language'
=> '',

'Community Blog Title'
=> '',

'The Network group title will be displayed on the homepage.'
=> '',

'Network Icon'
=> '',

'The icon will appear in the network listing.'
=> '',

'Current Icon'
=> '',

'Ideal size 70 x 60 pixels'
=> '',

'Check if content moderation is required.'
=> '',

'Check if People page should only show users with a profile photo.'
=> '',

'Check if you want to enable the languages menu bar.'
=> '',

'Check if top menu bar is not required.'
=> '',

'Check if reciprocated relationships are required.'
=> '',

'Check if email address validation is required.'
=> '',

'Check if CAPTCHA is required during registration.'
=> '',

'Reciprocated relationships are required.'
=> '',

'Reciprocated relationships are not required.'
=> '',

'Email address validation is required.'
=> '',

'Email address validation is not required.'
=> '',

'CAPTCHA is required during registration.'
=> '',

'CAPTCHA is not required during registration.'
=> '',

'Load / restore General Network Settings from local disk'
=> '',

'Load General Settings'
=> '',

'Upload / Download network default settings for this network'
=> '',

'Select XML configuration file for upload.'
=> '',

'Download default settings file'
=> '',

'Upload new default settings file'
=> '',

'New User Account Defaults'
=> '',

'Network friends'
=> '',

'I appear as a friend in all new accounts'
=> '',

'These users appear as friends in all new accounts.'
=> '',

'(enter screen names of registered network users, separated by commas)'
=> '',

'Current default desktop image'
=> '',

'(Images 1016 pixels wide by 191 pixels tall will have the best results)'
=> '',

'Upload default desktop image'
=> '',

'Set desktop image turn on/off'
=> '',

'Media Gallery Images'
=> '',

'Select an image album(s) from your gallery to include in new user default '
.'galleries. (An album in your gallery may contain one or more images.)'
=> '',

'Upload to gallery now'
=> '',

'For multiple selections hold down the &lt;Ctrl&gt;key PC or the &lt;'
.'Command&gt; key(Mac) while clicking the desired selections.'
=> '',

'Media Gallery Audio'
=> '',

'Select an audio album(s) from your gallery to include in new user default '
.'galleries. (An album in your gallery may contain one or more audio clips.)'
=> '',

'Media Gallery Video'
=> '',

'Default Blog'
=> '',

'Select a post to include in new user default.'
=> '',

'Save Settings'
=> '',

'Network Default Links'
=> '',

'No links have been added.'
=> '',

'Multiple networks are disabled - please configure your system for network '
.'operation.'
=> '',

'The current featured network is: <a href="%s">%s</a>'
=> '',

'Select a featured network:'
=> '',

'Select a network'
=> '',

'Featured Network'
=> '',

'Configure'
=> 'Konfigurieren',

'System Settings'
=> '',

'Configuration manager'
=> '',

'PA Defender'
=> '',

'Network Settings'
=> '',

'Network settings'
=> '',

'Ad Center'
=> '',

'Textpads'
=> '',

'Manage Textpads'
=> 'Textpads verwalten',

'Meta network'
=> '',

'Set featured network'
=> '',

'Manage emblems'
=> '',

'Manage splash'
=> '',

'Info Boxes'
=> '',

'Network of Moment'
=> '',

'Showcase Modules'
=> '',

'Video Tours'
=> '',

'Server Announcement'
=> '',

'Survey'
=> '',

'Create Survey'
=> '',

'Select Survey'
=> '',

'Register Today'
=> '',

'Take a Tour Video'
=> '',

'Usage'
=> '',

'Counts'
=> '',

'Marketing reports'
=> '',

'Themes'
=> '',

'Theme selector'
=> '',

'Module selector'
=> '',

'Background image'
=> '',

'Header image'
=> '',

'Customize theme'
=> '',

'User defaults'
=> '',

'Default settings'
=> '',

'Relationship settings'
=> '',

'Users Settings'
=> '',

'Create users'
=> '',

'Manage users'
=> '',

'Moderate users'
=> '',

'Moderate contents'
=> '',

'Manage contents'
=> '',

'Manage comments'
=> '',

'Manage links'
=> '',

'Network links'
=> '',

'Manage Profanity'
=> 'Böse Wörter verwanlten',

'Profane Word List'
=> 'Böse Wörter Liste',

'Manage Signup Access'
=> '',

'Manage Domain Names'
=> '',

'Manage Events'
=> '',

'Network Events'
=> '',

'Bulletins'
=> 'Bulletins',

'Email notifications'
=> 'Email Benachrichtigungen',

'Roles'
=> '',

'Manage Roles & Tasks'
=> '',

'Manage Tasks Relationship'
=> '',

'Static Pages'
=> '',

'Manage Network Links'
=> '',

'No Link Categories'
=> '',

'Manage Links'
=> 'Links verwalten',

'Link Name'
=> '',

'Link'
=> 'Link',

'Manage Network Content'
=> '',

'Search Posts'
=> '',

'Browse Months'
=> '',

'Search'
=> 'Suche',

'Network Operator Controls'
=> '',

'In this page you can manage users registered on your network'
=> '',

'Search Registered Users'
=> '',

'Manage Users'
=> 'Benutzer verwalten',

'Moderate content on your network.'
=> '',

'No Content For Moderation.'
=> '',

'In this page you can moderate users registered on your network'
=> '',

'Picture'
=> '',

'Registered'
=> '',

'Action'
=> '',

'No User.'
=> '',

'Moderate Users'
=> '',

'Manage content on your network.'
=> '',

'Search posts'
=> '',

'Browse months'
=> '',

'Comments'
=> 'Kommentare',

'Are you sure you want to delete this content?'
=> '',

'No Content.'
=> '',

'Manage Content'
=> '',

'Manage users registered on your network'
=> '',

'Are you sure you want to delete this user?'
=> '',

'pending'
=> 'wartend',

'Assign Role'
=> 'Rolle zuweisen',

'Selected'
=> 'Ausgewählt',

'Are you sure?'
=> 'Bist Du sicher?',

'(un)check all'
=> 'alle an-/abwählen',

'No users'
=> '',

'No networks in this category'
=> '',

'Size'
=> 'Grösse',

'Network Directory'
=> '',

'Search Networks'
=> '',

'No networks found'
=> '',

'Network Statistics'
=> '',

'Newest %s'
=> 'Neueste %s',

'Networks'
=> '',

'Largest Network'
=> '',

'No network created yet.'
=> '',

'Provide a login name, email address and basic information for a new network '
.'member.'
=> '',

'Upon hitting the create button, the new member will be emailed a greeting '
.'including an auto-generated password.'
=> '',

'Fields marked with an asterisk (*) are mandatory.'
=> '',

'Email address'
=> '',

'Photo/avatar'
=> '',

'Auto-generate new password for network member'
=> '',

'Manual password'
=> '',

'modify greeting if desired and click the create user button below tocomplete '
.'process'
=> '',

'Hi,'
=> '',

'I\'ve created my own place on PeopleAggregator and I\'d like you to'
=> '',

'connect to me so we can stay in touch.'
=> '',

'You can view my blog, my reviews, my ratings, my photos, my lists -'
=> '',

'and all sorts of things that matter to me.'
=> '',

'You can create a personal page and blog of your own, which will be'
=> '',

'linked to mine.'
=> '',

'That way you\'ll always know when I post something new!'
=> '',

'Create User'
=> 'Benutzer erstellen',

'Location'
=> 'Ort',

'no data'
=> 'keine Daten',

'Age'
=> 'Alter',

'Add as'
=> 'Hinzufügen als',

'Advanced Search'
=> 'Erweiterte Suche',

'Simple Search'
=> 'Einfache Suche',

'Recent Users'
=> 'Aktuelle Benutzer',

' with picture in profile'
=> 'mit Bild im Profil',

'Select rows'
=> 'Wähle Zeilen',

'Find Users'
=> 'Benutzer finden',

'Male'
=> 'Männlich',

'Female'
=> 'Weiblich',

'Any'
=> 'Beides',

'Company Name'
=> 'Firmen Name',

'Interests'
=> 'Interessen',

'College'
=> '',

'Cusines'
=> '',

'Shout-out'
=> '',

'Click here to add your Shout-out.'
=> '',

'Please, select a family member that you wish to assign points'
=> 'Wähle ein Familienmithglied aus um Punkte zu vergeben',

'Date: '
=> 'Datum: ',

'No entries.'
=> 'Keine Einträge.',

'or click here to add a new'
=> 'oder hier klicken um eine neue hinzuzufügen',

'Rating Points'
=> 'Bewertungs Punkte',

'Place'
=> 'Ort',

'Related Media'
=> 'Verwandte Medien',

'Click here to upload'
=> 'Hier klicken um hochzuladen',

'%s Points Directory'
=> '%s Punkte verzeichniss',

'%s Points'
=> '%s Punkte',

'Points for %s'
=> 'Punkte für %s',

'Search results for \'%s\' Category'
=> 'Suchergebnisse für Kategorie %s',

'Add Points'
=> 'Punkte hinzufügen',

'Edit Points'
=> 'Punkte bearbeiten',

'You do not have permission for this action!'
=> 'Du bist nicht autorisiert die Aktion auszuführen!',

'Points Entity not found!'
=> '',

'Points sucessfully deleted.'
=> 'Punkte erfolgreich gelöscht.',

'Points data sucessfully stored'
=> 'Punkte erfolgreich gespeichert',

'Survey Archive'
=> 'Umfragen Archiv',

'Answer'
=> 'Antwort',

'See all recent Surveys'
=> 'Alle alten Umfragen anzeigen',

'Most Popular Tags'
=> '',

'Nothing has been tagged yet.'
=> 'Noch keine Stichwörter.',

'Attach Media'
=> 'Medien Datein anhängen',

'Add Image or Video'
=> 'Bild oder Video hinuifügen',

'Separate tags with commas'
=> 'Stichwörter mit Kammas trennen',

'edit your post'
=> 'Beitrag bearbeiten',

'create your post'
=> 'Beitrag erstellen',

'Routing'
=> 'Verteilung',

'Community Blog'
=> 'Gemeinschafts Blog',

'Post to %s (On this networks home page)'
=> 'Auf %s posten',

'You can route this post to one or many destinations with the selectors below.'
=> '',

'Please note that routing does not post to private groups'
=> '',

'Post to community Blog (On this networks home page)'
=> 'Auf die Homepage posten',

'Send to selected group blogs'
=> 'An augewählte Gruppen Blogs posten',

'Send to selected external blogs'
=> '',

'Select albums in your media gallery to send to'
=> 'Wähle Album in deiner Audio Gallerie aus',

'Select none of my galleries'
=> 'Keine meiner Gallerien auswählen',

'Select all of my galleries'
=> 'Alle meine Gallerien auswählen',

'No Albums'
=> 'Kein Album',

'Or, create a new album in your media gallery'
=> 'Oder erstelle ein Album in deiner Galerie',

'The post you are composing will be lost if you continue, are you sure you '
.'want to leave  without saving?'
=> 'Der Beitrag in Bearbeitung geht verloren wenn du die Seite verlässt. Bist du '
.'sicher, dss du ohne zu speichern weitermachen willst?',

'Add Blog Post'
=> 'Beitrag erstellen',

'Default Image Album'
=> 'Standard Bilder Album',

'Default Audio Album'
=> 'Standard Audio Album',

'Default Video Album'
=> 'Standard Video Album',

'Blogs'
=> 'Blogs',

'Question of the Day'
=> 'Frage des Tages',

'Site Ranking'
=> 'Site Bewertung',

'Recent Comments'
=> 'Neue Kommentare',

'My Friend\'s Comments'
=> 'Kommentare meiner Freunde',

'No title'
=> 'Kein Titel',

'No comments posted yet.'
=> 'Noch keine Kommentare erstellt.',

'Recent Posts'
=> 'Neue Beiträge',

'No contents in blog.  <a href="%s">Click here to make a post</a>!'
=> 'Noch keine Beiträge im Blog.  <a href="%s">Hier klicken um einen Beitrag '
.'zu erstellen</a>!',

'Browse Tags'
=> 'Stichworte durchstöbern',

'Nothing has been tagged yet'
=> 'Noch keine Stichwörter',

'Welcome to %s!'
=> 'Willkommen zu %s!',

'With your %s account you will be able to:'
=> 'Mit deinem %s Account kannst du:',

'Edit, share and store all your digital stuff in one place.'
=> 'All deine digitalen Dinge an einem Ort bearbeiten, speichern und mit snderen '
.'teilen.',

'Manage all your friends, groups and content.'
=> 'All deine Freunde, Gruppen und Inhalte verwalten.',

'Unite your online life by connecting all your presences together.'
=> 'Dein online Leben vereinheitlichen indem du hier alle deine Präsenzen '
.'zusammenfügst.',

'Provide the following information to join and start connecting all your '
.'digital worlds!'
=> 'Bitte mache die folgenden Angaben um Mitglied zu werden!',

'My '
=> 'Meine ',

'No %ss made yet.'
=> 'Noch keine %s gemacht.',

'Send request for joining network'
=> '',

'Your request to join this network could not be sent due to following reason: '
.'%s. You can go back to the home network by clicking Return to home network'
=> '',

'Your request to join this network has been successfully sent to the '
.'moderator of this network. The Moderator will check this request and approve '
.'or deny the request. You can go back to mother network by clicking the '
.'button Return to home network'
=> '',

'Return to home network successfully.'
=> '',

'Request Message'
=> '',

'Welcome to PeopleAggregator'
=> '',

'This is a private network'
=> '',

'You need to be member of this network to do anything. You can send a request '
.'to join this network by clicking \'Request to join\'.'
=> '',

'Return to home network'
=> 'Zurück zum Haupt-Netzwerk',

'In this page you can manage different admin roles'
=> '',

'Sr.No.'
=> '',

'No roles have been created yet.'
=> '',

'Add New Role'
=> '',

'Load / restore Roles Settings from local disk'
=> '',

'Load Roles Settings'
=> '',

'Manage Roles'
=> '',

'Invalid configuration file format. Configuration file should be a valid XML '
.'file. '
=> '',

'Roles settings successfully loaded from '
=> '',

' file.'
=> '',

'Please, select a valid XML configuration file.'
=> '',

'Role data sucessfully updated.'
=> '',

'New Role sucessfully created.'
=> '',

'Role sucessfully deleted.'
=> '',

'This Role can\'t be deleted.'
=> '',

'Select Task(s) you want to assign to this Role and press left/right arrow.'
=> '',

'Default Roles settings sucessfully restored.'
=> '',

'There is no Roles data in default XML settings file.'
=> '',

'Tag Search'
=> 'Stichwort Suche',

'Search Terms'
=> 'Such Begriffe',

'all of these words'
=> 'all diese Wörter',

'this exact phrase'
=> 'genau diese Phrase',

'any of these words'
=> 'beliebige dieser Wörter',

'none of these words'
=> 'keines dieser Wörter',

'Date Range'
=> 'Datums Bereich',

'Start Date'
=> 'Start Datum',

'End Date'
=> 'End Datum',

'Search Content'
=> 'Inhalte durchsuchen',

'Poll Topic'
=> 'Umfrage Thema',

'Number Of Options'
=> 'Anzahl der Wahlmöglichkeiten',

'Select Any One Topic'
=> 'Wähle eine Umfrage aus',

'No poll was created yet.'
=> 'Noch keine Umfrage erstellt.',

'Poll has been deleted successfully.'
=> 'Umfrage wurde erfolgreich gelöscht.',

'Poll has been saved successfully.'
=> 'Umfrage wurde erfolgreich gespeichert.',

'Poll has been created successfully.'
=> 'Umfrage wurde erfolgreich erstellt.',

'Announcements'
=> '',

'ShowCase'
=> '',

'Contents'
=> 'Inhalt',

'Date range selected is invalid. Please, select a valid date range.'
=> 'Datums Bereich ist ungültig, bitte einen gültigen Zeitraum auswählen.',

'Please enter either data or date to search'
=> 'Bitte entweder Datums- oder Textsuche eingeben ',

'%s\'s Group Blog'
=> '%ss Gruppen Blog',

'Manage posts'
=> 'Beiträge verwalten',

'Return to private page'
=> 'Zurück zur privaten Ansicht',

'Showing results for tag %s.'
=> 'Ergebnisse für Stichwort %s.',

'Moderate'
=> 'Moderieren',

'Manage content'
=> 'Inhalte verwalten',

'Join this group'
=> 'Dieser Gruppe beitreten',

'No items match your search criteria.'
=> 'Keine Einträge entsprechen den Suchkriterien',

'Back'
=> 'Zurück',

'Click <a href="%s">here</a> to add content.'
=> '<a href="%s">Hier</a> klicken um Inhalte hinzu zu fügen.',

'You will be redirected in '
=> 'Du wirst in ',

' seconds, or you can click here to redirect now'
=> ' Sekunden umgeleitet. Du kannst hier klicken um gleich umgeletet zu werden',

'An Error Has Occurred'
=> 'Ein Fehler is aufgetreten',

'Error details'
=> 'Fehler Details',

'Information'
=> 'Information',

'Please confirm action'
=> 'Bitte Aktion bestätigen',

'Warning!'
=> 'Warnung!',

'No Testimonial Found'
=> 'Noch keine Stimmen',

'Testimonials'
=> 'Stimmen',

'New Testimonials'
=> 'Neue Stimme',

'Click here to submit a Testimonial'
=> 'Hier klicken um eine Stimme zu posten',

'Testimonials for '
=> 'Stimmen zu ',

'Comment rejected by spam filter'
=> 'Kommentar wurde vom Spam Filter abgewiesen',

'Comment can\'t be empty.'
=> 'Kommentar kann nicht leer sein',

'Show Splash Page'
=> '',

'If this checkbox is checked then Splash Page will be the first page to be '
.'shown to the anonymous users otherwise Homepage will be the first page'
=> '',

'Info for: '
=> '',

'Info URL'
=> '',

'Paste the complete URL of the network here'
=> '',

'Info Image'
=> '',

'No image selected.'
=> '',

'Upload Image'
=> '',

'Uploaded images will be displayed at 145 pixels by 145 pixels.'
=> '',

'Set Info Boxes'
=> '',

'Network URL'
=> '',

'Network of the Moment Image'
=> '',

'Uploaded image will be displayed at 193 pixels by 67 pixels'
=> '',

'Save Network of the Moment'
=> '',

'Uploaded image will be displayed at 193 pixels by 67 pixels.'
=> '',

'Uploaded image will be displayed at 185 pixels by 110 pixels.'
=> '',

'Save Announcement'
=> '',

'Featured User'
=> '',

'Featured Group ID'
=> '',

'Featured Video Link'
=> '',

'Featured Business ID'
=> '',

'Save Showcase Module'
=> '',

'Showcased Network '
=> '',

'Showcased Network URL'
=> '',

'Showcased Network Image'
=> '',

'Set Showcased Networks'
=> '',

'Showcase Module'
=> '',

'Video Tours Image'
=> '',

'Save Video Tour'
=> '',

'Click here to watch the video'
=> '',

'Take A Tour'
=> '',

'In this page you can assign roles to tasks'
=> 'Hier werden Rollen zu Aufgaben zugeordnet',

'No roles have been created yet'
=> 'Noch keine Rollen erstellt',

'Assign Roles to Tasks'
=> 'Aufgaben zu Rollen zuordnen',

'Terms and conditions for using'
=> 'Nutzungs Bedingungen',

'There are %s entries in this directory.'
=> 'Es gibt &s Einträge in diesem Verzeichnis.',

'Master Directory'
=> 'Haupt Verzeichnis',

'%s directory'
=> '%s Verzeichnis',

'There is no TypedEntity associated with this Group yet. Would you like to '
.'create one?'
=> 'Noch keine TypedEntity mit dieser Gruppe verknüpft, möchtest du eine '
.'erstellen?',

'--- Please select ---'
=> '--- Bitte auswählen ---',

'Create it'
=> 'Erstellen',

'Typed Group Settings'
=> 'Typisierte Gruppen Einstellungen',

'Request to join this group as'
=> 'Anfragen Mitglied dieser Gruppe zu werden als',

'Join This Group as'
=> 'Dieser Gruppe beitreten als',

'You can upload an audio file'
=> 'Du kannst eine Audio Datei hochladen',

'Audio title'
=> 'Audio Titel',

'You can upload a gif, jpg, jpeg, png, xpm or bmp file'
=> 'Dateiformat kann gif, jpg, jpeg, png, xpm oder bmp sein',

'Do not upload photos containing cartoons, celebrities, nudity, artwork or '
.'copyrighted images'
=> 'Bitte keine Bilder hochladen dir Copyright geschützt sind oder unpassende '
.'Inhalte zeugen',

'Upload image'
=> 'Bild hochladen',

'Select who can see this image'
=> 'Wähle wer dieses Bild sehen darf',

'Tags (separate with commas)'
=> 'Stichwörter (mit Komma getrennt)',

'Add More'
=> 'Namen hinzufügen',

'Or finish below'
=> 'Oder unten abschliessen',

'Upload audio'
=> 'Audio hochladen',

'You can upload a video file'
=> 'Du kannst ein Video hochladen',

'Video title'
=> 'Video Titel',

'Upload video'
=> 'Video hochladen',

'Select a file to upload, or enter a URL below'
=> 'Wähle eine Datei, oder gebe unten eine URL ein.',

'Audio URL'
=> 'Audio URL',

'Select who can listen to this Audio'
=> 'Wähle wer dieses Audio hören kann',

'Send to album'
=> 'Senden an Album',

'Or create new album'
=> 'Oder erstelle ein neues Album',

'Image URL'
=> 'Bild URL',

'Unkonwn type selected'
=> 'Unbekannter Typ ausgewählt',

'LinkedIn Contacts: '
=> 'LinkedIn Kontakte: ',

'No contacts'
=> 'Keine Kontakte',

'MS Live Contacts: '
=> 'MS Live Kontakte: ',

'Contacts'
=> 'Kontakte',

'Import'
=> 'Import',

'Outlook Contacts: '
=> 'Outlook Kontakte: ',

'Plaxo Contacts: '
=> 'Plaxo Kontakte: ',

' contact(s) sucessfully imported'
=> ' Kontakt(e) erfolgreich importiert',

'Invalid file type. Please select a valid LinkedIn CSV file. '
=> 'Bitte eine gültige LinkedIn CSV Datei auswählen.',

'Please, select a valid LinkedIn CSV file.'
=> 'Bitte eine gültige LinkedIn CSV Datei auswählen.',

'Invalid file type. Please select a valid Outlook CSV file. '
=> 'Bitte eine gültige Outlook CSV Datei auswählen.',

'Please, select a valid Outlook CSV file.'
=> 'Bitte eine gültige Outlook CSV Datei auswählen.',

'Invite message can\'t be empty.'
=> 'Einladungsnachricht darf nicht leer sein.',

'Please, select one or more contacts.'
=> 'Bitte mindestens einen Kontakt auswählen.',

' contact(s) sucessfully deleted.'
=> ' Kontakt(e) erfolgreich gelöscht.',

'General'
=> 'Allgemein',

'Other'
=> 'Andere',

'No details.'
=> 'Keine Details.',

'Messages'
=> 'Nachrichten',

'Photo'
=> 'Photo',

'No Videos'
=> 'Keine Videos',

'No Video'
=> 'Kein Video',

'Are you sure you want to delete this video'
=> 'Bist du sicher, dass du diese Video löschen willst',

'View all Members'
=> 'Alle Mitglieder anzeigen',

'View all '
=> 'Zeige alle ',

'View All %s Members'
=> 'Zeige alle %s Mitglieder',

'Polls'
=> 'Umfragen',

'No previous poll to display'
=> 'Keine vorige Umfrage.',

'No votes are posted for this poll'
=> 'Noch keine Antworten auf dies Umfrage',

'Edit Events'
=> 'Ereignisse bearbeiten',

'My Events'
=> 'Meine Ereignisse',

'Email Messages settings data successfully loaded from '
=> 'Email Einstellungen erfolgreich geladen von ',

'Email message settings successfully restored.'
=> '',

'Network URL cannot be left empty for showcased network '
=> '',

' For showcased network '
=> '',

'No caption given to network of moment'
=> '',

'Please provide URL for network of moment'
=> '',

'No video URL provided for video tours'
=> '',

'No description provided for network of moment'
=> '',

' For network of moment, '
=> '',

'Configure Splash Page'
=> '',

'You need to be member of this group to view the contents'
=> 'Du musst Mitglied dieser Gruppe sein um die Inhalte zu sehen.',

'Networks are disabled.'
=> 'Netzwerk Funktion deaktiviert.',

'Network spawning disabled.'
=> 'Estellen von Netzwerken nicht aktiviert.',

'Create Network - %s'
=> 'Netzwerk erstellen - %s',

'There was a problem:<br>No message(s) selected. Please select at least one '
.'message and try again.'
=> 'Keine Nachricht ausgewählt, bitte mindestens eine Nachricht auswählen.',

'There was a problem:'
=> 'Es ist ein Fehler aufgetreten:',

'No folder selected. Please select a folder and try again.'
=> 'Kein Ordner ausgewählt.',

'No message(s) selected. Please select at least one message and try again.'
=> 'Keine Nachrichten ausgewählt. Bitte mindestens eine Nachricht auswählen.',

'%s - %s'
=> '',

'page_name'
=> '',

' updated successfully'
=> ' erfolgreich geändert.',

'%s - Edit your profile - %s'
=> '%s - Profil bearbeiten - %s',

'Sorry! you are not authorized to view content of this page'
=> 'Du bist nicht autorisiert den Inhalt dieser Seite zu sehen',

'File '
=> 'Datei ',

' loaded successfully.'
=> ' erfolgreich geladen.',

'Click "Save" button to save new settings.'
=> '\'Sichern\' klicken um die Änderungen zu speichern.',

'Default settings sucessfully restored.'
=> 'Standard Einstellungen erfolgreich wiederhergestellt.',

'User default Notifications Settings successfully updated.'
=> 'Standard Benachrichtigungs Einstellungen erfolgreich gespeichert.',

'%s Events'
=> '%s Ereignisse',

'Data mapping error. Invalid data format.'
=> 'Daten ZUprdniungs Fehler: ungültiges Daten Format.',

'-no email address-'
=> '-keine Email Adresse-',

'Current %s'
=> 'Derzeitiges %s',

'Current Logo'
=> 'Derzeitiges Logo',

'Upload %s'
=> '%s hochladen',

'Your file is too large for the web server.  The largest file you can upload '
.'here is %.1fM.  If this is too small, please ask the administrator to '
.'increase the <code>upload_max_filesize</code> directive in <code>php.ini</'
.'code>.'
=> 'Die Datei war zu gross. Die maximale Grösse ist %.1fM.',

'The uploaded file was only partially uploaded.'
=> 'Datei wurde nur teilweise hochgeladen.',

'No file was uploaded'
=> 'Keine datei hochgeladen.',

'File %s not uploaded correctly.'
=> 'Datei %s wirde nicht korrekt hochgeladen.',

'File is not uploaded correctly.'
=> 'Datei wurde nicht korrekt hochgeladen.',

'File too large; %s file uploads are limited to %s.  If this is too small, '
.'please ask the administrator to increase the limit.'
=> 'Datei zu gross. %s Dateien dürfen maximal %s gross sein.',

'Invalid image file.'
=> 'Ungültige Bild Datei.',

'Invalid media file.'
=> 'Ungültige Medien Datei.',

'Invalid document type - supported formats are: %s'
=> 'Unzulässiges Datei Format: Zulässige Formate sind: %s',

'File error: File already exists'
=> 'Datei Fehler: Datei existiert bereits',

'Security error: File %s is not an uploaded file:'
=> 'Sicherheits Fehler: Datei %s ist keine hochgeladene Datei.',

'XML parsing error!'
=> 'XML Fehler!',

'Data not found or XML parsing error!'
=> 'Keine Daten gefunden oder XML Fehler!',

'Can\'t get data from URL. Please, check the given URL.'
=> 'Konnte keine Daten von der URL laden, bitte überprüfe die URL.',

'Can\'t open file \''
=> 'Kann Datei nicht öffnen ',

'File'
=> 'Datei',

'doesn\'t exist.'
=> 'existiert nicht.',

'No data! Check if file is empty.'
=> 'Keine Daten, überprüfe ob die Datei leer ist.',

'Network directory'
=> 'Netzwerkverzeichnis',

'JOIN Network'
=> 'Mitglied werden',

'Unjoin Network'
=> 'Mitgliedschaft beenden',

'Create a network'
=> 'Netzwerk erstellen',

'Home'
=> 'Start',

'Orgs'
=> 'Organisationen',

'Neighbors'
=> 'Nachbarn',

'My Widgets'
=> 'Meine Widgets',

'My Messages'
=> 'Meine Nachrichten',

'My Friends'
=> 'Meine Freunde',

'My Forum'
=> 'Mein Forum',

'My Points'
=> 'Meine Punkte',

'My Family'
=> 'Meine Familie',

'Edit My Account'
=> 'Meine Mitgliedschaft bearbeiten',

'Find %s'
=> '%s finden',

'My friends'
=> 'Meine Freunde',

'Friends gallery'
=> 'Freunde Gallerie',

'Family Homepage'
=> 'Familien Homepage',

'Create'
=> 'Erstellen',

'%s Home'
=> '%s Start',

'%s Forum'
=> '%s Forum',

'%s Gallery'
=> '%s Gallerie',

'Join'
=> 'Mitglied werden',

'Unjoin'
=> 'Mitgliedschaft beenden',

'Are you sure you want to delete this group'
=> 'Bist du sicher, dass du diese Gruppe löschen willst?',

'Email Notification'
=> 'Email Benachrichtigung',

'Set Feature Network'
=> '',

'Manage Emblem'
=> '',

'Personalized Video'
=> '',

'Top Bar Enable/Disable'
=> 'Oberste Menuleiste an/aus',

'User Defaults'
=> 'Benutzer Standardeinstellungen',

'Relationships'
=> 'Beziehungen',

'Manage Contents'
=> 'Inhalte verwalten',

'Customize UI'
=> 'Layout anpassen',

'Home Page'
=> 'Startseite',

'User Default Page'
=> 'Benutzer Standardseite',

'Group Directory Page'
=> 'Gruppen Verzeichnisseite',

'Network Directory Page'
=> 'Netzwerk Verzeichnisseite',

'Send a message'
=> 'Eine Nachricht senden',

'Change Relation'
=> 'Beziehung ändern',

'Delete as %s'
=> 'Löschen als %s',

'Are you sure you want to delete this Relationship?'
=> 'Bist du sicher, dass du diese Beziehung löschen willst?',

'Add as %s'
=> 'Hinzufügen als %s',

'%s function expects string as first argument.'
=> '',

'Malicious or unauthorized activities detected. If you think this is an '
.'error, '
=> '',

'First'
=> 'Erste',

'Last'
=> 'Letzte',

'Could not retrieve file from URL: %s'
=> 'Konnte Datei nicht laden von URL: %s',

'User ID or Password field can\'t be blank.'
=> 'User ID oder Passwort Feld kann nicht leer sein.',

'Invalid or missing SOAP XML file'
=> 'Ungültige oder fehlende SOAP XML Datei',

'Invalid response received from'
=> 'Ungültige Antwort erhalten von',

'Invalid XML response received from'
=> 'Ungültige XML Antwort erhalten von',

'BinarySecurityToken not found in XML response received from'
=> 'BinarySecurityToken nicht gefunden in der XML Antwort von',

'Can\'t estabilish WEB connection.'
=> 'Kann keine WEB Verbindung herstellen.',

'Unknown communication error has occured.'
=> 'Unbekannter Kommunikationsfehler aufgetreten.',

'Communication error - no response received.'
=> 'Kommunikationsfehler: keine Antwort erhalten.',

'AdrBook: Invalid response received from'
=> 'AdrBook: Ungültige Antwort erhalten von',

'no name'
=> 'kein Name',

'no email'
=> 'keine Email',

'Plaxo data parser error.'
=> 'Fehler im Plaxo Daten Parser.',

'Invalid Plaxo Header received.'
=> 'Ungültige Antwort von Plaxo erhalten.',

'Unable to get list of the Plaxo folders.'
=> 'Konnte die Liste der Plaxo Ordner nicht holen.',

'Unable to read the Plaxo folders.'
=> 'Konnte die Plaxo Ordner nicht lesen.',

'Sorry - you are not logged in or you have been logged out due to inactivity. '
.'Please, log in again.'
=> 'Du bist nicht eingeloggt oder wurdest aufgrund von Inaktivität ausgeloggt. '
.'Bitte erneut einloggen.',

'Myself'
=> 'Ich',

'Everyone'
=> 'Jeder',

'Friends Only'
=> 'Nur Freunde',

'In Family'
=> 'In der Familie',

'Network name'
=> 'Netzwerk Name',

'Network address'
=> 'Netzwek Adresse',

'Network tagline'
=> 'Gruppen Slogan',

'Group name'
=> 'Gruppen Name',

'Group description'
=> 'Gruppem Beschreibung',

'Group tag'
=> 'Gruppen Stichwörter',

'Select age'
=> 'Alter wählen',

'Under 10 years'
=> 'Unter 10 Jahren',

'11-20 years'
=> '11-20 Jahre',

'21-30 years'
=> '21-30 Jahre',

'31-40 years'
=> '31-40 Jahre',

'41-50 years'
=> '41-50 Jahre',

'Over 50 years'
=> 'Über 50 Jahre',

'Create Post'
=> 'Beitrag erstellen',

'Messages '
=> 'Nachrichten ',

'Edit my account'
=> 'Mein Profil bearbeiten',

'Tags:'
=> 'Stichwörter:',

'Installer will perform now a series of tests to determine the working '
.'environment of the server and the minimum conditions for a successful '
.'installation. Please do not interrupt this step of the installation process.'
=> '',

'Please wait...'
=> '',

'Please complete the following information to create an admin account.'
=> '',

'Admin username'
=> '',

'Admin password'
=> '',

'Admin email'
=> '',

'Invalid or empty user name.'
=> '',

'Your password must be at least %d characters long.'
=> '',

'Your password can not be longer than %d characters.'
=> '',

'Invalid or empty email field.'
=> '',

'Administrator account data sucessfully stored. Click \'Next\' please...'
=> '',

'Please complete the following information if you have already created a '
.'database for People Aggregator application.'
=> '',

'or you can provide bellow MySQL root username/password and People Aggregator '
.'will create a database for you.'
=> '',

'MySQL root username'
=> '',

'MySQL root password'
=> '',

'Please wait, trying to connect to the database.'
=> '',

'Creating the Database'
=> '',

'Congratulations!'
=> '',

'%s - My Links - %s'
=> '%s - Meine Links - %s',

'Group deleted successfully'
=> 'Gruppe erfolgreich gelöscht',

'%s groups deleted successfully'
=> '%s Gruppen erfolgreich gelöscht',

'Question is set for all users'
=> 'Frage ist für alle User eingestellt',

'Please select a question to activate.'
=> 'Bitte eine Frage zur Aktivierung auswählen.',

'Question has been successfully saved'
=> 'Frage wurde erfolgreich gespeichert',

'Fields marked with * must not be left empty'
=> 'Felder die mit * markiet sind dürfen nicht leer bleiben',

'Question has been deleted successfully'
=> 'Frage wurde erfolgreich gelöscht',

'Caption has already been taken, please enter a different caption'
=> 'Titel ist schon vergeben, bitte einen anderen Titel angeben.',

'Successfully updated'
=> 'Erfolgreich geändert',

' is already enabled at specified orientation'
=> ' ist schon an der angegeben Position aktiviert.',

'Please select atleast one user.'
=> 'Bitte mindestens einen User auswählen.',

'Status of selected user(s) updated successfully'
=> 'Status der ausgewählten User erfolgreich geändert.',

'An error has occured on deleting users.'
=> 'Beim Löschen der User ist ein Fehler aufgetreten.',

' uploaded successfully.'
=> 'erfolgreich hochgeladen.',

'Please confirm network deletion by selecting deletion checkbox.'
=> 'Bitte das Löschen des Netzwerks durch anhaken des \'Löchen\' Kästchens.',

'Network Statistics - %s'
=> 'Netzwerk Daten - %s',

'General Network Settings'
=> 'Allgemeine Netzwerk Daten',

'Administration panel'
=> 'Administrations Seite',

'Following relations could not be added as default relation '
=> 'Folgende Personen konnten nicht als Standard Beziehungen gespeichert werden: ',

'Default settings for the network has been saved'
=> 'Standard Einstellungen für das Netzwerk wurden gespeichert',

'Click "Save" button to store new settings.'
=> 'Auf "Sichern" klicken um die neuen Einstellungen zu sichern',

'Date range selected is invalid, so it has been ignored in searching'
=> 'Datums Bereich war ungültig und wurde daher für die Suche ignoriert',

'Your comment contains some illegal characters. Please try again.'
=> 'Der Kommentar enthält unerlaubte Zeichen.',

'Comment can not be left blank'
=> 'Kommentar darf nicht leer sein.',

'Sorry, your comment cannot be posted as it looks like spam. Try removing any '
.'links to possibly suspect sites, and re-submitting.'
=> 'Der Kommentar konnte nicht gespeichert werden, da er wie Spam aussieht, oder '
.'Links zu Seiten in der Blacklist enthält. Bitte überprüfe die Links in dem '
.'Kommentar, und stelle sicher, dass Name und Email korrekt sind.',

'Your comment has been posted successfully'
=> 'Der Kommentar wurde erfolgreich gepostet.',

'Sorry, your comment cannot be posted as it was classified as spam by '
.'Akismet, or contained links to blacklisted sites.  Please check the links in '
.'your post, and that your name and e-mail address are correct.'
=> 'Der Kommentar konnte nicht gespeichert werden, da er von Akismet als Spam '
.'klassifiziert wurde, oder Links zu Seiten in der Blacklist enthält. Bitte '
.'überprüfe die Links in dem Kommentar, und stelle sicher, dass Name und Email '
.'korrekt sind.',

'Sorry, your comment cannot be posted as it was classified as spam by '
.'Akismet, or contained links to blacklisted sites. Please check the links in '
.'your post, and that your name and e-mail address are correct.'
=> 'Der Kommentar konnte nicht gespeichert werden, da er von Akismet als Spam '
.'klassifiziert wurde, oder Links zu Seiten in der Blacklist enthält. Bitte '
.'überprüfe die Links in dem Kommentar, und stelle sicher, dass Name und Email '
.'korrekt sind.',

'Terms and Conditions - %s'
=> 'Benutzungsbedingungen',

'basecamp test disabled'
=> '',

'please enter your basecamp login details above.'
=> '',

'scraping contacts page to get companies'
=> '',

'getting list of people from company '
=> '',

' who are working on this project'
=> '',

'testing ImageResize module with engine'
=> '',

'make sure to hit ctrl-F5 after clicking, to clear the cache'
=> '',

'flushing cache'
=> '',

'done'
=> '',

'expanding and cropping 135x75 to fit inside 300x300'
=> '',

'reduce only'
=> '',

'fitting 135x75 inside 300x300'
=> '',

'reduce only, smaller'
=> '',

'Report abuse'
=> 'Missbrauch melden',

'Comment'
=> 'Kommentar',

'Submit Abuse'
=> 'Missbrauch melden',

'Right-click to download'
=> 'Mit Rechtsklick downloaden',

'Overall Rating'
=> 'Gesamt Wertung',

'Your Rating'
=> 'Deine Bewertung',

'Please'
=> 'Bitte',

'log in'
=> 'einloggen',

'to rate this audio'
=> 'um dieses Audio zu bewerten',

'to rate this post'
=> 'um diesen Beitrag zu bewerten',

'Are you sure you want  to post the comment?'
=> 'Bist du sicher, dass du diesen Kommentar posten willst?',

'Leave a Comment'
=> 'Kommentieren',

'Submit Comment'
=> 'Kommentar posten',

'Are you sure you want to post the comment?'
=> 'Bist du sicher, dass du diesen Kommentar posten willst?',

'posted by %s on %s'
=> 'erstellt von %s am %s',

'permalink'
=> 'Permalinl',

'comments'
=> 'Kommentare',

'Unknown error.'
=> 'Unbekannter Fehler.',

'Detailed information has been written into the error log.'
=> '',

'Begins'
=> 'Beginnt',

'Click here to go back to the Home page'
=> '',

'&copy;'
=> '',

'Already a member?'
=> 'Schon Mitglied?',

'Login now'
=> 'Einloggen',

'or'
=> 'oder',

'Register'
=> 'Anmelden',

'shortcuts'
=> '',

'logoff'
=> 'Ausloggen',

'to rate this image'
=> 'um dieses Bild zu bewerten',

'Network is temporarily closed. We apologize for any inconvenience and thank '
.'you for your patience as we improve the system. Please try after some time. '
.'Currently, only site administrator can login.'
=> '',

'view all'
=> 'Alle anzeigen',

'%s Networks'
=> '%s Netzwerke',

'to rate this video'
=> '',

'Showing profile fields in sidebar widget.'
=> '',

'peopleaggregator: widgetization testbench'
=> '',

'Select a module'
=> '',

'Module'
=> '',

'Request'
=> '',

'Response'
=> '',

'Rendered response'
=> '',

'An unknown error occurred - no response available.'
=> '',

'Note: do not enable widgetization on public facing webservers as it allows '
.'operations to be performed as arbitrary users! Access must be restricted to '
.'trusted front-end systems.'
=> '',

'This file may not be called directly.'
=> '',

'No admininstrator password configured'
=> '',

'To use the updater, add a line like this to'
=> '',

'Log in'
=> '',

'All the files have been updated. Now you need to'
=> '',

'click here to update the database'
=> '',

'and the update will be complete'
=> '',

'Error occurred running database update:'
=> '',

'PeopleAggregator system update'
=> '',

'%s - Media Gallery - %s'
=> '%s - Medien Gallerie - %s',

'View All Members'
=> 'Alle Mitglieder anzeigen',

'View All Group Members'
=> 'Alle Gruppen Mitglieder anzeigen',

'Comment can not be empty'
=> '',

'Please login to comment'
=> '',

'Your Recommendation: '
=> '',

'Error processing request'
=> '',

'Error parsing URL'
=> 'Fehler bein parsen der URL.',

'Ad Title can not have empty.'
=> 'Anzeigen Titel kann nicht leer sein.',

'Ad Target page is not specified.'
=> 'Keine Seite für die Anzeige spezifiziert.',

'attributes'
=> 'Attribute',

'middle'
=> 'Mitte',

'Date Established'
=> 'Gründungsdatum',

'Postal Code'
=> 'Postleitzahl',

'Phone Number'
=> 'Telefon',

'Honors / Awards'
=> 'Ehren / Auszeichnungen',

'Supporter'
=> 'Unterstützer',

'Customer'
=> 'Kunde',

'Employee'
=> 'Angestellter',

'Religion / Faith'
=> 'Religion / Glauben',

'Congregational member'
=> 'Gemeinde Mitglied',

'Church member'
=> 'Kirchen Mitglied',

'Church goer'
=> 'Kirchgänger',

'Date the Family was formed'
=> 'Datum der Familiengrümdung',

'City of Origin'
=> 'Geburtsstadt',

'Grand Parent'
=> 'Grosselter',

'Relative'
=> 'Verwandter',

'Child'
=> 'Kind',

'owner'
=> 'eigentümer',

'admin'
=> 'admin',

'banned'
=> 'gesperrt',

'limited'
=> 'eingeschränkt',

'Group moderation'
=> 'Gruppen Moderation',

'My messages'
=> 'Meine Nachrichten',

'Cannot create networks: this installation is not configured for network '
.'operation.'
=> 'Kann Netwerk nicht erstelen da diese funktion hier nicht verfügbar ist.',

'Cannot create networks: %s is not writable'
=> 'Kann Netzwerk nicht erstellen: %s ist nicht schreibbar',

'Cannot create networks: Network spawning has been disabled on this '
.'installation.'
=> 'Kann Netwerk nicht erstelen da diese funktion hier nicht verfügbar ist.',

'Files with extension \'%s\' may not be uploaded'
=> 'Dateien mit der Endung\'%s\' dürfen nicht hochgeladen werden.',

'Unable to determine image type'
=> 'Konnte Bild Format nicht feststellen.',

'File MIME type is %s, expected %s'
=> 'MIME type der datei ist %s, erwartet wurde %s.',

'E-mail address is not valid.'
=> 'Ungültige Email Adresse.',

'The domain of your E-mail address is not in the list of allowed domains.'
=> 'Die Domain der Email Adresse ist nicht in der Liste der erlaubten Damains.',

'\n'
.'The password must be less than %d characters.'
=> '\n'
.'Das Passwort muss weniger als %d Zeichen haebn.',

'\n'
.'The password must be longer than %d characters.'
=> '\n'
.'Das Passwort muss mehr als %d Zeichen haebn.',

'Latest posts from %s'
=> 'Neueste Beiträge von %s',

'Newest posts from everyone on %s'
=> 'Neueste Beiträge von %s',

'%s: %s blog'
=> '%s: %s Blog',

'Failed to retrieve %s: %s'
=> 'Konnte %s nicht laden: %s',

);

?>