<?php

// This file is automatically generated from messages.po.  Do not edit it!

$TRANSLATED_STRINGS = array(

'About Me'
=> 'Über mich',

'About'
=> 'Über',

'User image.'
=> 'Nutzerbild',

'More Detail'
=> 'Details',

'Sex'
=> 'Geschlecht',

'State'
=> 'Bundesland',

'City'
=> 'Stadt',

'ZIP code'
=> 'PLZ',

'Country'
=> 'Land',

'Game Handle'
=> '',

'Hobbies'
=> 'Hobbies',

'Interests'
=> 'Interessen',

'No details entered yet.'
=> 'Noch keine Details eingegeben.',

'Actions'
=> 'Aktionen',

'Configure this Network'
=> 'Diese Netzwerk konfigurieren',

'logoff'
=> 'Logout',

'Login now'
=> 'Login',

'or'
=> 'oder',

'Register'
=> 'Anmelden',

'Activity Feed'
=> 'Aktivität',

'All'
=> 'Alle',

'My Groups'
=> 'Meine Gruppen',

'My Friends'
=> 'Meine Freunde',

'My Activities'
=> 'Meine Aktivitäten',

'My Activity Feeds'
=> 'Meine Aktivitäten',

'Activity Feeds'
=> 'Aktivitäten',

'Group Name'
=> 'Gruppen Name',

'Group Category'
=> 'Gruppen Kategorie',

'Tags'
=> 'Stichwürter',

'separated tags with commas'
=> 'Sticjwörter mit Komma trennen',

'Group Photo'
=> 'Gruppen Foto',

'Choose File'
=> 'Datei auswählen',

'Current Photo'
=> 'Derzeitiges Foto',

'Group Description'
=> 'Gruppen Beschreibung',

'Submit'
=> 'Abschicken',

'Send'
=> 'Senden',

'Message composed will be discarded. Do you want to continue?'
=> 'Erstellte Nachricht wird verworfen, ist das ok?',

'To'
=> 'An',

'select friend'
=> 'Freund auswählen',

'Subject'
=> 'Betreff',

'Message'
=> 'Nachricht',

'Cancel'
=> 'Abbrechen',

'You have not created any folders.'
=> 'Sie haben noch keine Ordner erstellt.',

'Have you...'
=> 'Hast du schon...',

'Joined up?'
=> 'Dich angemeldet?',

'Join Network'
=> 'Mitglied werden',

'Filled out your profile?'
=> 'Dein Profil ausgefüllt?',

'Edit Profile'
=> 'Profil bearbeiten',

'Posted your rigs?'
=> 'Deine Rigs gepostet?',

'Edit Rigs'
=> 'Rigs bearbeiten',

'Listed your games?'
=> 'Deine Spiele gelistet?',

'Edit Games'
=> 'Spiele bearbeiten',

'Profile'
=> 'Profil',

'Notifications'
=> 'Benschrichtigungen',

'My Rigs'
=> 'Meine Rigs',

'My Games'
=> 'Meine Spiele',

'Delete Account'
=> 'Account löschen',

'Current Photo '
=> 'Derzeitiges Foto',

'Current Image '
=> 'Derzeitiges Bild',

'Use as main pic'
=> 'As Hauptbild verwenden',

'Photo'
=> 'Photo',

'Name'
=> 'Name',

'Developer'
=> '',

'Publisher'
=> '',

'My Comments'
=> 'Mein Kommentar',

'Apply Changes'
=> 'Änderungen anwenden',

'Onknown POST action.'
=> '',

'Please enter a name for your Game.'
=> 'Bitte gib einen Namen für das Spiel ein',

'Please upload a valid Game Image in %s<br/>%s'
=> '',

'Your Game has been saved successfully!'
=> '',

'Club SLI Member'
=> 'Club SLI Mitglied',

'SLI Member Number'
=> 'SLI Mitgliedsnummer',

'Registration Date'
=> 'Datum der Registrierung',

'Avatar Photo Upload'
=> 'Avatar Foto Upload',

'Current Image'
=> 'Derzeitiges Bild',

'Remove Picture'
=> 'Bild entfernen',

'Email Address'
=> 'Email Adresse',

'Password'
=> 'Passwort',

'Confirm Password'
=> 'Passwort bestätigen',

'First Name'
=> 'Vorname',

'Last Name'
=> 'Nachname',

'Screen Name'
=> 'Screen Name',

'This name will be displayed throughout the system to other users. This does '
.'not affect your login.'
=> 'Dieser Name wird für alle anderen Benutzer der Seite angezeigt. Dies ist '
.'nicht dein Login Name.',

'Home Address 1'
=> 'Adresse 1',

'Home Address 2'
=> 'Adresse 2',

'State/Province'
=> 'Bundesland',

'Other state'
=> 'Anderes Bundesland',

'ZIP Code'
=> 'PLZ',

'Phone #'
=> 'Telefon Nummer',

'Male'
=> 'Männlich',

'Female'
=> 'Weiblich',

'Gender'
=> 'Geschlecht',

'Music'
=> 'Musik',

'Books'
=> 'Literatur',

'Movies'
=> 'Filme',

'You are not allowed to delete your account here. You can delete your account '
.'from meta organization only.'
=> '',

'If you delete your account, all your content posted will be deleted. Your '
.'complete information will be deleted from the network.'
=> '',

'To delete your account you have to check this box.'
=> 'Um dein Konto zu löschen musst du dieses Kästchen anklicken.',

'Delete My Account'
=> 'Mein Konto löschen',

'Current Desktop Image'
=> 'Derzeitiges Desktop Bild',

'Upload desktop image'
=> 'Desktop Bild hochladen',

'Image will appear on your public page'
=> 'Bild erscheint auf deinen Benutzer Seiten',

'Set image appearance'
=> 'Bild darstellungs-Optionen wählen',

'Images 1016 pixels wide by 191 pixels tall will give the best results.'
=> 'Bilder mit 1016x191 pixeln sind am besten geeignet.',

'Use desktop image?'
=> '',

'Select "yes" to turn on or "no" to turn off your custom desktop image.'
=> 'wähle ja oder nein um das Desktop Buld zu aktiveren oder de-akticieren.',

'Save'
=> 'Sichern',

'Restore Default Image'
=> 'Standard Desktio Bild wiederherstellen',

'Fields marked with * can not be empty, First name can not be empty.'
=> '',

'Fields marked with * can not be empty, Email field is mandatory.'
=> '',

'Password and confirm password should match.'
=> '',

'Password should be of %s characters or more.'
=> '',

'Password should be less than %s charcaters.'
=> '',

'Profile updated successfully.'
=> 'Profil erfolgreich aktualisiert.',

'Please select the image appearance'
=> '',

'Please select option for using desktop image'
=> '',

'Please upload a valid desktop image'
=> '',

'Please upload a valid Rig Image in %s'
=> '',

'Games'
=> 'Spiele',

'Add New Game'
=> '',

'Game Title'
=> '',

'My Score'
=> '',

'Enter any positive number between 1 and 100.'
=> '',

'Comments'
=> 'Kommentare',

'Remove'
=> 'entfernen',

'I want to receive  notifications when'
=> '',

'via my registered email'
=> 'über meine registrierte Email Adresse',

'via my account inbox'
=> 'über meine Konto InBox',

'Notify \'messages waiting\''
=> '',

'through my registered mail'
=> '',

'\'messages waiting\' notifications in my mail box, when new messages arrive'
=> '',

'Restore default settings'
=> '',

'Update Now!'
=> '',

'Ok to submit?'
=> '',

'To update your hardware info, you will be asked to install the SHIMGen '
.'ActiveX control or JavaApplet. Do you want to proceed?'
=> '',

'Update Hardware Info'
=> '',

'Start'
=> 'Start',

'Benchmarks'
=> 'Benchmarks',

'3DMark 05 Score'
=> '',

'3DMark 05 Link'
=> '',

'3DMark 06 Score'
=> '',

'3DMark 06 Link'
=> '',

'3DMark Vantage (Performance)'
=> '3DMark Vantage (Performance)',

'3DMark Vantage Link'
=> '',

'Case'
=> 'Gehäuse',

'Brand'
=> 'Marke',

'Model'
=> 'Modell',

'Cooling'
=> 'Kühlung',

'Lighting'
=> 'Beleuchtung',

'Modifications'
=> 'Modifikationen',

'Operating System'
=> 'Betriebssystem',

'Version'
=> 'Version',

'CPU'
=> 'CPU',

'Manufacturer'
=> 'Hersteller',

'Code Name'
=> 'Code Name',

'Core Count'
=> 'Anzahl Cores',

'Stepping'
=> 'Stepping',

'CPU Settings'
=> '',

'Stock BusSpeed'
=> '',

'Current BusSpeed'
=> '',

'Stock Multiplier'
=> '',

'Current Multiplier'
=> '',

'Stock Core Clock'
=> '',

'Current Core Clock'
=> '',

'Stock Core Voltage'
=> '',

'Current Core Voltage'
=> '',

'Is HT Enabled'
=> '',

'CPU Cooling'
=> '',

'Motherboard'
=> '',

'Type'
=> 'Art',

'BIOSVendor'
=> '',

'BIOSVersion'
=> '',

'ChipsetName'
=> '',

'Motherboard Cooling'
=> '',

'Graphics Cards'
=> '',

'Display Device'
=> '',

'GPU Settings'
=> '',

'Stock Shader Clock'
=> '',

'Current Shader Clock'
=> '',

'Stock Memory Clock'
=> '',

'Current Memory Clock'
=> '',

'Voltage'
=> '',

'Memory Size'
=> '',

'GPU Cooling'
=> '',

'Display Driver'
=> '',

'Memory'
=> '',

'Size'
=> 'Grösse',

'Part #'
=> '',

'Memory Settings'
=> '',

'Stock Speed'
=> '',

'Current Speed'
=> '',

'Stock Timings (CL-tRCD-tRP-tRAS)'
=> '',

'Current Timings (CL-tRCD-tRP-tRAS)'
=> '',

'Stock Bank Cycle Time (tRC)'
=> '',

'Current Bank Cycle Time (tRC)'
=> '',

'Stock Command Rate (CR)'
=> '',

'Current Command Rate (CR)'
=> '',

'Stock Voltage'
=> '',

'Current Voltage'
=> '',

'Memory Cooling'
=> '',

'Total Memory'
=> '',

'Memory available'
=> '',

'Number of DIMMs'
=> '',

'Power Supply'
=> '',

'Max Wattage'
=> '',

'Modular?'
=> '',

'Sound Card'
=> '',

'Monitor'
=> '',

'Max Resolution'
=> '',

'Response time'
=> '',

'Refresh Rate'
=> '',

'Hard Drive 1'
=> '',

'Capacity'
=> '',

'Speed'
=> '',

'Raid'
=> '',

'Optical Drive 1'
=> '',

'Accessories'
=> '',

'Mouse'
=> '',

'Keyboard'
=> '',

'Other'
=> 'Andere',

'Please enter a name for your Rig.'
=> '',

'Please upload a valid Image in %s<br/>%s'
=> '',

'Your Rig has been saved successfully!'
=> '',

'You cannot add an Event to the calendar of group %s, as you are not a member.'
=> 'Du kannst dieses Ereignis nicht der Gruppe %s hinzufügen, weil du kein '
.'Mitglieded bist.',

'Couldn\'t create event:'
=> 'Konnte das Ereignis nicht erzeugen:',

'Couldn\'t create EventAssociation:'
=> '',

'There was a problem updating the event:'
=> 'Es gab ein Problem bein Aktualisieren des ereignisses:',

'Event %d doesn\'t exist'
=> 'Ereignis %d existiert nicht.',

'Couldn\'t update the event:'
=> 'Konnte das Ereignis nicht aktualisieren',

'There was a problem deleting the event:'
=> 'Es gab ein Problem beim Löschen des Ereignisses.',

'The event has been deleted.'
=> 'Das Ereignis wurde gelöscht.',

'Couldn\'t delete the event:'
=> 'Konnte das ereignis nicht löschen:',

'No users given'
=> '',

'There was a problem associating the event:'
=> '',

'%s is not a user'
=> '%s ist kein Benutzer',

'Add people:'
=> 'Leute hinzufügen:',

'You cannot add an Event to the caledar of group %s, as you are not a member.'
=> '',

'Add group:'
=> 'Gruppe hinzufügen:',

'You may not remove the association to this event.'
=> '',

'You cannot remove yourself from this event, as you created it.  Please use '
.'\'Delete Event\' instead.'
=> '',

'Unknown event association'
=> 'Unbekannte ereignis Verknüpfung',

'Events'
=> 'Ereignisse',

'My Events'
=> 'Meine Ereignisse',

'Personal Events'
=> 'Persönliche Ereignisse',

'Rig Photo'
=> 'Rig Foto',

'Game Photo'
=> '',

'This Game was nominated Game of the Month %s'
=> 'Dieses Spiel wurde zum Spiel des Monats %s nominiert',

'There has not been a Game of the Month nominated yet.'
=> '',

'SLI Game of the Month'
=> 'SLI Spiel des Monats',

'Members'
=> 'Mitglieder',

'Category'
=> 'Kategorie',

'Founded'
=> 'Gegründet',

'Owner'
=> 'Eigentümer',

'Gallery'
=> 'Gallerie',

'Recent Media'
=> 'Aktuelle Medien',

'Group Gallery'
=> 'Gruppen Gallerie',

'My Gallery'
=> 'Meine Gallerie',

'Images'
=> 'Bilder',

'Video'
=> 'Video',

'Audio'
=> 'Audio',

'No images have been published yet.'
=> 'Es sind noch keine Bilder veröffentlicht worden.',

'No videos have been published yet.'
=> 'Es sind noch keine Videos veröffentlicht worden.',

'No audio has been published yet.'
=> 'Es ist noch kein Audio veröffentlicht worden.',

'Edit Game of the Month'
=> '',

'Please enter a name for the Game of the Month.'
=> '',

'Next Month'
=> 'Nächster Monat',

'This Month'
=> 'Dieser Monat',

'Last Month'
=> 'Vergangener Monat',

'Post a new Rig'
=> 'Neues Rig posten',

'Edit Rig'
=> 'Rig bearbeiten',

'Make this the Rig of the Month'
=> '',

'Over Clocked'
=> '',

'Water Cooled'
=> '',

'Modified Case'
=> '',

'Lights and LEDs'
=> '',

'CPU Type'
=> '',

'CPU Speed'
=> '',

'RAM'
=> '',

'No Rigs have been voted on yet.'
=> 'Es wurden noch keine Rigs bewertet.',

'Manage Rig of the Month'
=> 'Rig des Monats verwalten',

'Make Rig of the Month'
=> '',

'Do you want to reset all Rig votes?'
=> '',

'Reset now!'
=> '',

'Manage Rig Votes'
=> '',

'Description'
=> 'Beschreibung',

'Link Title'
=> 'Link Titel',

'Link URL'
=> 'Link URL',

'Edit Rig of the Month'
=> '',

'Please enter a name for the Rig of the Month.'
=> 'Bitte gib einen Namen für das Rig des Monats ein.',

'Media file has been deleted from album or gallery.'
=> '',

'Author of this content is no longer a member of this group'
=> '',

'Edit'
=> 'Bearbeiten',

'Return to %s'
=> 'Zurück zu %s',

'Return to %s gallery'
=> 'Zurück zur %s Gallerie',

'Return to %s\'s gallery'
=> 'Zurück zu %ss Gallerie',

'%s\'s Page'
=> '%ss Seite',

'My Page'
=> 'Meine Seite',

'find People'
=> 'Leute finden',

'Post new Game'
=> 'Neues Spiel posten',

'Groups'
=> 'Gruppen',

'My Links'
=> 'Meine Links',

'Links'
=> '',

'Post new Rig'
=> '',

'Rigs'
=> 'Rigs',

'Configure'
=> 'Konfigurieren',

'Settings'
=> '',

'Network settings'
=> '',

'Manage Rig votes'
=> '',

'Manage Game of the Month'
=> '',

'Ad center'
=> '',

'Manage ad center'
=> '',

'Textpads'
=> '',

'Manage Textpads'
=> 'Textpads verwalten',

'Configure Email'
=> '',

'Meta network'
=> '',

'Set featured network'
=> '',

'Manage emblems'
=> '',

'Manage splash'
=> '',

'Showcased networks'
=> '',

'Network of Moment'
=> '',

'Video Tours'
=> '',

'Server Announcement'
=> '',

'Register Today'
=> '',

'Take a Tour Video'
=> '',

'MIS Reports'
=> '',

'Usage'
=> '',

'Counts'
=> '',

'Marketing reports'
=> '',

'Page Customization'
=> '',

'Theme selector'
=> '',

'Module selector'
=> '',

'Background image'
=> '',

'Header image'
=> '',

'Customize theme'
=> '',

'User defaults'
=> '',

'Default settings'
=> '',

'Relationship settings'
=> '',

'Users Settings'
=> '',

'Create users'
=> '',

'Manage users'
=> '',

'Moderate users'
=> '',

'Content'
=> 'Inhalt',

'Moderate contents'
=> '',

'Manage contents'
=> '',

'Manage forums'
=> '',

'Manage comments'
=> '',

'Manage links'
=> '',

'Network links'
=> '',

'Manage Profanity'
=> '',

'Profane Word List'
=> '',

'Manage Signup Access'
=> '',

'Manage Domain Names'
=> '',

'Manage Events'
=> '',

'Network Events'
=> '',

'Manage Questions'
=> '',

'Manage Groups'
=> 'Gruppen verwalten',

'Manage Category'
=> 'Kategorie verwalten',

'Bulletins'
=> 'Bulletins',

'Email notifications'
=> '',

'Roles'
=> '',

'Manage Roles & Tasks'
=> '',

'Manage Tasks Relationship'
=> '',

'Poll'
=> '',

'Select Poll'
=> '',

'Create Poll'
=> '',

'Points'
=> '',

'Manage Ranking points'
=> '',

'Static Pages'
=> '',

'Manage Footer Links'
=> 'Links der Fusszeile verwalten',

'Manage Static Pages'
=> '',

'Newest Rigs'
=> 'Neueste Rigs',

'no data'
=> 'keine Daten',

'Add as'
=> 'Hinzufügen als',

'Advanced Search'
=> 'Erweiterte Suche',

'Simple Search'
=> 'Einfache Suche',

'Recent Users'
=> 'Aktuelle Benutzer',

'Alphabetical'
=> 'Alfabetisch',

' with picture in profile'
=> 'mit Bild im Profil',

'Select rows'
=> 'Wähle Zeilen',

'Search'
=> 'Suche',

'Enter Name here'
=> 'Hier Namen eingeben',

'Find Users'
=> 'Benutzer finden',

'Any'
=> 'Beides',

'Company Name'
=> 'Firmen Name',

'Industry'
=> 'Branche',

'Friend'
=> 'Freund',

'Attach Media'
=> 'Medien Datein anhängen',

'Title'
=> 'Titel',

'Add Image or Video'
=> '',

'Separate tags with commas'
=> 'Stichwörter mit Kammas trennen',

'Recent Comments'
=> 'Neueste Kommentare',

'No title'
=> '',

'Author'
=> 'Autor',

'No comments posted yet.'
=> 'Noch keine Kommentare erstellt.',

'Sorry, your GFX card does not seem to be SLI enabled. You can\'t join.'
=> '',

'You will have to let the SHIM ActiveX or Java Plugin be installed, It will '
.'detecht if your computer is SLIEnabled, You can only join %s if you have '
.'hardware that meets the requirements.'
=> 'Du musst die Installation des SHIM ActiveX oder Java Applets zulassen. Es '
.'wird überprpfen ob dein Computer SLIEnabled ist. Du kannst nur Mitglied von %'
.'s werden, wenn dein Computer die erfoderliche SLI Hardware hat.',

'Cool! Your hardware is SLI enabled. Click ok to sign up!'
=> 'Cool! Deine Hardware ist SLI enabled, Klicke OK um dich anzumelden!',

'Test Now!'
=> 'Jetzt testen!',

'Test if you have SLI enabled hardware?'
=> 'Teste ob du SLI enabled Hardware hast?',

'Welcome to %s!'
=> 'Willkommen zu %s!',

'With your %s account you will be able to:'
=> 'Mit deinem %s Account kannst du:',

'Edit, share and store all your digital stuff in one place.'
=> 'All deine digitalen Dinge an einem Ort bearbeiten, speichern und mit snderen '
.'teilen.',

'Manage all your friends, groups and content.'
=> 'All deine Freunde, Gruppen und Inhalte verwalten.',

'Unite your online life by connecting all your presences together.'
=> 'Dein online Leben vereinheitlichen indem di hier alle dein Präsenzen '
.'zusammenfügst.',

'Provide the following information to join and start connecting all your '
.'digital worlds!'
=> 'Bitte mache die folgenden Angaben um Mitglied zu werden!',

'Login name'
=> 'Login Name',

'Login name may contain letters, numbers and underscores (_).'
=> 'Der Login Name kann Buchstaben, Zahlen und Unterstriche (_) enthalten',

'First name'
=> 'Vorname',

'Last name'
=> 'Nachname',

'Screen name'
=> '',

'This name will be what others users see and can be changed at any time.'
=> '',

'Date of birth'
=> 'Geburtsdatum',

'Street address 1'
=> 'Adresse 1',

'Street address 2'
=> 'Adresse 2',

'Password can be 5-15 characters long, and is case sensitive.'
=> 'Das PAsswort kann 5-15 Zeichen lang sein und die Gross-/Kleinschreibung ist '
.'wichtig',

'Confirm password'
=> 'Passwort bestätigen',

'Email'
=> 'Email',

'Your photo'
=> 'Dein Foto',

'To use a different image, click Browse or enter a URL below.'
=> '',

'Upload a photo'
=> 'Ein Foto hochladen',

'Or enter a photo URL'
=> '',

'Preview Image'
=> 'Bildvorschau',

'Clear Image'
=> 'Bild löschen',

'To use a different image, click Clear Image and select a new image.'
=> 'Um ein anderes Foto zu benutzen, klicke \'Bild löschen\' und wähle ein anderes',

'I have read and agree to the %s <a href=\'%s/terms.php\' target=\'_blank\'>Terms '
.'and Conditions</a>'
=> 'I habe die %s <a href=\'%s/terms.php\' target=\'_blank\'>AGBs</a> gelsen und '
.'akzeptiere sie.',

'Join now'
=> 'Jetzt Mitglied werden',

'SHIM Plug-in not loaded yet.'
=> '',

'Show detected hardware data (SHIM)'
=> '',

'Submit this data.'
=> '',

'My '
=> '',

'There has not been a Rig of the Month nominated yet.'
=> '',

'SLI Rig of the Month'
=> 'SLI Rig des Monats',

'Invalid Rig ID'
=> '',

'Rig Permalink'
=> 'Rig Permaliink',

'This Rig was nominated Rig of the Month %s'
=> 'Dieses Rig wurde zum Rig des Monats %s nominiert',

'average vote: %1$s, %2$s votes total'
=> 'Durchschnittliche Bewertung: %1$s, %$2s Bewertugen gesamt',

'Your current vote'
=> 'Deine derzeitige Bewertung',

'1 star'
=> '1 Stern',

'2 stars'
=> '2 Sterne',

'3 stars'
=> '3 Sterne',

'4 stars'
=> '4 Sterne',

'5 stars'
=> '5 Sterne',

'Your rating'
=> 'Deine Bewertung',

'Your comment'
=> 'Dein Kommentar',

'Post vote'
=> 'Bewertung posten',

'said:'
=> 'sagte:',

'Rig Votes'
=> 'Rig Bewertungen',

'Please rate the Rig from 1 to 5 stars.'
=> 'Bitte bewerte das Rig mit 1 bis 5 Sternen.',

'Rate'
=> 'Bewerten',

'Top Rigs'
=> 'Top Rigs',

'Contents'
=> 'Inhalt',

'Date range selected is invalid, so it has been ignored in searching'
=> 'Datums Bereich war ungültig und wurde daher für die Suche ignoriert',

'Please enter either data or date to search'
=> 'Bitte entweder Datums- oder Textsuche eingeben ',

'%s\'s Group Blog'
=> '%ss Gruppen Blog',

'Create post'
=> 'Beitrag erstellen',

'Manage posts'
=> 'Beiträge verwalten',

'Showing results for tag %s.'
=> 'Ergebnisse für Stichwort %s.',

'Invite'
=> 'Einladen',

'Group Settings'
=> 'Gruppeneinstellungen',

'Moderate'
=> 'Moderieren',

'Manage content'
=> 'Inhalt verwalten',

'Join this group'
=> 'Dieser Gruppe beitreten',

'No content found.'
=> 'Kein Inhalt gefunden',

'Click <a href="%s">here</a> to add content.'
=> '',

'Link'
=> 'Link',

'Top Games'
=> 'Top Spiele',

'View all Members'
=> 'Alle Mitglieder anzeigen',

'who'
=> 'die',

'View All %s Members'
=> 'Zeige alle %s Mitglieder',

'Configure this network'
=> 'Dieses Netzwerk konfigurieren',

'Invite a Friend'
=> 'Freund einladen',

'3DMark 05'
=> '3DMark 05',

'3DMark 06'
=> '3DMark 06',

'Return to home network'
=> 'Zurück zum Haupt-Netzwerk',

'Network directory'
=> 'Netzwerkverzeichnis',

'JOIN Network'
=> 'Mitglied werden',

'Unjoin Network'
=> 'Mitgliedschaft beenden',

'Create a network'
=> 'Netzwerk erstellen',

'Home'
=> 'Start',

'People'
=> 'Mitglieder',

'Directory'
=> 'Verzeichnis',

'My Messages'
=> 'Meine Nachrichten',

'My Profile'
=> 'Mein Profil',

'View my public page'
=> 'Meine öffentliche Seite',

'My friends'
=> 'Meine Freunde',

'Find %s'
=> '%s finden',

'Create'
=> 'Erstellen',

'%s Home'
=> '%s Start',

'%s Members'
=> '%s Mitglieder',

'%s Gallery'
=> '%s Gallerie',

'%s Events'
=> '%s Ereignisse',

'Join'
=> 'Mitglied werden',

'Unjoin'
=> 'Mitgliedschaft beenden',

'Delete'
=> 'Löschen',

'Are you sure you want to delete this group'
=> 'Bist du sicher, dass du siese Gruppe löschen willst?',

'Edit My Profile'
=> 'Mein Profil bearbeiten',

'Edit My Rigs'
=> 'Meine Rigs bearbeiten',

'Edit My Games'
=> 'Meine Spiele bearbeiten',

'Email Notification'
=> 'Email Benachrichtigung',

'Set Feature Network'
=> '',

'Manage Emblem'
=> '',

'Personalized Video'
=> '',

'Configure Splash Page'
=> '',

'Top Bar Enable/Disable'
=> 'Oberste Menuleiste an/aus',

'Create User'
=> 'Benutzer erstellen',

'User Defaults'
=> 'Benutzer Standardeinstellungen',

'Relationships'
=> 'Beziehungen',

'Manage Users'
=> 'Benutzer verwalten',

'Manage Contents'
=> 'Inhalte verwalten',

'Manage Links'
=> 'Links verwalten',

'General'
=> 'Allgemein',

'Customize UI'
=> 'Layout anpassen',

'Home Page'
=> 'Startseite',

'User Default Page'
=> 'Benutzer Standardseite',

'Group Directory Page'
=> 'Gruppen Verzeichnisseite',

'Network Directory Page'
=> 'Netzwerk Verzeichnisseite',

'Send a message'
=> 'Eine Nachricht senden',

'Delete as '
=> 'Löschen als ',

'Are you sure you want to delete this Relationship'
=> 'Bist du sicher, dass du diese Beziehung löschen willst?',

'Add as '
=> 'Hinzufügen als ',

'Yes'
=> 'Nein',

'No'
=> 'Ja',

'Tags:'
=> 'Stichw&ouml;rter:',

'Overall Rating'
=> '',

'Your Rating'
=> '',

'Please'
=> '',

'log in'
=> '',

'to rate this post'
=> '',

'Are you sure you want  to post the comment?'
=> '',

'Leave a Comment'
=> '',

'Comment'
=> '',

'Submit Comment'
=> '',

'Are you sure you want to post the comment?'
=> '',

'%s Networks'
=> '',

' E-mail address is not valid'
=> '',

'The domain of your E-mail address is not in the list of  allowed domains'
=> '',

'%s\'s Primary Rig'
=> '%ss Haupt Rig',

'Create Group'
=> '',

'Edit Group'
=> '',

'Message sent successfully to '
=> '',

'Last Login'
=> '',

'Latest Registered'
=> '',

'Role can\'t be deleted.'
=> '',

'Successfully deleted.'
=> '',

'Please enter a valid URL!'
=> '',

'Please, select one of the following Professional profiles: '
=> '',

'Please, select the XFN relations you want to import: '
=> '',

'Sorry, we couldn\'t any identity informations '
=> '',

'at: '
=> '',

'in your HTML text.'
=> '',

'Please, select contacts you want to import.'
=> '',

'We haven\'t found any contacts on your Plaxo account.'
=> '',

'Username and/or password field can\'t be empty!'
=> '',

'Apply to User pages'
=> '',

'Apply to this Network'
=> '',

'Apply to '
=> '',

' group'
=> '',

'Tasks/Permissions'
=> '',

'Select any %s file to upload'
=> '',

'You have to login before uploading a %s'
=> '',

'Edit/Assign Role for user: '
=> '',

'Select roles you want to associate with this user and press left/right '
.'arrow, <br />'
=> '',

'We haven\'t found any contacts on your MSLive account.'
=> '',

'Recently Created'
=> '',

'Recently Modified'
=> '',

'Largest Group'
=> '',

'Answer can not be left blank'
=> '',

'Sorry, your Answer cannot be posted as it looks like spam. Try removing any '
.'links to possibly suspect sites, and re-submitting.'
=> '',

'Your Answer has been posted successfully'
=> '',

'Sorry, your answer cannot be posted as it was classified as spam by Akismet, '
.'or contained links to blacklisted sites. Please check the links in your '
.'post, and that your name and e-mail address are correct.'
=> '',

'This section is disabled. Click the checkbox above to show it in your '
.'sidebar widget.'
=> '',

'click to include'
=> '',

'Design your sidebar widget'
=> '',

'Rename this widget'
=> '',

'Rename'
=> '',

'Or'
=> '',

'Delete this widget'
=> '',

'Are you sure you wish to delete this widget?'
=> '',

'Preview'
=> '',

'%s - My Widgets - %s'
=> '',

'About: %s'
=> '',

'Blog'
=> '',

'Flickr'
=> '',

'Delicious'
=> '',

'User Tags (Interests)'
=> '',

'Professional'
=> '',

'Headline'
=> '',

'Company'
=> '',

'Website'
=> '',

'Career skill'
=> '',

'Download CV'
=> '',

'Download'
=> '',

'Prior Company'
=> '',

'Degree'
=> '',

'Personal'
=> '',

'Ethnicity'
=> '',

'Religion'
=> '',

'Political view'
=> '',

'Passion'
=> '',

'Activities'
=> '',

'Cuisines'
=> '',

'TV shows'
=> '',

'Change Group Settings'
=> '',

'File upload error: '
=> '',

'Please select a type.'
=> '',

'TypedEntity associated successfully.'
=> '',

'Please upload a valid Game Image in %s'
=> '',

'Please supply a name.'
=> '',

'Registration Type'
=> '',

'Open'
=> '',

'Moderated'
=> '',

'Invite Only'
=> '',

'Entity Type'
=> '',

'Compose'
=> '',

'Message sent successfully to %s'
=> '',

'Message sending failed for %s  as user(s) doesn\'t exist'
=> '',

'Write Comment for '
=> '',

'\'s Answers'
=> '',

'No answer is posted till now'
=> '',

'Submit your answer'
=> '',

'Answers'
=> '',

'Submit Answers'
=> '',

'Album'
=> '',

'Select Album'
=> '',

'Upload'
=> '',

'Thumbnail'
=> '',

'Title/Description/Date/Tags'
=> '',

'Album/Playlist'
=> '',

'No Audio'
=> '',

'Blog Settings'
=> '',

'You have 3 blog options:'
=> '',

'You can contribute to the community blog'
=> '',

'You also can have a personal blog. A personal blog shows up on your page '
.'with posts routed to the community blog by default. You can opt for those to '
.'only be on your personal blog.'
=> '',

'If you already have a blog, you can display your External Blog here.'
=> '',

'Add a personal blog'
=> '',

'Display my external blog here'
=> '',

'Configure external blog'
=> '',

'Welcome'
=> '',

'Enter your new password'
=> '',

'Re-enter the new password'
=> '',

'Change Password'
=> '',

'Please enter your new password'
=> '',

'Please confirm your new password'
=> '',

'Passwords do not match. Please re-enter'
=> '',

'Manage comments.'
=> '',

'When'
=> '',

'Parent'
=> '',

'Abuses'
=> '',

'No Comments'
=> '',

'Manage Comments'
=> '',

'Anonymous'
=> '',

'Select An email type'
=> '',

'Select an email type'
=> '',

'Available configurable variables'
=> '',

'Restore Default'
=> '',

'Store as Defaults'
=> '',

'Caution - software developers only'
=> '',

'Load / restore Email Message settings from local disk'
=> '',

'Select XML configuration file.'
=> '',

'Select action'
=> '',

'Load Email Message settings'
=> '',

'Revert All Messages'
=> '',

'Warning: you will lose all message changes made at this site.'
=> '',

'Select page'
=> '',

'Select page you want to customize.'
=> '',

'Get module info'
=> '',

'Add this module to: '
=> '',

'Page ID'
=> '',

'If you want to create a new page, enter here an unique Page ID number.'
=> '',

'For dynamic pages, this ID number should start from 200.'
=> '',

'Page Title'
=> '',

'Enter Page name'
=> '',

'Login required'
=> '',

'Select Page type'
=> '',

'Page type'
=> '',

'Enter Page type (user, group, network). For multiple types use "|" to '
.'separate types.'
=> '',

'Is page configurable'
=> '',

'If a page is configurable - these settings will be available in Customize UI '
.'pages.'
=> '',

'Required user or administration permissions for access to this page'
=> '',

'Enter required administration permissions. Currently, these permissions are '
.'available'
=> '',

'Page Theme'
=> '',

'Enter Page theme (Beta)'
=> '',

'Page Outer Template'
=> '',

'Enter Page Outer Template (container_three_column.tpl, container_two_column.'
.'tpl ...)'
=> '',

'Header Template'
=> '',

'Enter Page Header Template (header.tpl, header_group.tpl ...)'
=> '',

'Page boot (pre-execute) PHP code'
=> '',

'Enter here code that should be executed on page boot before any module '
.'initialization function called. Use this only if you have a good reason for '
.'that and when you can\'t place that code inside a module - initializeModule() '
.'function. For example, if some modules need and share same data and you want '
.'to avoid executing same code multiple times. In that case, place here '
.'required code to evaluate those data and forward results to each module via '
.'$module_shared_data variable. For example'
=> '',

'NOTE: If your page does not require additional boot code, leave this '
.'untouched.'
=> '',

'Left modules'
=> '',

'Enter Left modules separated by commas'
=> '',

'Middle modules'
=> '',

'Enter Middle modules separated by commas'
=> '',

'Right modules'
=> '',

'Enter Right modules separated by commas'
=> '',

'Page JavaScript files'
=> '',

'Enter page Javascript file names separated by commas'
=> '',

'Page CSS files'
=> '',

'Enter page CSS file names separated by commas'
=> '',

'Page navigation links PHP code'
=> '',

'Enter code required for generating page navigation links. Here should be '
.'moved code from function'
=> '',

'declared in'
=> '',

'class (web/includes/classes/Navigation.php)'
=> '',

'inside'
=> '',

'statement'
=> '',

'Please see an example below. In this example we will use code written for '
.'generating navigation links on'
=> '',

'page'
=> '',

'So, this PHP code block should be copied and pasted in a text field above. '
.'If old'
=> '',

'page will not be used anymore, this code block should be removed from '
.'Navigation class'
=> '',

'See'
=> '',

'line'
=> '',

'NOTE: Code in the box above is only for example. You must delete it or enter '
.'your menu- navigation code here!'
=> '',

'Page body attributes'
=> '',

'Enter page body CSS attribute. For example'
=> '',

'Save generated page'
=> '',

'Select if you want to save generated Page'
=> '',

'Edit/Create Dynamic Page'
=> '',

'Your page created sucessfull. Page data'
=> '',

'Click here for preview'
=> '',

'Write Testimonial'
=> '',

'Testimonial'
=> '',

'Write Testimonial for '
=> '',

'Left'
=> '',

'Right'
=> '',

'Middle'
=> '',

'Background Image'
=> '',

'Current Background Image'
=> '',

'Upload Background Image'
=> '',

'Image as header background will appear on your Networks Pages'
=> '',

'Apply background image'
=> '',

'Theme Selector'
=> '',

'Module Selector'
=> '',

'Desktop image'
=> '',

'Customize Theme'
=> '',

'Desktop Image'
=> '',

'Upload Desktop Image'
=> '',

'Image will appear on your Personal Pages'
=> '',

'Image will appear on your Groups Pages'
=> '',

'Image will appear on your Networks Pages'
=> '',

'Stretch to fit'
=> '',

'Crop'
=> '',

'Tile'
=> '',

'Leave it alone'
=> '',

'Images 1016 pixels wide by 191 pixels tall will have the best results'
=> '',

'Set Desktop image Turn on/off'
=> '',

'Turn on'
=> '',

'Turn off'
=> '',

'Here to set the Desktop image is display turn on or off.'
=> '',

'Apply desktop image'
=> '',

'Select page layout'
=> '',

'Select page layout template.'
=> '',

'Add a side module'
=> '',

'Select a side module to add it to your page, chose module placement column, '
.'then click "Save settings". '
=> '',

'Add a middle module'
=> '',

'Select a middle module to add it to your page, chose module placement '
.'column, then click "Save settings". '
=> '',

'Available Modules'
=> '',

'Enable'
=> '',

'Show in Left or Right'
=> '',

'Stacking Order'
=> '',

'Use these settings to customize the look of your Network pages'
=> '',

'that others will see.'
=> '',

'Select Theme'
=> '',

'This is the echo test module.'
=> '',

'>Update:'
=> '',

'Echo Test'
=> '',

'Full view'
=> '',

'Select'
=> 'Auswählen',

'Access'
=> '',

'in which your'
=> '',

'file will appear...'
=> '',

'Create New Album'
=> '',

'Return to media gallery'
=> '',

'Basic info'
=> '',

'Login Name'
=> '',

'Upload Photo'
=> '',

'You have 3 blog options'
=> '',

'You also can have a personal blog. A personal blog shows up on your page '
.'with posts routed to the community blog by default. You can opt for those to '
.'only be on your personal blog'
=> '',

'If you already have a blog, you can display your External Blog on My Page'
=> '',

'Blogs/RSS'
=> '',

'Add another Blog'
=> '',

'Permission to view your Blog'
=> '',

'Blog Title'
=> '',

'Blog URL'
=> '',

'Blog Feed URL'
=> '',

'Basic Info'
=> '',

'General Info'
=> '',

'Personal Info'
=> '',

'Professional Info'
=> '',

'Import Contacts'
=> '',

'Export'
=> '',

'If you delete your account, all your content posted and your membership in '
.'other networks will be deleted. Your complete information will be deleted '
.'from the network.'
=> '',

'Personal and professional info'
=> '',

'show everything'
=> '',

'show what your friends see'
=> '',

'show only public info'
=> '',

'Sidebar preview of your hCard/XFN profile'
=> '',

'Please modify the hCard/XFN preview below to suit your taste.'
=> '',

'Once you have selected what you want to display, click \'create hCard\', then '
.'copy the generated HTML to your blog or wherever you want to use it.'
=> '',

'The Date of Birth is invalid.'
=> '',

'Url is invalid'
=> '',

'Sorry: you are unable to save data.'
=> '',

'Reason: '
=> '',

'Select for All'
=> '',

'Slogan'
=> '',

'Slogan will appear on your Public Page.'
=> '',

'Shout Out'
=> '',

'Shout out will appear on your Public Page.'
=> '',

'Date of Birth'
=> '',

'Address'
=> '',

'Address 2'
=> '',

'Zip/Postal Code'
=> '',

'Phone'
=> '',

'Mobile Phone'
=> '',

'Seperate tags with commas.'
=> '',

' Reason: '
=> '',

'Political View'
=> '',

'TV Shows'
=> '',

'Sorry: you are unable to save data'
=> '',

'Upload CV'
=> '',

'Valid file types are .doc and .pdf'
=> '',

'This will replace your current CV'
=> '',

'Work Phone'
=> '',

'Career Skills'
=> '',

'Prior Title'
=> '',

'College Name'
=> '',

'Summary'
=> '',

'Your full Professional biography here. Please note there is a 2,500 '
.'character limit.'
=> '',

'Languages'
=> '',

'Honors &amp; Awards'
=> '',

'Specify how close you are in your relationship with'
=> '',

'User: '
=> '',

'Check if'
=> '',

'is'
=> '',

'in family'
=> '',

'Update Relationship Request'
=> '',

'ADD as a Friend'
=> '',

'Your request for adding '
=> '',

' as a relation has already been sent'
=> '',

'Edit Relationship'
=> '',

'Event'
=> '',

'Event Banner'
=> '',

'Starts'
=> '',

'Ends'
=> '',

'Venue'
=> '',

'Are you sure you want to delete this Event?'
=> '',

'Create new Event'
=> '',

'Edit Event'
=> '',

'Create Event'
=> '',

'Event title'
=> '',

'Start date'
=> '',

'Start time'
=> '',

'End date'
=> '',

'End time'
=> '',

'Event venue'
=> '',

'Event description'
=> '',

'Current Event Banner'
=> '',

'Upload Event Banner'
=> '',

'This event appears on'
=> '',

'Calendar for'
=> '',

'(This event will always appear in the creator\'s calendar.)'
=> '',

'Add to further calendars'
=> '',

'Add people\'s login names here, seperated by commas.'
=> '',

'Groups you are a member of'
=> '',

'Add'
=> '',

'Display as'
=> '',

'List'
=> '',

'Calendar'
=> '',

'External Feeds'
=> '',

'Last login'
=> '',

'Latest registered'
=> '',

'Sort By'
=> '',

'Forgotten your PeopleAggregator account information?'
=> '',

'Just enter the e-mail address or login name you signed up with, and we\'ll '
.'mail you a link to change your password.'
=> '',

'E-mail address:'
=> '',

'Get new password'
=> '',

'Please enter your email address or login name.'
=> '',

'Please enter either email or Login name'
=> '',

'Invalid email address.  Please try again.'
=> '',

'A link has been e-mailed to you to let you change your password.  Thanks!'
=> '',

'There are no accounts in our system with the e-mail address %s.\n'
.'              If you have spelled the address incorrectly or entered the '
.'wrong address, please try again.'
=> '',

'Recover Password'
=> '',

'Latest Forum Posts'
=> '',

'Date'
=> '',

'Forum Name'
=> '',

'Thread Title'
=> '',

'User'
=> '',

'Last Post'
=> '',

'Replies'
=> '',

'No posts'
=> '',

'Posts'
=> '',

'Status'
=> '',

'You will be able to answer this post after admin approve your membership '
.'request'
=> '',

'Banned User'
=> '',

'Administrator message'
=> '',

'label'
=> '',

'Edit post'
=> '',

'Edit thread'
=> '',

'Post title'
=> '',

'Thread title'
=> '',

'Post content'
=> '',

'Thread content'
=> '',

'Forum'
=> '',

'Forum Last post'
=> '',

'Threads'
=> '',

'Category:'
=> '',

'Are you sure you want to delete this category?'
=> '',

'Posted by'
=> '',

'no posts'
=> '',

'Pages: '
=> '',

'Thread'
=> '',

'You will be able to answer this topic after admin approve your membership '
.'request'
=> '',

'Are you sure you want to delete this topic?'
=> '',

'Thread Last post'
=> '',

'Viewed'
=> '',

'Forum:'
=> '',

'Are you sure you want to delete this forum?'
=> '',

'Created by'
=> 'Erstellt von',

'Forums'
=> 'Foren',

'Forum Board for this network has not yet been created.'
=> '',

'Forum Board for this group have not yet been created.'
=> '',

'The personal forum board for this user have not yet been created.'
=> '',

'Post does not exists!'
=> '',

'Thread does not exists!'
=> '',

'New Thread'
=> '',

'You don\'t have permissions to create a new thread!'
=> '',

'Forum does not exists!'
=> '',

'Edit Forum'
=> '',

'New Forum'
=> '',

'Forum title'
=> '',

'Short description'
=> '',

'You don\'t have permissions to create a new forum!'
=> '',

'Category does not exists!'
=> '',

'Edit Category'
=> '',

'New Category'
=> '',

'Category title'
=> '',

'You don\'t have permissions to create a new category!'
=> '',

'network forum board'
=> '',

'group forum board'
=> '',

'personal forum board'
=> '',

'Forum Board description goes here'
=> '',

'Forum Board sucessfully saved'
=> '',

'You don\'t have permissions to create this Forum Board!'
=> '',

'Forum Settings'
=> '',

'Forum name'
=> '',

'Forum description'
=> '',

'Allow anonymous post'
=> '',

'Allow users to create Categories'
=> '',

'Allow users to create Forums'
=> '',

'Membership approval required'
=> '',

'Threads per page'
=> '',

'Posts per page'
=> '',

'Avatar size'
=> '',

'Edit mode'
=> '',

'Forum theme'
=> '',

'Banned users message'
=> '',

'Join requested message'
=> '',

'Join approved message'
=> '',

'You don\'t have permissions to edit Forum Board settings!'
=> '',

'You don\'t have required permissions for this task!'
=> '',

'Thread sucessfully removed'
=> '',

'Forum sucessfully deleted'
=> '',

'Category sucessfully deleted'
=> '',

'Post sucessfully deleted'
=> '',

'Thread not found!'
=> '',

'sticky'
=> '',

'locked'
=> '',

'Thread status sucessfully changed'
=> '',

'Anonymous user can\'t be banned'
=> '',

'You can\'t ban itself.'
=> '',

'Can\'t ban user - user not found!'
=> '',

'User status sucessfully changed.'
=> '',

'User is'
=> '',

'not'
=> '',

'banned now.'
=> '',

'Please, enter your name or email address'
=> '',

'Please, enter correct verification code'
=> '',

'Please, enter reply title'
=> '',

'Please, enter reply message text'
=> '',

'Reply post sucessfully saved'
=> '',

'Please, enter thread title'
=> '',

'Please, enter thread text'
=> '',

'Thread sucessfully created'
=> '',

'Please, enter forum title'
=> '',

'Please, enter forum description text'
=> '',

'Forum sucessfully created'
=> '',

'Forum data sucessfully updated'
=> '',

'Please, enter category title'
=> '',

'Please, enter category description text'
=> '',

'Category sucessfully created'
=> '',

'Category data sucessfully updated'
=> '',

'Please, enter numeric value into the "threads_per_page" field'
=> '',

'Please, enter numeric value into the "posts_per_page" field'
=> '',

'Settings data sucessfully updated'
=> '',

'Title field can\'t be empty'
=> '',

'Content field can\'t be empty'
=> '',

'Post sucessfully saved'
=> '',

'Thread sucessfully saved'
=> '',

'Reply to'
=> '',

'post'
=> '',

'thread'
=> '',

'Reply title'
=> '',

'Reply content'
=> '',

'User '
=> '',

'wrote'
=> '',

'Enter the verification code'
=> '',

'Code'
=> '',

'Your name or email'
=> '',

'Click here to create it'
=> '',

'Forums List'
=> '',

'type: '
=> '',

'board'
=> '',

'Forum Statistics'
=> '',

'Categories'
=> '',

'Topics'
=> '',

'Request to join this group'
=> '',

'Join This Group'
=> '',

'Leave This Group'
=> '',

'You have updated your relation to "%s" successfully.'
=> '',

'You are already a member of "%s"'
=> '',

'Your request to join "%s" has been submitted to the owner of the group.'
=> '',

'You have joined "%s" successfully.'
=> '',

'You need to be logged in to join a group.'
=> '',

'You can\'t leave your own group.'
=> '',

'You are not member of "%s".'
=> '',

'You have left "%s" successfully.'
=> '',

'Group sucessfully deleted.'
=> '',

'Please select a group'
=> '',

'Invite Into Groups'
=> '',

'Invitation could not be sent to following login names- %s'
=> '',

'Invitation could not be sent to following email addresses- %s'
=> '',

'Invitation from %s %s to join %s'
=> '',

'Sorry: you are unable to invite a friend.  Reason: %s'
=> '',

'Select a group to invite into'
=> '',

'Enter Your friend\'s login name(in People Aggregator) or email address'
=> '',

'(separated by comma)'
=> '',

'Write here personalized message for invitees. It will be appended to email'
=> '',

'Write your invitation Message'
=> '',

'Send Invitation'
=> '',

'Moderate Group Members'
=> '',

'Moderate Membership'
=> '',

'Moderate Content'
=> '',

'There are no pending moderation requests'
=> '',

'Sorry you are not authorised to moderate this group'
=> '',

'Content Approved'
=> '',

'Content Denied'
=> '',

'Please select a content for approval'
=> '',

'Please select a content for denial'
=> '',

'Requests'
=> '',

'Approve or deny requests to join this group'
=> '',

'User Approved'
=> '',

'User Denied'
=> '',

'Please select a user for approval'
=> '',

'Please select a user for denial'
=> '',

'Moderate %s Members'
=> '',

'Moderation'
=> '',

'Remove selected members from the %s'
=> '',

'Declare as Moderator'
=> '',

'Declare as Member'
=> '',

'Edit/Assign Role'
=> '',

'There are no members in this %s'
=> '',

'Member(s) Deleted'
=> '',

'Please select a member'
=> '',

'User status sucessfuly changed.'
=> '',

'Can\'t change status for this user.'
=> '',

'member'
=> '',

'No groups created yet. Be the first to <a href="%s" style="display:inline;'
.'">create one</a>!'
=> '',

'No Groups found.'
=> '',

'Click'
=> '',

'to create.'
=> '',

'caption'
=> 'Überschrift',

'Group doesn\'t exist'
=> '',

'Browse %d Groups'
=> '',

'No groups in this category'
=> '',

'On this page you can manage all posts of the %s.'
=> '',

'title'
=> '',

'No Content Published'
=> '',

'On this page you can manage all the forums of the Group.'
=> '',

'Create Forum'
=> '',

'Manage %s Contents'
=> '',

'Largest'
=> '',

'Date Created'
=> '',

'Group Directory'
=> '',

'Create a Group'
=> '',

'Search Groups'
=> '',

'Search for'
=> '',

'Member'
=> 'Mitglied',

'Created'
=> '',

'Moderated By'
=> '',

'No groups found.'
=> '',

'Group Statistics'
=> '',

'No Photos.'
=> '',

'Are you sure you want to delete this image'
=> '',

'Added as a friend by'
=> '',

'Invite friends and colleagues to join %s:'
=> '',

'Choose a program or service below to import your contacts:'
=> '',

'Your Plaxo ID'
=> '',

'(Enter your email or AIM screen name here)'
=> '',

'Enter your password'
=> '',

'We will not store your password. It will only be temporarily used to access '
.'your Plaxo address book.'
=> '',

'Your WindowsLive ID'
=> '',

'(Enter your WindowsLive ID here)'
=> '',

'Your password'
=> '',

'We will not store your password. It will only be temporarily used to access '
.'your Windows Live address book.'
=> '',

'Select CSV file'
=> '',

'(Select CSV file you want to load)'
=> '',

'Email:'
=> '',

'(separate addresses with commas)'
=> '',

' Login Name'
=> '',

'Write your invitation Message:'
=> '',

'Following user names are not valid %s'
=> '',

'Following email addresses are not valid: %s'
=> '',

' Invalid Email addresses'
=> '',

'Sorry: you are unable to invite a friend. Reason: %s'
=> '',

'An Invitation has been sent to - %s'
=> '',

'Invitation Status'
=> '',

'Accepted invitations'
=> '',

'No Accepted Invitations'
=> '',

'Pending invitations'
=> '',

'No pending Invitations'
=> '',

'Largest %s'
=> '',

'Leader Board'
=> '',

'No.'
=> '',

'User Name'
=> '',

'Last Activity Date'
=> '',

'Ranking points'
=> '',

'Ranking stars'
=> '',

'unknown'
=> '',

'There\'s no ranked users.'
=> '',

'Manage your link lists'
=> '',

'Create new'
=> '',

'Edit selected list'
=> '',

'Delete selected list'
=> '',

'Create a list'
=> '',

'New List Name'
=> '',

'Links under the selected list will be shown here'
=> '',

'Create link'
=> '',

'Link caption'
=> '',

'URL'
=> '',

'Links Control Panel'
=> '',

'Sorry - you are not logged in or you have been logged out due to inactivity.'
.'<br />Please, log in again.<br />'
=> '',

'Login'
=> '',

'%s login.'
=> '',

'You can login directly if you have an account,<br />or you can <b><a href="/'
.'register.php">sign up right now</a></b> to create a new account.'
=> '',

'User name: '
=> '',

'Password: '
=> '',

'Remember me on this computer'
=> '',

'Forgot your password?'
=> '',

'Edit Ad'
=> '',

'Create An Ad'
=> '',

'Image'
=> '',

'Page'
=> '',

'Orientation'
=> '',

'Display count'
=> '',

'Hit count'
=> '',

'Enable/Disable'
=> '',

'Disable'
=> '',

'Are you sure you want to delete this Ad'
=> '',

'In this page you can manage ads on your network'
=> '',

'Manage Ads'
=> '',

'Create New Ad'
=> '',

'Enter Title'
=> '',

'Title should not be greater than 30 characters'
=> '',

'Select An Image'
=> '',

'Preferred size'
=> '',

'for side modules and'
=> '',

'for center modules'
=> '',

'Previously Selected Image'
=> '',

'Enter URL'
=> '',

'Or Enter JavaScript(.js code)/ Html code'
=> '',

'Enter Description'
=> '',

'Select Page'
=> '',

'Select a page'
=> '',

'Select Horizontal position'
=> '',

'Select vertical position'
=> '',

'Manage Ad Center'
=> '',

'Edit Textpad'
=> '',

'Create Textpad'
=> '',

'Are you sure you want to delete this Textpad'
=> '',

'Available Textpads'
=> '',

'New Textpad'
=> '',

'In this page you can manage category on your network'
=> '',

'Select Type'
=> '',

'Options'
=> '',

'Create New Category'
=> '',

'Parent Category (Optional)'
=> '',

'Enter Tilte'
=> '',

'You can upload a gif, jpg, jpeg, png, xpm, bmp, file.'
=> '',

'Maximum size'
=> '',

'Do not upload photos containing cartoons, celebrities, nudity, artwork of '
.'copyrighted images.'
=> '',

'For better result image dimension  should be 36x191'
=> '',

'Select a file to upload'
=> '',

'Enter the destination URL of image'
=> '',

'Image title'
=> '',

'Manage Domain List'
=> '',

'Please press enter after each entry'
=> '',

'Edit Link'
=> '',

'Create A Link'
=> '',

'Caption'
=> '',

'Are you sure you want to delete this link?'
=> '',

'In this page you can manage footer links.'
=> '',

'Create New Footer Link'
=> '',

'Enter Caption'
=> '',

'Caption should be less than 30 characters.'
=> '',

'Check this, if you want to open link in a different window'
=> '',

'In this page you can manage groups on your network'
=> '',

'Manage Profanity List'
=> '',

'Edit question'
=> '',

'Create new question'
=> '',

'select'
=> '',

'Question'
=> '',

'Are you sure you want to delete this?'
=> '',

'In this page you can manage questions for your network\'s users'
=> '',

'Set Active Question'
=> '',

'Id'
=> '',

'Edit activity types or add a new type below'
=> '',

'New'
=> '',

'\'Title\' and/or \'Type\' filed should not be empty.'
=> '',

'\'Points\' filed should be numeric and not empty.'
=> '',

'Edit Static Page'
=> '',

'Create Static Page'
=> '',

'Page Text'
=> '',

'Are you sure you want to delete this page?'
=> '',

'In this page you can manage static pages.'
=> '',

'Create New Static Page'
=> '',

'Enter Page Text'
=> '',

'Manage TakeATour'
=> '',

'Video URL'
=> '',

'Video description'
=> '',

'No such content or media file has been deleted from the gallery.'
=> '',

'On this page you can manage all posts you have created.'
=> '',

'All Posts'
=> '',

'Reviews'
=> '',

'Group'
=> '',

'No Content Published.'
=> '',

'Manage Post'
=> '',

'Member Search'
=> '',

'Folder creation failed. '
=> '',

' is not a valid folder name.'
=> '',

'Folder creation failed. You already have a folder named '
=> '',

'1 message has been deleted successfully'
=> '',

' messages have been deleted successfully'
=> '',

'1 message has been moved to folder '
=> '',

' successfully'
=> '',

' messages have been moved to folder '
=> '',

'Selected message(s) are already in '
=> '',

' folder'
=> '',

'Please select message(s) to move'
=> '',

'There are no messages in this folder.'
=> '',

'No messages matched your search'
=> '',

'Compose message'
=> '',

'Create new folder'
=> '',

'Move to:'
=> '',

'- Select Folder -'
=> '',

'(no folders available)'
=> '',

'Sent To'
=> '',

'To:'
=> '',

'Sender'
=> '',

'Search ...'
=> '',

'Inbox'
=> '',

'Sent'
=> '',

'Conversations View'
=> '',

'Go'
=> '',

'Mailbox'
=> '',

'Search Results'
=> '',

'You can\'t access other user\'s messages.'
=> '',

'Conversations'
=> '',

'Please create a folder to move message(s)'
=> '',

'Back to search results'
=> '',

'Reply'
=> '',

'Forward'
=> '',

'Previous'
=> '',

'Next'
=> '',

'Date:'
=> '',

'From:'
=> '',

'Subject:'
=> '',

'In this page you can view Email Addresses of all users'
=> '',

'All Users'
=> '',

'Most Active Users'
=> '',

'Dormant Users'
=> '',

'Email Addresses'
=> '',

'Total Points'
=> '',

'In this page you can view stats about system usage'
=> '',

'Registered Users'
=> '',

'Number of blog post'
=> '',

'Number of Images'
=> '',

'Profile Views'
=> '',

'Maximum'
=> '',

'Minimum'
=> '',

'Average'
=> '',

'Profile Visited by User'
=> '',

'Relations Statistics'
=> '',

'Number of Users by Email Domain:'
=> '',

'Domain Name'
=> '',

'Number of Users'
=> '',

'You haven\'t <a href="%s">created</a> or <a href="%s">joined</a> any '
.'groups yet.'
=> '',

'User has not joined any groups yet.'
=> '',

'No links under this category'
=> '',

'No links have been added. Click <a href="%s">here</a> to add links.'
=> '',

'No links have been added'
=> '',

'My Networks'
=> '',

'No network joined yet.'
=> '',

'Use this tool to send announcements to all registered network members'
=> '',

'Message/post'
=> '',

'Destination'
=> '',

'Deliver message to all registered members by internal mail'
=> '',

'Email message to all network members'
=> '',

'Post message to network home page community blog'
=> '',

'Send to me only'
=> '',

'Manage Network Bulletins'
=> '',

'Please, select your administration task'
=> '',

'Email Notifications'
=> '',

'Notify network operator (me) when'
=> '',

'Registered members receive notifications when'
=> '',

'via their registered email'
=> '',

'via their account inbox'
=> '',

'User settable'
=> '',

'Blink Messages Waiting:'
=> '',

'messages  waiting blinks in network member\'s toolbar when new messages arrive'
=> '',

'Update All Current Users'
=> '',

'Save changes'
=> '',

'Restore Defaults'
=> '',

'Load / restore User Account Defaults from local disk'
=> '',

'Load User Account Defaults'
=> '',

'Configure Network'
=> '',

'Configure Basic Information'
=> '',

'Configure Email Notifications'
=> '',

'Configure User defaults'
=> '',

'Send Announcements'
=> '',

'Configure Relationships'
=> '',

'Save Relationship'
=> '',

'Network Address'
=> '',

'Network address will be part of the URL of your network, e.g. <code>http://'
.'<b>abc</b>.%s/</code>. It should be less than 10 characters.'
=> '',

'Check Availability'
=> '',

'Network Title/Heading'
=> '',

'Title appears on network pages.  For best results, keep below 60 characters '
.'(max 100 characters).'
=> '',

'Network Sub Title'
=> '',

'The sub-title will be displayed below the Network Title.'
=> '',

'Network Category'
=> '',

'This category is used to organise the Network Directory.'
=> '',

'Network Description'
=> '',

'A short paragraph or two describing your network.'
=> '',

'Default Network Language'
=> '',

'Select the Network default language'
=> '',

'Community Blog Title'
=> '',

'The Network group title will be displayed on the homepage.'
=> '',

'Network Icon'
=> '',

'The icon will appear in the network listing.'
=> '',

'Current Icon'
=> '',

'Ideal size 70 x 60 pixels'
=> '',

'Check if content moderation is required.'
=> '',

'Check if People page should only show users with a profile photo.'
=> '',

'Check if you want to enable the languages menu bar.'
=> '',

'Check if top menu bar is not required.'
=> '',

'Check if reciprocated relationships are required.'
=> '',

'Check if email address validation is required.'
=> '',

'Check if CAPTCHA is required during registration.'
=> '',

'Reciprocated relationships are required.'
=> '',

'Reciprocated relationships are not required.'
=> '',

'Email address validation is required.'
=> '',

'Email address validation is not required.'
=> '',

'CAPTCHA is required during registration.'
=> '',

'CAPTCHA is not required during registration.'
=> '',

'Load / restore General Network Settings from local disk'
=> '',

'Load General Settings'
=> '',

'Upload / Download network default settings for this network'
=> '',

'Select XML configuration file for upload.'
=> '',

'Download default settings file'
=> '',

'Upload new default settings file'
=> '',

'New User Account Defaults'
=> '',

'Network friends'
=> '',

'I appear as a friend in all new accounts'
=> '',

'These users appear as friends in all new accounts.'
=> '',

'(enter screen names of registered network users, separated by commas)'
=> '',

'Current default desktop image'
=> '',

'(Images 1016 pixels wide by 191 pixels tall will have the best results)'
=> '',

'Upload default desktop image'
=> '',

'Set desktop image turn on/off'
=> '',

'Media Gallery Images'
=> '',

'Select an image album(s) from your gallery to include in new user default '
.'galleries. (An album in your gallery may contain one or more images.)'
=> '',

'Upload to gallery now'
=> '',

'For multiple selections hold down the &lt;Ctrl&gt;key PC or the &lt;'
.'Command&gt; key(Mac) while clicking the desired selections.'
=> '',

'Media Gallery Audio'
=> '',

'Select an audio album(s) from your gallery to include in new user default '
.'galleries. (An album in your gallery may contain one or more audio clips.)'
=> '',

'Media Gallery Video'
=> '',

'Default Blog'
=> '',

'Select a post to include in new user default.'
=> '',

'Manage link lists'
=> '',

'Select category'
=> '',

'Search Engines'
=> '',

'Ect...'
=> '',

'New List'
=> '',

'Edit List'
=> '',

'Delete List'
=> '',

'Add Link'
=> '',

'Delete Link'
=> '',

'Save Settings'
=> '',

'Network Default Links'
=> '',

'No links have been added.'
=> '',

'Multiple networks are disabled - please configure your system for network '
.'operation.'
=> '',

'The current featured network is: <a href="%s">%s</a>'
=> '',

'Select a featured network:'
=> '',

'Select a network'
=> '',

'Featured Network'
=> '',

'Themes'
=> '',

'Manage Network Links'
=> '',

'No Link Categories'
=> '',

'Link Name'
=> '',

'Manage Network Content'
=> '',

'Search Posts'
=> '',

'Browse Months'
=> '',

'Network Operator Controls'
=> '',

'In this page you can manage users registered on your network'
=> '',

'Search Registered Users'
=> '',

'Moderate content on your network.'
=> '',

'Deny'
=> '',

'Approve'
=> '',

'No Content For Moderation.'
=> '',

'In this page you can moderate users registered on your network'
=> '',

'Picture'
=> '',

'Registered'
=> '',

'Action'
=> '',

'No User.'
=> '',

'Moderate Users'
=> '',

'Manage content on your network.'
=> '',

'Search posts'
=> '',

'Browse months'
=> '',

'Are you sure you want to delete this content?'
=> '',

'No Content.'
=> '',

'Manage Content'
=> '',

'Manage users registered on your network'
=> '',

'Are you sure you want to delete this user?'
=> '',

'pending'
=> '',

'Assign Role'
=> '',

'Selected'
=> '',

'Are you sure?'
=> '',

'(un)check all'
=> '',

'No users'
=> '',

'No networks in this category'
=> '',

'Network Directory'
=> '',

'Search Networks'
=> '',

'No networks found'
=> '',

'Network Statistics'
=> '',

'Newest %s'
=> '',

'Networks'
=> '',

'Largest Network'
=> '',

'No network created yet.'
=> '',

'Provide a login name, email address and basic information for a new network '
.'member.'
=> '',

'Upon hitting the create button, the new member will be emailed a greeting '
.'including an auto-generated password.'
=> '',

'Fields marked with an asterisk (*) are mandatory.'
=> '',

'Email address'
=> '',

'Photo/avatar'
=> '',

'Auto-generate new password for network member'
=> '',

'Manual password'
=> '',

'modify greeting if desired and click the create user button below tocomplete '
.'process'
=> '',

'Hi,'
=> '',

'I\'ve created my own place on PeopleAggregator and I\'d like you to'
=> '',

'connect to me so we can stay in touch.'
=> '',

'You can view my blog, my reviews, my ratings, my photos, my lists -'
=> '',

'and all sorts of things that matter to me.'
=> '',

'You can create a personal page and blog of your own, which will be'
=> '',

'linked to mine.'
=> '',

'That way you\'ll always know when I post something new!'
=> '',

'Location'
=> '',

'Age'
=> '',

'Vote'
=> '',

'Most Popular Tags'
=> '',

'Nothing has been tagged yet.'
=> '',

'edit your post'
=> '',

'create your post'
=> '',

'Routing'
=> '',

'Community Blog'
=> '',

'Post to %s (On this networks home page)'
=> '',

'You can route this post to one or many destinations with the selectors below.'
=> '',

'Please note that routing does not post to private groups'
=> '',

'Post to community Blog (On this networks home page)'
=> '',

'Send to selected group blogs'
=> '',

'Send to selected external blogs'
=> '',

'Select albums in your media gallery to send to'
=> '',

'Select none of my galleries'
=> '',

'Select all of my galleries'
=> '',

'No Albums'
=> '',

'Or, create a new album in your media gallery'
=> '',

'Add Blog Post'
=> '',

'Default Image Album'
=> '',

'Default Audio Album'
=> '',

'Default Video Album'
=> '',

'Blogs'
=> '',

'Question of the Day'
=> '',

'Site Ranking'
=> '',

'Recent Posts'
=> '',

'No contents in blog.  <a href="%s">Click here to make a post</a>!'
=> '',

'Browse Tags'
=> '',

'Nothing has been tagged yet'
=> '',

's made yet.'
=> '',

'Send request for joining network'
=> '',

'Your request to join this network could not be sent due to following reason: '
.'%s. You can go back to the home network by clicking Return to home network'
=> '',

'Your request to join this network has been successfully sent to the '
.'moderator of this network. The Moderator will check this request and approve '
.'or deny the request. You can go back to mother network by clicking the '
.'button Return to home network'
=> '',

'Return to home network successfully.'
=> '',

'Request Message'
=> '',

'Welcome to PeopleAggregator'
=> '',

'This is a private network'
=> '',

'You need to be member of this network to do anything. You can send a request '
.'to join this network by clicking \'Request to join\'.'
=> '',

'In this page you can manage different admin roles'
=> '',

'Sr.No.'
=> '',

'No roles have been created yet.'
=> '',

'Add New Role'
=> '',

'Load / restore Roles Settings from local disk'
=> '',

'Load Roles Settings'
=> '',

'Manage Roles'
=> '',

'Invalid configuration file format. Configuration file should be a valid XML '
.'file. '
=> '',

'Roles settings successfully loaded from '
=> '',

' file.'
=> '',

'Please, select a valid XML configuration file.'
=> '',

'Role data sucessfully updated.'
=> '',

'New Role sucessfully created.'
=> '',

'Role sucessfully deleted.'
=> '',

'This Role can\'t be deleted.'
=> '',

'Select Task(s) you want to assign to this Role and press left/right arrow.'
=> '',

'Default Roles settings sucessfully restored.'
=> '',

'There is no Roles data in default XML settings file.'
=> '',

'Tag Search'
=> 'Stichwort Suche',

'Search Terms'
=> 'Such Begriffe',

'all of these words'
=> 'all diese Wörter',

'this exact phrase'
=> 'genau diese Phrase',

'any of these words'
=> 'beliebige dieser Wörter',

'none of these words'
=> 'keines dieser Wörter',

'Date Range'
=> 'Datums Bereich',

'Start Date'
=> 'Start Datum',

'End Date'
=> 'End Datum',

'Search Content'
=> 'Inhalte durchsuchen',

'Poll Topic'
=> '',

'Number Of Options'
=> '',

'Select Any One Topic'
=> '',

'No poll is created yet.'
=> '',

'Poll has been deleted successfully.'
=> '',

'Poll has been saved successfully.'
=> '',

'Poll has been created successfully.'
=> '',

'Announcements'
=> '',

'Date range selected is invalid. Please, select a valid date range.'
=> '',

'Return to private page'
=> '',

'No items match your search criteria.'
=> '',

'Back'
=> '',

'You will be redirected in '
=> '',

' seconds, or you can click here to redirect now'
=> '',

'An Error Has Occurred'
=> '',

'Error details'
=> '',

'Information'
=> '',

'Please confirm action'
=> '',

'Warning!'
=> '',

'No Testimonial Found'
=> '',

'Testimonials'
=> '',

'New Testimonials'
=> '',

'No Comments Found'
=> '',

'Comments for '
=> '',

'Show Splash Page'
=> '',

'If this checkbox is checked then Splash Page will be the first page to be '
.'shown to the anonymous users otherwise Homepage will be the first page'
=> '',

'Network URL'
=> '',

'Network of the Moment Image'
=> '',

'No image selected.'
=> '',

'Upload Image'
=> '',

'Uploaded image will be displayed at 193 pixels by 67 pixels'
=> '',

'Save Network of the Moment'
=> '',

'Uploaded image will be displayed at 193 pixels by 67 pixels.'
=> '',

'Uploaded image will be displayed at 185 pixels by 110 pixels.'
=> '',

'Save Announcement'
=> '',

'Showcased Network '
=> '',

'Showcased Network URL'
=> '',

'Paste the complete URL of the network here'
=> '',

'Showcased Network Image'
=> '',

'Uploaded images will be displayed at 145 pixels by 145 pixels.'
=> '',

'Set Showcased Networks'
=> '',

'Network of the Moment'
=> '',

'Video Tours Image'
=> '',

'Save Video Tour'
=> '',

'Click here to watch the video'
=> '',

'Take A Tour'
=> '',

'In this page you can assign roles to tasks'
=> '',

'No roles have been created yet'
=> '',

'Assign Roles to Tasks'
=> '',

'Terms and conditions for using'
=> '',

'Create new %s'
=> '',

'There are %s entries in this directory.'
=> '',

'Master Directory'
=> '',

'%s directory'
=> '',

'There is no TypedEntity associated with this Group yet. Would you like to '
.'create one?'
=> '',

'--- Please select ---'
=> '',

'Create it'
=> '',

'Update relation'
=> '',

'-- Please select --'
=> '',

'Update'
=> '',

'Typed Group Settings'
=> '',

'Sorry, you can\'t perform this action.'
=> '',

'Request to join this group as'
=> '',

'Join This Group as'
=> '',

'You are a %s'
=> '',

'Edit %s profile'
=> '',

'%s profile'
=> '',

'You can upload a gif, jpg, jpeg, png, xpm or bmp file'
=> '',

'Do not upload photos containing cartoons, celebrities, nudity, artwork or '
.'copyrighted images'
=> '',

'Upload image'
=> '',

'Select who can see this image'
=> '',

'You can upload an audio file'
=> '',

'Audio title'
=> '',

'Tags (separate with commas)'
=> '',

'Add More'
=> '',

'Or finish below'
=> '',

'Upload audio'
=> '',

'You can upload a video file'
=> '',

'Video title'
=> '',

'Upload video'
=> '',

'Select a file to upload, or enter a URL below'
=> '',

'Audio URL'
=> '',

'Select who can listen this Audio'
=> '',

'Send to album'
=> '',

'Or create new album'
=> '',

'Image URL'
=> '',

'Unkonwn type selected'
=> '',

'LinkedIn Contacts: '
=> '',

'No contacts'
=> '',

'MS Live Contacts: '
=> '',

'Contacts'
=> '',

'External Accounts'
=> '',

'ID Hub'
=> '',

'Import'
=> '',

'Outlook Contacts: '
=> '',

'Plaxo Contacts: '
=> '',

' contact(s) sucessfully imported'
=> '',

'Invalid file type. Please select a valid LinkedIn CSV file. '
=> '',

'Please, select a valid LinkedIn CSV file.'
=> '',

'Invalid file type. Please select a valid Outlook CSV file. '
=> '',

'Please, select a valid Outlook CSV file.'
=> '',

'Invite message can\'t be empty.'
=> '',

'Please, select one or more contacts.'
=> '',

' contact(s) sucessfully deleted.'
=> '',

'No details.'
=> '',

'Messages'
=> '',

'No Videos'
=> '',

'No Video'
=> '',

'Are you sure you want to delete this video'
=> '',

'There are %d members in %s.'
=> '',

'There are %d friends.'
=> '',

'There are '
=> '',

' members '
=> '',

'There are %d members in this %s.'
=> '',

'There are %d members.'
=> '',

'There are %d friends for %s.'
=> '',

'member since:'
=> '',

'No relation exists.'
=> '',

'View all '
=> '',

'View all people who call '
=> '',

'me a friend'
=> '',

' as a friend'
=> '',

'Polls'
=> '',

'No previous poll to display'
=> '',

'No votes are posted for this poll'
=> '',

'Edit Events'
=> '',

'Business'
=> '',

'Church'
=> '',

'School'
=> '',

'Fan'
=> '',

'Supporter'
=> '',

'Customer'
=> '',

'Employee'
=> '',

'Postal Code'
=> '',

'Phone Number'
=> '',

'PeopleAggregator setup'
=> '',

'Already configured'
=> '',

'It looks like this PeopleAggregator is already set up.'
=> '',

'Click here to log in'
=> '',

'If something went wrong and you want to reconfigure PeopleAggregator, delete '
.'the'
=> '',

'file and refresh this page'
=> '',

'Almost done!'
=> '',

'Congratulations - you have nearly finished installing PeopleAggregator!'
=> '',

'The final step is to move the'
=> '',

'file from'
=> '',

'up into the'
=> '',

'directory'
=> '',

'On Linux, the following command will do so'
=> '',

'Once that is done, please refresh this page'
=> '',

'Alternatively, if something went wrong and you want to reconfigure '
.'PeopleAggregator, delete'
=> '',

'the'
=> '',

'Email Messages settings data successfully loaded from '
=> '',

'Email message settings successfully restored.'
=> '',

'Network URL cannot be left empty for showcased network '
=> '',

' For showcased network '
=> '',

'No caption given to network of moment'
=> '',

'Please provide URL for network of moment'
=> '',

'No video URL provided for video tours'
=> '',

'No description provided for network of moment'
=> '',

' For network of moment, '
=> '',

'You need to be member of this group to view the contents'
=> '',

'Networks are disabled.'
=> '',

'Network spawning disabled.'
=> '',

'Create Network - %s'
=> '',

'There was a problem:<br>No message(s) selected. Please select at least one '
.'message and try again.'
=> '',

'There was a problem:'
=> '',

'No folder selected. Please select a folder and try again.'
=> '',

'No message(s) selected. Please select at least one message and try again.'
=> '',

'page_name'
=> '',

' updated successfully'
=> '',

'%s - Edit your profile - %s'
=> '',

'Sorry! you are not authorized to view content of this page'
=> '',

'File '
=> '',

' loaded successfully.'
=> '',

'Click "Save" button to save new settings.'
=> '',

'Default settings sucessfully restored.'
=> '',

'User default Notifications Settings successfully updated.'
=> '',

'Setting correct default Notifications for Videoplay installations'
=> '',

'Groups - %s'
=> '',

'Data mapping error. Invalid data format.'
=> '',

'-no email address-'
=> '',

'Current %s'
=> '',

'Current Logo'
=> '',

'Upload %s'
=> '',

'Your file is too large for the web server.  The largest file you can upload '
.'here is %.1fM.  If this is too small, please ask the administrator to '
.'increase the <code>upload_max_filesize</code> directive in <code>php.ini</'
.'code>.'
=> '',

'The uploaded file was only partially uploaded.'
=> '',

'No file was uploaded'
=> '',

'File %s not uploaded correctly.'
=> '',

'File is not uploaded correctly.'
=> '',

'File too large; %s file uploads are limited to %s.  If this is too small, '
.'please ask the administrator to increase the limit.'
=> '',

'Invalid image file.'
=> '',

'Invalid media file.'
=> '',

'Invalid document type - supported formats are: %s'
=> '',

'File error: File already exists'
=> '',

'Security error: File %s is not an uploaded file:'
=> '',

'XML parsing error!'
=> '',

'Data not found or XML parsing error!'
=> '',

'Can\'t get data from URL. Please, check the given URL.'
=> '',

'Can\'t open file \''
=> '',

'File'
=> '',

'doesn\'t exist.'
=> '',

'No data! Check is file empty.'
=> '',

'My Widgets'
=> '',

'My Forum'
=> '',

'Edit My Account'
=> '',

'%s who call me friend'
=> '',

'Friends gallery'
=> '',

'%s Forum'
=> '',

'Change '
=> '',

'Write Comment'
=> '',

'First'
=> '',

'Last'
=> '',

'Could not retrieve file from URL: %s'
=> '',

'Hi '
=> '',

'Activate your '
=> '',

' account by clicking the following link:'
=> '',

'User ID or Password field can\'t be blank.'
=> '',

'Invalid or missing SOAP XML file'
=> '',

'Invalid response received from'
=> '',

'Invalid XML response received from'
=> '',

'BinarySecurityToken not found in XML response received from'
=> '',

'Can\'t estabilish WEB connection.'
=> '',

'Unknown communication error has been occured.'
=> '',

'Communication error - no response received.'
=> '',

'AdrBook: Invalid response received from'
=> '',

'no name'
=> '',

'no email'
=> '',

'Plaxo data parser error.'
=> '',

'Invalid Plaxo Header received.'
=> '',

'Unable to get list of the Plaxo folders.'
=> '',

'Unable to read the Plaxo folders.'
=> '',

'Sorry - you are not logged in or you have been logged out due to inactivity. '
.'Please, log in again.'
=> '',

'Myself'
=> '',

'Everyone'
=> '',

'Friends Only'
=> '',

'In Family'
=> '',

'Network name'
=> '',

'Network address'
=> '',

'Network tagline'
=> '',

'Group name'
=> '',

'Group description'
=> '',

'Group tag'
=> '',

'Select age'
=> '',

'Under 10 years'
=> '',

'11-20 years'
=> '',

'21-30 years'
=> '',

'31-40 years'
=> '',

'41-50 years'
=> '',

'Over 50 years'
=> '',

'Select horizontal position'
=> '',

'left'
=> '',

'center'
=> '',

'right'
=> '',

'top'
=> '',

'Create Post'
=> '',

'Messages '
=> '',

'Edit my account'
=> '',

'Invite people - %s'
=> '',

'%s - My Links - %s'
=> '',

'Group deleted successfully'
=> '',

' deleted successfully'
=> '',

'Question is set for all users'
=> '',

'Please select a question to activate.'
=> '',

'Question has been successfully saved'
=> '',

'Fields marked with * must not be left empty'
=> '',

'Question has been deleted successfully'
=> '',

'Successfully updated'
=> '',

' is already enabled at specified orientation'
=> '',

'Please select atleast one user.'
=> '',

'Status of selected user(s) updated successfully'
=> '',

'An error has occured on deleting users.'
=> '',

'%s - Private Messages - %s'
=> '',

' uploaded successfully.'
=> '',

'Please confirm network deletion by selecting deletion checkbox.'
=> '',

'Network Statistics - %s'
=> '',

'General Network Settings'
=> '',

'Administration panel'
=> '',

'Following relations could not be added as default relation '
=> '',

'Default settings for the network has been saved'
=> '',

'Click "Save" button to store new settings.'
=> '',

'Request to join'
=> '',

'Your comment contains some illegal characters. Please try again.'
=> '',

'Comment can not be left blank'
=> '',

'Sorry, your comment cannot be posted as it looks like spam. Try removing any '
.'links to possibly suspect sites, and re-submitting.'
=> '',

'Your comment has been posted successfully'
=> '',

'Sorry, your comment cannot be posted as it was classified as spam by '
.'Akismet, or contained links to blacklisted sites.  Please check the links in '
.'your post, and that your name and e-mail address are correct.'
=> '',

'Sorry, your comment cannot be posted as it was classified as spam by '
.'Akismet, or contained links to blacklisted sites. Please check the links in '
.'your post, and that your name and e-mail address are correct.'
=> '',

'Terms and Conditions - %s'
=> '',

'basecamp test disabled'
=> '',

'please enter your basecamp login details above.'
=> '',

'scraping contacts page to get companies'
=> '',

'getting list of people from company '
=> '',

' who are working on this project'
=> '',

'testing ImageResize module with engine'
=> '',

'make sure to hit ctrl-F5 after clicking, to clear the cache'
=> '',

'flushing cache'
=> '',

'done'
=> '',

'expanding and cropping 135x75 to fit inside 300x300'
=> '',

'reduce only'
=> '',

'fitting 135x75 inside 300x300'
=> '',

'reduce only, smaller'
=> '',

'Report abuse'
=> '',

'Submit Abuse'
=> '',

'Right-click to download'
=> '',

'to rate this audio'
=> '',

'posted by %s on %s'
=> '',

'permalink'
=> '',

'comments'
=> '',

'Unknown error.'
=> '',

'Detailed information has been written into the error log.'
=> '',

'Begins'
=> '',

'&copy;'
=> '',

'Already a member?'
=> '',

'shortcuts'
=> '',

'register'
=> '',

'to rate this image'
=> '',

'view all'
=> '',

'to rate this video'
=> '',

'Showing profile fields in sidebar widget.'
=> '',

'peopleaggregator: widgetization testbench'
=> '',

'Select a module'
=> '',

'Module'
=> '',

'Request'
=> '',

'Response'
=> '',

'Rendered response'
=> '',

'An unknown error occurred - no response available.'
=> '',

'Note: do not enable widgetization on public facing webservers as it allows '
.'operations to be performed as arbitrary users! Access must be restricted to '
.'trusted front-end systems.'
=> '',

'This file may not be called directly.'
=> '',

'No admininstrator password configured'
=> '',

'To use the updater, add a line like this to'
=> '',

'Log in'
=> '',

'All the files have been updated. Now you need to'
=> '',

'click here to update the database'
=> '',

'and the update will be complete'
=> '',

'Error occurred running database update:'
=> '',

'PeopleAggregator system update'
=> '',

'%s - Media Gallery - %s'
=> '',

'View All Members'
=> '',

'View All Group Members'
=> '',

'Comment can not be empty'
=> '',

'Please login to comment'
=> '',

'Your Recommendation: '
=> '',

'Error processing request'
=> '',

'Error parsing URL'
=> '',

'User Public Page'
=> '',

'User Private Page'
=> '',

'People Page'
=> '',

'Blog Post Permalink Page'
=> '',

'Group Page'
=> '',

'Forums Page'
=> '',

'Search Page'
=> '',

'Date Established'
=> '',

'Honors / Awards'
=> '',

'Religion / Faith'
=> '',

'Congregational member'
=> '',

'Church member'
=> '',

'Church goer'
=> '',

'owner'
=> '',

'admin'
=> '',

'banned'
=> '',

'limited'
=> '',

'Cannot create networks: this installation is not configured for network '
.'operation.'
=> '',

'Cannot create networks: %s is not writable'
=> '',

'Cannot create networks: Network spawning has been disabled on this '
.'installation.'
=> '',

'Files with extension \'%s\' may not be uploaded'
=> '',

'Unable to determine image type'
=> '',

'File MIME type is %s, expected %s'
=> '',

'Latest posts from %s'
=> '',

'Newest posts from everyone on %s'
=> '',

'%s: %s blog'
=> '',

'Failed to retrieve %s: %s'
=> '',

'Are you sure you want to delete this Ad?'
=> '',

'Ad Center'
=> '',

'%s - %s'
=> '',

'Caption has already been taken, please enter a different caption'
=> '',

'Ad Title can not have empty.'
=> '',

'Ad Target page is not specified.'
=> '',

'middle'
=> '',

'Me'
=> 'Ich',

'(%d %ss)'
=> '(%d %se)',

'Forum Board for this group has not yet been created.'
=> '',

'The personal forum board for this user has not yet been created.'
=> '',

'Post does not exist!'
=> '',

'Thread does not exist!'
=> '',

'You do not have permission to manage Ads.'
=> '',

'Add as %s'
=> '',

);

?>