<?php
// Call TasksTest::main() if this source file is executed directly.
if (!defined("PHPUnit_MAIN_METHOD")) {
    define("PHPUnit_MAIN_METHOD", "TasksTest::main");
}
require_once dirname(__FILE__)."/lib/common.php";
require_once "api/Tasks/Tasks.php";


/**
 * Test class for Tasks.
 * Generated by PHPUnit_Util_Skeleton on 2007-04-23 at 06:12:28.
 */
class TasksTest extends PHPUnit_Framework_TestCase {
    /**
     * Runs the test methods of this class.
     *
     * @access public
     * @static
     */
    public static function main() {
        require_once "PHPUnit/TextUI/TestRunner.php";

        $suite  = new PHPUnit_Framework_TestSuite("TasksTest");
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

    /**
     * Sets up the fixture, for example, open a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp() {
    }

    /**
     * Tears down the fixture, for example, close a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown() {
    }

    /**
     * @todo Implement testGet_instance().
     */
    public function testGet_instance() {
        // Remove the following line when you implement this test.
        $this->markTestIncomplete(
          "This test has not been implemented yet."
        );
    }

    /**
     * @todo Implement testGet_tasks().
     */
    public function testGet_tasks() {
        // Remove the following line when you implement this test.
        $this->markTestIncomplete(
          "This test has not been implemented yet."
        );
    }
}

// Call TasksTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == "TasksTest::main") {
    TasksTest::main();
}
?>
